// Code generated by protoc-gen-go. DO NOT EDIT.
// source: permission/pb/binding.proto

package gosionsvc_external_permission

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "konekko.me/gosion/commons/dto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BindingRolesRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Roles                []string `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindingRolesRequest) Reset()         { *m = BindingRolesRequest{} }
func (m *BindingRolesRequest) String() string { return proto.CompactTextString(m) }
func (*BindingRolesRequest) ProtoMessage()    {}
func (*BindingRolesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d6cdac82fda43c5, []int{0}
}

func (m *BindingRolesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindingRolesRequest.Unmarshal(m, b)
}
func (m *BindingRolesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindingRolesRequest.Marshal(b, m, deterministic)
}
func (m *BindingRolesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindingRolesRequest.Merge(m, src)
}
func (m *BindingRolesRequest) XXX_Size() int {
	return xxx_messageInfo_BindingRolesRequest.Size(m)
}
func (m *BindingRolesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BindingRolesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BindingRolesRequest proto.InternalMessageInfo

func (m *BindingRolesRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *BindingRolesRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BindingRolesRequest) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type BindingRoleRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	RoleId               string   `protobuf:"bytes,3,opt,name=roleId,proto3" json:"roleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindingRoleRequest) Reset()         { *m = BindingRoleRequest{} }
func (m *BindingRoleRequest) String() string { return proto.CompactTextString(m) }
func (*BindingRoleRequest) ProtoMessage()    {}
func (*BindingRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d6cdac82fda43c5, []int{1}
}

func (m *BindingRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindingRoleRequest.Unmarshal(m, b)
}
func (m *BindingRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindingRoleRequest.Marshal(b, m, deterministic)
}
func (m *BindingRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindingRoleRequest.Merge(m, src)
}
func (m *BindingRoleRequest) XXX_Size() int {
	return xxx_messageInfo_BindingRoleRequest.Size(m)
}
func (m *BindingRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BindingRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BindingRoleRequest proto.InternalMessageInfo

func (m *BindingRoleRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *BindingRoleRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BindingRoleRequest) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

func init() {
	proto.RegisterType((*BindingRolesRequest)(nil), "gosionsvc.external.permission.BindingRolesRequest")
	proto.RegisterType((*BindingRoleRequest)(nil), "gosionsvc.external.permission.BindingRoleRequest")
}

func init() { proto.RegisterFile("permission/pb/binding.proto", fileDescriptor_5d6cdac82fda43c5) }

var fileDescriptor_5d6cdac82fda43c5 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0xd2, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0x07, 0x70, 0xd6, 0xe1, 0xd4, 0x87, 0xec, 0x10, 0x65, 0x94, 0x89, 0x30, 0x76, 0x12, 0x84,
	0x04, 0xe7, 0x7f, 0xe0, 0x41, 0xd8, 0xd1, 0xca, 0x04, 0xf1, 0x20, 0x6d, 0x13, 0x4a, 0xe8, 0x9a,
	0x17, 0xf3, 0x52, 0xf1, 0x6f, 0xf7, 0x24, 0x49, 0x36, 0xf5, 0x20, 0xfe, 0x00, 0xbd, 0xf5, 0xbd,
	0x7e, 0xfb, 0xe1, 0xf5, 0x25, 0x70, 0x6c, 0x95, 0xeb, 0x34, 0x91, 0x46, 0x23, 0x6c, 0x25, 0x2a,
	0x6d, 0xa4, 0x36, 0x0d, 0xb7, 0x0e, 0x3d, 0xb2, 0x93, 0x06, 0xc3, 0x0b, 0x7a, 0xaa, 0xb9, 0x7a,
	0xf6, 0xca, 0x99, 0x72, 0xcd, 0xdf, 0xf3, 0xd3, 0xb3, 0x16, 0x8d, 0x6a, 0x5b, 0xe4, 0x9d, 0x12,
	0x29, 0x29, 0x6a, 0xec, 0x3a, 0x34, 0x24, 0xa4, 0xc7, 0xed, 0x73, 0xb2, 0xe6, 0xd7, 0x70, 0x78,
	0x99, 0xf0, 0x02, 0xd7, 0x8a, 0x0a, 0xf5, 0xd8, 0x2b, 0xf2, 0xec, 0x08, 0x76, 0x4a, 0x6b, 0x97,
	0x32, 0x1f, 0xcc, 0x06, 0xa7, 0xfb, 0x45, 0x2a, 0xd8, 0x18, 0x32, 0x2d, 0xf3, 0x2c, 0xb6, 0x32,
	0x2d, 0x43, 0xca, 0x85, 0xaf, 0xf2, 0xe1, 0x6c, 0x18, 0x52, 0xb1, 0x98, 0x17, 0xc0, 0x3e, 0x90,
	0xbf, 0x13, 0x27, 0x30, 0x0a, 0xc8, 0x52, 0xe6, 0xc3, 0xd8, 0xdb, 0x54, 0x8b, 0x97, 0x0c, 0x76,
	0x37, 0x28, 0xbb, 0x85, 0xbd, 0x15, 0x29, 0x17, 0x70, 0xb6, 0xe0, 0x5f, 0xee, 0x82, 0x7f, 0xf2,
	0x6f, 0xd3, 0x09, 0x6f, 0x88, 0x6f, 0xb7, 0x20, 0x3d, 0xf2, 0x1b, 0x5f, 0xfa, 0x9e, 0xd8, 0x1d,
	0x1c, 0x5c, 0xf5, 0xa6, 0xf6, 0x1a, 0x4d, 0xb4, 0xcf, 0x7f, 0x6e, 0x7f, 0x47, 0xdf, 0xc3, 0x78,
	0x65, 0xc2, 0x21, 0xbe, 0x0d, 0xfe, 0x87, 0xf8, 0x03, 0xb0, 0x84, 0xff, 0xd3, 0xf4, 0xd5, 0x28,
	0x5e, 0x95, 0x8b, 0xd7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x90, 0x7a, 0xad, 0x0d, 0x95, 0x02, 0x00,
	0x00,
}
