// Code generated by protoc-gen-go. DO NOT EDIT.
// source: permission/pb/dat.proto

package gs_service_permission

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	dto "konekko.me/gosion/commons/dto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DurationAccessRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Code                 int64    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DurationAccessRequest) Reset()         { *m = DurationAccessRequest{} }
func (m *DurationAccessRequest) String() string { return proto.CompactTextString(m) }
func (*DurationAccessRequest) ProtoMessage()    {}
func (*DurationAccessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a56d7a64efc26c6, []int{0}
}

func (m *DurationAccessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DurationAccessRequest.Unmarshal(m, b)
}
func (m *DurationAccessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DurationAccessRequest.Marshal(b, m, deterministic)
}
func (m *DurationAccessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DurationAccessRequest.Merge(m, src)
}
func (m *DurationAccessRequest) XXX_Size() int {
	return xxx_messageInfo_DurationAccessRequest.Size(m)
}
func (m *DurationAccessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DurationAccessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DurationAccessRequest proto.InternalMessageInfo

func (m *DurationAccessRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *DurationAccessRequest) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DurationAccessRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type DurationAccessResponse struct {
	State                *dto.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DurationAccessResponse) Reset()         { *m = DurationAccessResponse{} }
func (m *DurationAccessResponse) String() string { return proto.CompactTextString(m) }
func (*DurationAccessResponse) ProtoMessage()    {}
func (*DurationAccessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a56d7a64efc26c6, []int{1}
}

func (m *DurationAccessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DurationAccessResponse.Unmarshal(m, b)
}
func (m *DurationAccessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DurationAccessResponse.Marshal(b, m, deterministic)
}
func (m *DurationAccessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DurationAccessResponse.Merge(m, src)
}
func (m *DurationAccessResponse) XXX_Size() int {
	return xxx_messageInfo_DurationAccessResponse.Size(m)
}
func (m *DurationAccessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DurationAccessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DurationAccessResponse proto.InternalMessageInfo

func (m *DurationAccessResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *DurationAccessResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*DurationAccessRequest)(nil), "gs.service.permission.DurationAccessRequest")
	proto.RegisterType((*DurationAccessResponse)(nil), "gs.service.permission.DurationAccessResponse")
}

func init() { proto.RegisterFile("permission/pb/dat.proto", fileDescriptor_1a56d7a64efc26c6) }

var fileDescriptor_1a56d7a64efc26c6 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x91, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0x69, 0x37, 0x95, 0x45, 0xd8, 0x45, 0xa0, 0x5a, 0x76, 0x35, 0x76, 0x35, 0x98, 0x9e,
	0xc2, 0x7c, 0x02, 0xc1, 0x7b, 0xa1, 0x3e, 0x80, 0x64, 0xc9, 0xa1, 0x96, 0x92, 0x9c, 0xd8, 0x73,
	0xea, 0xc3, 0xfa, 0x34, 0xb2, 0xd4, 0x22, 0xca, 0x2e, 0xbc, 0xd9, 0xdd, 0x9f, 0xe4, 0xcf, 0xff,
	0xfd, 0xc9, 0x51, 0xb7, 0x11, 0x7b, 0xdf, 0x32, 0xb7, 0x14, 0xaa, 0x78, 0xa8, 0x9c, 0x11, 0x88,
	0x3d, 0x09, 0xe9, 0xa2, 0x61, 0x60, 0xec, 0x3f, 0x5a, 0x8b, 0xf0, 0xe3, 0x59, 0xed, 0x3a, 0x0a,
	0xd8, 0x75, 0x04, 0x1e, 0xab, 0x86, 0xd2, 0x35, 0x4b, 0xde, 0x53, 0xe0, 0xca, 0x09, 0x4d, 0x7a,
	0xcc, 0xd8, 0x3c, 0xab, 0xe2, 0x69, 0xe8, 0x8d, 0xb4, 0x14, 0x1e, 0xad, 0x45, 0xe6, 0x1a, 0xdf,
	0x07, 0x64, 0xd1, 0x5a, 0xcd, 0xa3, 0x91, 0xb7, 0x32, 0x5b, 0x67, 0xdb, 0x45, 0x9d, 0xf4, 0x71,
	0xcf, 0x92, 0xc3, 0x32, 0x5f, 0x67, 0xdb, 0x59, 0x9d, 0xb4, 0x5e, 0xaa, 0x5c, 0xa8, 0x9c, 0x25,
	0x57, 0x2e, 0xb4, 0x79, 0x55, 0x37, 0x7f, 0x03, 0x39, 0x52, 0x60, 0xd4, 0x3b, 0x75, 0xc1, 0x62,
	0x04, 0x53, 0xe4, 0xf5, 0xbe, 0x80, 0x86, 0x61, 0x2a, 0xe3, 0x84, 0xe0, 0xe5, 0x78, 0x58, 0x8f,
	0x1e, 0x5d, 0xaa, 0x2b, 0x8f, 0xcc, 0xa6, 0x19, 0x69, 0x8b, 0x7a, 0x5a, 0xee, 0x3f, 0x33, 0xb5,
	0xfc, 0x4d, 0xd0, 0x56, 0xcd, 0x9d, 0x91, 0x41, 0xdf, 0xc1, 0xc9, 0x1f, 0x81, 0x93, 0x2f, 0x5c,
	0xdd, 0xff, 0xd3, 0xfd, 0x5d, 0x7f, 0x84, 0xc4, 0xb3, 0x42, 0x0e, 0x97, 0x69, 0x2a, 0x0f, 0x5f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xb1, 0xfe, 0xc3, 0x22, 0xf4, 0x01, 0x00, 0x00,
}
