// Code generated by protoc-gen-go. DO NOT EDIT.
// source: permission/pb/function.proto

package xbasissvc_external_permission

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	dto "konekko.me/xbasis/commons/dto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ModifySettingsRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	FunctionId           string   `protobuf:"bytes,2,opt,name=functionId,proto3" json:"functionId,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Api                  string   `protobuf:"bytes,4,opt,name=api,proto3" json:"api,omitempty"`
	ValTokenTimes        int64    `protobuf:"varint,5,opt,name=valTokenTimes,proto3" json:"valTokenTimes,omitempty"`
	NoGrants             []string `protobuf:"bytes,6,rep,name=noGrants,proto3" json:"noGrants,omitempty"`
	AuthTypes            []int64  `protobuf:"varint,7,rep,packed,name=authTypes,proto3" json:"authTypes,omitempty"`
	Share                bool     `protobuf:"varint,8,opt,name=share,proto3" json:"share,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifySettingsRequest) Reset()         { *m = ModifySettingsRequest{} }
func (m *ModifySettingsRequest) String() string { return proto.CompactTextString(m) }
func (*ModifySettingsRequest) ProtoMessage()    {}
func (*ModifySettingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ec5ed375fcb9fb2, []int{0}
}

func (m *ModifySettingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifySettingsRequest.Unmarshal(m, b)
}
func (m *ModifySettingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifySettingsRequest.Marshal(b, m, deterministic)
}
func (m *ModifySettingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifySettingsRequest.Merge(m, src)
}
func (m *ModifySettingsRequest) XXX_Size() int {
	return xxx_messageInfo_ModifySettingsRequest.Size(m)
}
func (m *ModifySettingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifySettingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifySettingsRequest proto.InternalMessageInfo

func (m *ModifySettingsRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *ModifySettingsRequest) GetFunctionId() string {
	if m != nil {
		return m.FunctionId
	}
	return ""
}

func (m *ModifySettingsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ModifySettingsRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ModifySettingsRequest) GetValTokenTimes() int64 {
	if m != nil {
		return m.ValTokenTimes
	}
	return 0
}

func (m *ModifySettingsRequest) GetNoGrants() []string {
	if m != nil {
		return m.NoGrants
	}
	return nil
}

func (m *ModifySettingsRequest) GetAuthTypes() []int64 {
	if m != nil {
		return m.AuthTypes
	}
	return nil
}

func (m *ModifySettingsRequest) GetShare() bool {
	if m != nil {
		return m.Share
	}
	return false
}

type FunctionSearchRequest struct {
	Page                 int64    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	AppId                string   `protobuf:"bytes,3,opt,name=appId,proto3" json:"appId,omitempty"`
	Keyword              string   `protobuf:"bytes,4,opt,name=keyword,proto3" json:"keyword,omitempty"`
	FilterRoleId         string   `protobuf:"bytes,5,opt,name=filterRoleId,proto3" json:"filterRoleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FunctionSearchRequest) Reset()         { *m = FunctionSearchRequest{} }
func (m *FunctionSearchRequest) String() string { return proto.CompactTextString(m) }
func (*FunctionSearchRequest) ProtoMessage()    {}
func (*FunctionSearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ec5ed375fcb9fb2, []int{1}
}

func (m *FunctionSearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionSearchRequest.Unmarshal(m, b)
}
func (m *FunctionSearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionSearchRequest.Marshal(b, m, deterministic)
}
func (m *FunctionSearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionSearchRequest.Merge(m, src)
}
func (m *FunctionSearchRequest) XXX_Size() int {
	return xxx_messageInfo_FunctionSearchRequest.Size(m)
}
func (m *FunctionSearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionSearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionSearchRequest proto.InternalMessageInfo

func (m *FunctionSearchRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *FunctionSearchRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FunctionSearchRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *FunctionSearchRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *FunctionSearchRequest) GetFilterRoleId() string {
	if m != nil {
		return m.FilterRoleId
	}
	return ""
}

type FunctionSearchResponse struct {
	State                *dto.State            `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Data                 []*SimpleFunctionItem `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *FunctionSearchResponse) Reset()         { *m = FunctionSearchResponse{} }
func (m *FunctionSearchResponse) String() string { return proto.CompactTextString(m) }
func (*FunctionSearchResponse) ProtoMessage()    {}
func (*FunctionSearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ec5ed375fcb9fb2, []int{2}
}

func (m *FunctionSearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionSearchResponse.Unmarshal(m, b)
}
func (m *FunctionSearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionSearchResponse.Marshal(b, m, deterministic)
}
func (m *FunctionSearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionSearchResponse.Merge(m, src)
}
func (m *FunctionSearchResponse) XXX_Size() int {
	return xxx_messageInfo_FunctionSearchResponse.Size(m)
}
func (m *FunctionSearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionSearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionSearchResponse proto.InternalMessageInfo

func (m *FunctionSearchResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *FunctionSearchResponse) GetData() []*SimpleFunctionItem {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetFunctionItemsRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId                string   `protobuf:"bytes,2,opt,name=appId,proto3" json:"appId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFunctionItemsRequest) Reset()         { *m = GetFunctionItemsRequest{} }
func (m *GetFunctionItemsRequest) String() string { return proto.CompactTextString(m) }
func (*GetFunctionItemsRequest) ProtoMessage()    {}
func (*GetFunctionItemsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ec5ed375fcb9fb2, []int{3}
}

func (m *GetFunctionItemsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFunctionItemsRequest.Unmarshal(m, b)
}
func (m *GetFunctionItemsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFunctionItemsRequest.Marshal(b, m, deterministic)
}
func (m *GetFunctionItemsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFunctionItemsRequest.Merge(m, src)
}
func (m *GetFunctionItemsRequest) XXX_Size() int {
	return xxx_messageInfo_GetFunctionItemsRequest.Size(m)
}
func (m *GetFunctionItemsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFunctionItemsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFunctionItemsRequest proto.InternalMessageInfo

func (m *GetFunctionItemsRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetFunctionItemsRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

type GetFunctionItemsResponse struct {
	State                *dto.State            `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Data                 []*SimpleFunctionItem `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetFunctionItemsResponse) Reset()         { *m = GetFunctionItemsResponse{} }
func (m *GetFunctionItemsResponse) String() string { return proto.CompactTextString(m) }
func (*GetFunctionItemsResponse) ProtoMessage()    {}
func (*GetFunctionItemsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ec5ed375fcb9fb2, []int{4}
}

func (m *GetFunctionItemsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFunctionItemsResponse.Unmarshal(m, b)
}
func (m *GetFunctionItemsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFunctionItemsResponse.Marshal(b, m, deterministic)
}
func (m *GetFunctionItemsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFunctionItemsResponse.Merge(m, src)
}
func (m *GetFunctionItemsResponse) XXX_Size() int {
	return xxx_messageInfo_GetFunctionItemsResponse.Size(m)
}
func (m *GetFunctionItemsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFunctionItemsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFunctionItemsResponse proto.InternalMessageInfo

func (m *GetFunctionItemsResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *GetFunctionItemsResponse) GetData() []*SimpleFunctionItem {
	if m != nil {
		return m.Data
	}
	return nil
}

type SimpleFunctionItem struct {
	Function             bool     `protobuf:"varint,1,opt,name=function,proto3" json:"function,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	AppId                string   `protobuf:"bytes,4,opt,name=appId,proto3" json:"appId,omitempty"`
	CreateAt             int64    `protobuf:"varint,5,opt,name=createAt,proto3" json:"createAt,omitempty"`
	Path                 string   `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleFunctionItem) Reset()         { *m = SimpleFunctionItem{} }
func (m *SimpleFunctionItem) String() string { return proto.CompactTextString(m) }
func (*SimpleFunctionItem) ProtoMessage()    {}
func (*SimpleFunctionItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ec5ed375fcb9fb2, []int{5}
}

func (m *SimpleFunctionItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleFunctionItem.Unmarshal(m, b)
}
func (m *SimpleFunctionItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleFunctionItem.Marshal(b, m, deterministic)
}
func (m *SimpleFunctionItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleFunctionItem.Merge(m, src)
}
func (m *SimpleFunctionItem) XXX_Size() int {
	return xxx_messageInfo_SimpleFunctionItem.Size(m)
}
func (m *SimpleFunctionItem) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleFunctionItem.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleFunctionItem proto.InternalMessageInfo

func (m *SimpleFunctionItem) GetFunction() bool {
	if m != nil {
		return m.Function
	}
	return false
}

func (m *SimpleFunctionItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SimpleFunctionItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SimpleFunctionItem) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *SimpleFunctionItem) GetCreateAt() int64 {
	if m != nil {
		return m.CreateAt
	}
	return 0
}

func (m *SimpleFunctionItem) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type GetFunctionItemRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId                string   `protobuf:"bytes,2,opt,name=appId,proto3" json:"appId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFunctionItemRequest) Reset()         { *m = GetFunctionItemRequest{} }
func (m *GetFunctionItemRequest) String() string { return proto.CompactTextString(m) }
func (*GetFunctionItemRequest) ProtoMessage()    {}
func (*GetFunctionItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ec5ed375fcb9fb2, []int{6}
}

func (m *GetFunctionItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFunctionItemRequest.Unmarshal(m, b)
}
func (m *GetFunctionItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFunctionItemRequest.Marshal(b, m, deterministic)
}
func (m *GetFunctionItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFunctionItemRequest.Merge(m, src)
}
func (m *GetFunctionItemRequest) XXX_Size() int {
	return xxx_messageInfo_GetFunctionItemRequest.Size(m)
}
func (m *GetFunctionItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFunctionItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFunctionItemRequest proto.InternalMessageInfo

func (m *GetFunctionItemRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetFunctionItemRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

type GetFunctionItemResponse struct {
	State                *dto.State          `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Data                 *FunctionItemDetail `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetFunctionItemResponse) Reset()         { *m = GetFunctionItemResponse{} }
func (m *GetFunctionItemResponse) String() string { return proto.CompactTextString(m) }
func (*GetFunctionItemResponse) ProtoMessage()    {}
func (*GetFunctionItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ec5ed375fcb9fb2, []int{7}
}

func (m *GetFunctionItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFunctionItemResponse.Unmarshal(m, b)
}
func (m *GetFunctionItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFunctionItemResponse.Marshal(b, m, deterministic)
}
func (m *GetFunctionItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFunctionItemResponse.Merge(m, src)
}
func (m *GetFunctionItemResponse) XXX_Size() int {
	return xxx_messageInfo_GetFunctionItemResponse.Size(m)
}
func (m *GetFunctionItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFunctionItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFunctionItemResponse proto.InternalMessageInfo

func (m *GetFunctionItemResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *GetFunctionItemResponse) GetData() *FunctionItemDetail {
	if m != nil {
		return m.Data
	}
	return nil
}

type FunctionItemDetail struct {
	Name                 string                      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Api                  string                      `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`
	CreateAt             int64                       `protobuf:"varint,3,opt,name=createAt,proto3" json:"createAt,omitempty"`
	Roles                []*FunctionBindRole         `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	AuthTypes            []*FunctionAuthTypes        `protobuf:"bytes,5,rep,name=authTypes,proto3" json:"authTypes,omitempty"`
	Platforms            []*FunctionNoGrantPlatforms `protobuf:"bytes,6,rep,name=platforms,proto3" json:"platforms,omitempty"`
	Share                bool                        `protobuf:"varint,7,opt,name=share,proto3" json:"share,omitempty"`
	ValTokenTimes        int64                       `protobuf:"varint,8,opt,name=valTokenTimes,proto3" json:"valTokenTimes,omitempty"`
	Id                   string                      `protobuf:"bytes,9,opt,name=id,proto3" json:"id,omitempty"`
	TodayVisit           int64                       `protobuf:"varint,10,opt,name=todayVisit,proto3" json:"todayVisit,omitempty"`
	TodayUserVisit       int64                       `protobuf:"varint,11,opt,name=todayUserVisit,proto3" json:"todayUserVisit,omitempty"`
	TotalUserVisit       int64                       `protobuf:"varint,12,opt,name=totalUserVisit,proto3" json:"totalUserVisit,omitempty"`
	TotalVisit           int64                       `protobuf:"varint,13,opt,name=totalVisit,proto3" json:"totalVisit,omitempty"`
	ValCode              bool                        `protobuf:"varint,14,opt,name=valCode,proto3" json:"valCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *FunctionItemDetail) Reset()         { *m = FunctionItemDetail{} }
func (m *FunctionItemDetail) String() string { return proto.CompactTextString(m) }
func (*FunctionItemDetail) ProtoMessage()    {}
func (*FunctionItemDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ec5ed375fcb9fb2, []int{8}
}

func (m *FunctionItemDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionItemDetail.Unmarshal(m, b)
}
func (m *FunctionItemDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionItemDetail.Marshal(b, m, deterministic)
}
func (m *FunctionItemDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionItemDetail.Merge(m, src)
}
func (m *FunctionItemDetail) XXX_Size() int {
	return xxx_messageInfo_FunctionItemDetail.Size(m)
}
func (m *FunctionItemDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionItemDetail.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionItemDetail proto.InternalMessageInfo

func (m *FunctionItemDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FunctionItemDetail) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FunctionItemDetail) GetCreateAt() int64 {
	if m != nil {
		return m.CreateAt
	}
	return 0
}

func (m *FunctionItemDetail) GetRoles() []*FunctionBindRole {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *FunctionItemDetail) GetAuthTypes() []*FunctionAuthTypes {
	if m != nil {
		return m.AuthTypes
	}
	return nil
}

func (m *FunctionItemDetail) GetPlatforms() []*FunctionNoGrantPlatforms {
	if m != nil {
		return m.Platforms
	}
	return nil
}

func (m *FunctionItemDetail) GetShare() bool {
	if m != nil {
		return m.Share
	}
	return false
}

func (m *FunctionItemDetail) GetValTokenTimes() int64 {
	if m != nil {
		return m.ValTokenTimes
	}
	return 0
}

func (m *FunctionItemDetail) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FunctionItemDetail) GetTodayVisit() int64 {
	if m != nil {
		return m.TodayVisit
	}
	return 0
}

func (m *FunctionItemDetail) GetTodayUserVisit() int64 {
	if m != nil {
		return m.TodayUserVisit
	}
	return 0
}

func (m *FunctionItemDetail) GetTotalUserVisit() int64 {
	if m != nil {
		return m.TotalUserVisit
	}
	return 0
}

func (m *FunctionItemDetail) GetTotalVisit() int64 {
	if m != nil {
		return m.TotalVisit
	}
	return 0
}

func (m *FunctionItemDetail) GetValCode() bool {
	if m != nil {
		return m.ValCode
	}
	return false
}

type FunctionBindRole struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FunctionBindRole) Reset()         { *m = FunctionBindRole{} }
func (m *FunctionBindRole) String() string { return proto.CompactTextString(m) }
func (*FunctionBindRole) ProtoMessage()    {}
func (*FunctionBindRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ec5ed375fcb9fb2, []int{9}
}

func (m *FunctionBindRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionBindRole.Unmarshal(m, b)
}
func (m *FunctionBindRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionBindRole.Marshal(b, m, deterministic)
}
func (m *FunctionBindRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionBindRole.Merge(m, src)
}
func (m *FunctionBindRole) XXX_Size() int {
	return xxx_messageInfo_FunctionBindRole.Size(m)
}
func (m *FunctionBindRole) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionBindRole.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionBindRole proto.InternalMessageInfo

func (m *FunctionBindRole) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FunctionBindRole) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type FunctionAuthTypes struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 int64    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Enabled              bool     `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FunctionAuthTypes) Reset()         { *m = FunctionAuthTypes{} }
func (m *FunctionAuthTypes) String() string { return proto.CompactTextString(m) }
func (*FunctionAuthTypes) ProtoMessage()    {}
func (*FunctionAuthTypes) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ec5ed375fcb9fb2, []int{10}
}

func (m *FunctionAuthTypes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionAuthTypes.Unmarshal(m, b)
}
func (m *FunctionAuthTypes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionAuthTypes.Marshal(b, m, deterministic)
}
func (m *FunctionAuthTypes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionAuthTypes.Merge(m, src)
}
func (m *FunctionAuthTypes) XXX_Size() int {
	return xxx_messageInfo_FunctionAuthTypes.Size(m)
}
func (m *FunctionAuthTypes) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionAuthTypes.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionAuthTypes proto.InternalMessageInfo

func (m *FunctionAuthTypes) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FunctionAuthTypes) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *FunctionAuthTypes) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type FunctionNoGrantPlatforms struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 int64    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Enabled              bool     `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FunctionNoGrantPlatforms) Reset()         { *m = FunctionNoGrantPlatforms{} }
func (m *FunctionNoGrantPlatforms) String() string { return proto.CompactTextString(m) }
func (*FunctionNoGrantPlatforms) ProtoMessage()    {}
func (*FunctionNoGrantPlatforms) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ec5ed375fcb9fb2, []int{11}
}

func (m *FunctionNoGrantPlatforms) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionNoGrantPlatforms.Unmarshal(m, b)
}
func (m *FunctionNoGrantPlatforms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionNoGrantPlatforms.Marshal(b, m, deterministic)
}
func (m *FunctionNoGrantPlatforms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionNoGrantPlatforms.Merge(m, src)
}
func (m *FunctionNoGrantPlatforms) XXX_Size() int {
	return xxx_messageInfo_FunctionNoGrantPlatforms.Size(m)
}
func (m *FunctionNoGrantPlatforms) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionNoGrantPlatforms.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionNoGrantPlatforms proto.InternalMessageInfo

func (m *FunctionNoGrantPlatforms) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FunctionNoGrantPlatforms) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *FunctionNoGrantPlatforms) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type FunctionRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Api                  string   `protobuf:"bytes,3,opt,name=api,proto3" json:"api,omitempty"`
	Type                 int64    `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	BindGroupId          string   `protobuf:"bytes,5,opt,name=bindGroupId,proto3" json:"bindGroupId,omitempty"`
	AuthTypes            []int64  `protobuf:"varint,6,rep,packed,name=authTypes,proto3" json:"authTypes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FunctionRequest) Reset()         { *m = FunctionRequest{} }
func (m *FunctionRequest) String() string { return proto.CompactTextString(m) }
func (*FunctionRequest) ProtoMessage()    {}
func (*FunctionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ec5ed375fcb9fb2, []int{12}
}

func (m *FunctionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionRequest.Unmarshal(m, b)
}
func (m *FunctionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionRequest.Marshal(b, m, deterministic)
}
func (m *FunctionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionRequest.Merge(m, src)
}
func (m *FunctionRequest) XXX_Size() int {
	return xxx_messageInfo_FunctionRequest.Size(m)
}
func (m *FunctionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionRequest proto.InternalMessageInfo

func (m *FunctionRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *FunctionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FunctionRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FunctionRequest) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *FunctionRequest) GetBindGroupId() string {
	if m != nil {
		return m.BindGroupId
	}
	return ""
}

func (m *FunctionRequest) GetAuthTypes() []int64 {
	if m != nil {
		return m.AuthTypes
	}
	return nil
}

type FunctionGroupRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BindGroupId          string   `protobuf:"bytes,3,opt,name=bindGroupId,proto3" json:"bindGroupId,omitempty"`
	Type                 int64    `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FunctionGroupRequest) Reset()         { *m = FunctionGroupRequest{} }
func (m *FunctionGroupRequest) String() string { return proto.CompactTextString(m) }
func (*FunctionGroupRequest) ProtoMessage()    {}
func (*FunctionGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ec5ed375fcb9fb2, []int{13}
}

func (m *FunctionGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionGroupRequest.Unmarshal(m, b)
}
func (m *FunctionGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionGroupRequest.Marshal(b, m, deterministic)
}
func (m *FunctionGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionGroupRequest.Merge(m, src)
}
func (m *FunctionGroupRequest) XXX_Size() int {
	return xxx_messageInfo_FunctionGroupRequest.Size(m)
}
func (m *FunctionGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionGroupRequest proto.InternalMessageInfo

func (m *FunctionGroupRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *FunctionGroupRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FunctionGroupRequest) GetBindGroupId() string {
	if m != nil {
		return m.BindGroupId
	}
	return ""
}

func (m *FunctionGroupRequest) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func init() {
	proto.RegisterType((*ModifySettingsRequest)(nil), "xbasissvc.external.permission.ModifySettingsRequest")
	proto.RegisterType((*FunctionSearchRequest)(nil), "xbasissvc.external.permission.FunctionSearchRequest")
	proto.RegisterType((*FunctionSearchResponse)(nil), "xbasissvc.external.permission.FunctionSearchResponse")
	proto.RegisterType((*GetFunctionItemsRequest)(nil), "xbasissvc.external.permission.GetFunctionItemsRequest")
	proto.RegisterType((*GetFunctionItemsResponse)(nil), "xbasissvc.external.permission.GetFunctionItemsResponse")
	proto.RegisterType((*SimpleFunctionItem)(nil), "xbasissvc.external.permission.SimpleFunctionItem")
	proto.RegisterType((*GetFunctionItemRequest)(nil), "xbasissvc.external.permission.GetFunctionItemRequest")
	proto.RegisterType((*GetFunctionItemResponse)(nil), "xbasissvc.external.permission.GetFunctionItemResponse")
	proto.RegisterType((*FunctionItemDetail)(nil), "xbasissvc.external.permission.FunctionItemDetail")
	proto.RegisterType((*FunctionBindRole)(nil), "xbasissvc.external.permission.FunctionBindRole")
	proto.RegisterType((*FunctionAuthTypes)(nil), "xbasissvc.external.permission.FunctionAuthTypes")
	proto.RegisterType((*FunctionNoGrantPlatforms)(nil), "xbasissvc.external.permission.FunctionNoGrantPlatforms")
	proto.RegisterType((*FunctionRequest)(nil), "xbasissvc.external.permission.FunctionRequest")
	proto.RegisterType((*FunctionGroupRequest)(nil), "xbasissvc.external.permission.FunctionGroupRequest")
}

func init() { proto.RegisterFile("permission/pb/function.proto", fileDescriptor_7ec5ed375fcb9fb2) }

var fileDescriptor_7ec5ed375fcb9fb2 = []byte{
	// 948 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x57, 0x4f, 0x6f, 0xe3, 0x44,
	0x14, 0x97, 0x63, 0x37, 0x75, 0x5e, 0x76, 0x4b, 0x19, 0x6d, 0x17, 0x13, 0x2d, 0xab, 0xc8, 0x42,
	0x28, 0x12, 0x92, 0x03, 0x5d, 0xb6, 0x7b, 0x03, 0x15, 0x58, 0xaa, 0x1e, 0x76, 0x05, 0xd3, 0x96,
	0x0b, 0x2b, 0xa4, 0x49, 0x3c, 0xdd, 0x8e, 0x62, 0x7b, 0x8c, 0x67, 0x12, 0x36, 0x5c, 0x91, 0x38,
	0x71, 0xe0, 0xcf, 0x8d, 0x1b, 0x5f, 0x83, 0x6f, 0xc4, 0xb7, 0x40, 0x9e, 0xf1, 0xd8, 0x8e, 0x9d,
	0x76, 0x13, 0xa9, 0x2b, 0x6e, 0xf3, 0xde, 0xbc, 0x3f, 0xbf, 0xf7, 0x9b, 0x37, 0x6f, 0x6c, 0x78,
	0x90, 0xd2, 0x2c, 0x66, 0x42, 0x30, 0x9e, 0x8c, 0xd3, 0xc9, 0xf8, 0x72, 0x9e, 0x4c, 0x25, 0xe3,
	0x49, 0x90, 0x66, 0x5c, 0x72, 0xf4, 0xde, 0xab, 0x09, 0x11, 0x4c, 0x88, 0xc5, 0x34, 0xa0, 0xaf,
	0x24, 0xcd, 0x12, 0x12, 0x05, 0x95, 0xc3, 0xe0, 0xc3, 0x19, 0x4f, 0xe8, 0x6c, 0xc6, 0x83, 0x98,
	0x8e, 0xb5, 0xe5, 0x78, 0xca, 0xe3, 0x98, 0x27, 0x62, 0x1c, 0x4a, 0x6e, 0xd6, 0x3a, 0x96, 0xff,
	0xaf, 0x05, 0x07, 0xcf, 0x78, 0xc8, 0x2e, 0x97, 0x67, 0x54, 0x4a, 0x96, 0xbc, 0x14, 0x98, 0xfe,
	0x30, 0xa7, 0x42, 0xa2, 0x7b, 0xb0, 0x43, 0xd2, 0xf4, 0x34, 0xf4, 0xac, 0xa1, 0x35, 0xea, 0x61,
	0x2d, 0xa0, 0x87, 0x00, 0x06, 0xcd, 0x69, 0xe8, 0x75, 0xd4, 0x56, 0x4d, 0x83, 0x10, 0x38, 0x09,
	0x89, 0xa9, 0x67, 0xab, 0x1d, 0xb5, 0x46, 0xfb, 0x60, 0x93, 0x94, 0x79, 0x8e, 0x52, 0xe5, 0x4b,
	0xf4, 0x3e, 0xdc, 0x5d, 0x90, 0xe8, 0x9c, 0xcf, 0x68, 0x72, 0xce, 0x62, 0x2a, 0xbc, 0x9d, 0xa1,
	0x35, 0xb2, 0xf1, 0xaa, 0x12, 0x0d, 0xc0, 0x4d, 0xf8, 0x49, 0x46, 0x12, 0x29, 0xbc, 0xee, 0xd0,
	0x1e, 0xf5, 0x70, 0x29, 0xa3, 0x07, 0xd0, 0x23, 0x73, 0x79, 0x75, 0xbe, 0x4c, 0xa9, 0xf0, 0x76,
	0x87, 0xf6, 0xc8, 0xc6, 0x95, 0x22, 0xc7, 0x2e, 0xae, 0x48, 0x46, 0x3d, 0x77, 0x68, 0x8d, 0x5c,
	0xac, 0x05, 0xff, 0x4f, 0x0b, 0x0e, 0xbe, 0x2a, 0xa0, 0x9e, 0x51, 0x92, 0x4d, 0xaf, 0x4c, 0xad,
	0x08, 0x9c, 0x94, 0xbc, 0xa4, 0xaa, 0x54, 0x1b, 0xab, 0x75, 0xae, 0x13, 0xec, 0x27, 0xaa, 0x6a,
	0xb4, 0xb1, 0x5a, 0x57, 0x9c, 0xd8, 0x75, 0x4e, 0x3c, 0xd8, 0x9d, 0xd1, 0xe5, 0x8f, 0x3c, 0x0b,
	0x8b, 0x1a, 0x8d, 0x88, 0x7c, 0xb8, 0x73, 0xc9, 0x22, 0x49, 0x33, 0xcc, 0x23, 0x7a, 0x1a, 0xaa,
	0x32, 0x7b, 0x78, 0x45, 0xe7, 0xff, 0x66, 0xc1, 0xfd, 0x26, 0x2a, 0x91, 0xf2, 0x44, 0x50, 0x34,
	0x86, 0x1d, 0x21, 0x89, 0xd4, 0xb8, 0xfa, 0x87, 0xef, 0x06, 0xfa, 0x38, 0x03, 0x73, 0x84, 0xa1,
	0xe4, 0xc1, 0x59, 0x6e, 0x80, 0xb5, 0x1d, 0x7a, 0x0a, 0x4e, 0x48, 0x24, 0xf1, 0x3a, 0x43, 0x7b,
	0xd4, 0x3f, 0xfc, 0x38, 0xb8, 0xb1, 0x51, 0x82, 0x33, 0x16, 0xa7, 0x11, 0x35, 0xb9, 0x4f, 0x25,
	0x8d, 0xb1, 0x72, 0xf7, 0x3f, 0x83, 0x77, 0x4e, 0xa8, 0xac, 0x6f, 0x94, 0x5d, 0xb1, 0x07, 0x1d,
	0x66, 0x5a, 0xa2, 0xc3, 0xc2, 0x8a, 0x91, 0x4e, 0x8d, 0x11, 0xff, 0x0f, 0x0b, 0xbc, 0x76, 0x84,
	0xff, 0xb9, 0xaa, 0xbf, 0x2c, 0x40, 0xed, 0xcd, 0xbc, 0xcb, 0x4c, 0xff, 0x2a, 0x44, 0x2e, 0x2e,
	0xe5, 0xb2, 0x9b, 0x3b, 0xb5, 0x6e, 0xd6, 0x0c, 0xd8, 0x6d, 0x06, 0x9c, 0x7a, 0x4f, 0x0c, 0xc0,
	0x9d, 0x66, 0x94, 0x48, 0x7a, 0x2c, 0x8b, 0xe6, 0x2e, 0x65, 0xdd, 0x6d, 0xf2, 0xca, 0xeb, 0xea,
	0xa8, 0xf9, 0xda, 0xff, 0x14, 0xee, 0x37, 0x08, 0xdb, 0x8e, 0xf1, 0xdf, 0xad, 0xd6, 0x99, 0xdd,
	0x06, 0xe1, 0xd6, 0x06, 0x84, 0xd7, 0x73, 0x7e, 0x49, 0x25, 0x61, 0x51, 0x41, 0xf8, 0x3f, 0x0e,
	0xa0, 0xf6, 0x66, 0x49, 0xaa, 0xd5, 0x1e, 0x11, 0x9d, 0x6a, 0x44, 0xd4, 0x09, 0xb4, 0x1b, 0x04,
	0x3e, 0x85, 0x9d, 0x8c, 0x47, 0x54, 0x78, 0x8e, 0xea, 0x88, 0xf1, 0x86, 0x00, 0x3f, 0x67, 0x49,
	0x98, 0x5f, 0x3a, 0xac, 0xbd, 0xd1, 0xf3, 0xfa, 0x0c, 0xd9, 0x51, 0xa1, 0x3e, 0xda, 0x30, 0xd4,
	0xb1, 0xf1, 0xab, 0x4f, 0x9d, 0x0b, 0xe8, 0xa5, 0x11, 0x91, 0x97, 0x3c, 0x8b, 0xf5, 0xc0, 0xea,
	0x1f, 0x3e, 0xd9, 0x30, 0xde, 0x73, 0x3d, 0xd7, 0xbe, 0x36, 0xee, 0xb8, 0x8a, 0x54, 0x0d, 0xb3,
	0xdd, 0xda, 0x30, 0x6b, 0x8f, 0x50, 0x77, 0xdd, 0x08, 0xd5, 0xcd, 0xd3, 0x2b, 0x9b, 0xe7, 0x21,
	0x80, 0xe4, 0x21, 0x59, 0x7e, 0xcb, 0x04, 0x93, 0x1e, 0x28, 0x97, 0x9a, 0x06, 0x7d, 0x00, 0x7b,
	0x4a, 0xba, 0x10, 0x34, 0xd3, 0x36, 0x7d, 0x65, 0xd3, 0xd0, 0x6a, 0x3b, 0x49, 0xa2, 0xca, 0xee,
	0x8e, 0xb1, 0xab, 0x6b, 0x75, 0x3e, 0x49, 0x22, 0x6d, 0x73, 0xd7, 0xe4, 0x33, 0x9a, 0x7c, 0x74,
	0x2e, 0x48, 0xf4, 0x05, 0x0f, 0xa9, 0xb7, 0xa7, 0xaa, 0x33, 0xa2, 0x7f, 0x04, 0xfb, 0xcd, 0x73,
	0x5b, 0xdb, 0x39, 0xba, 0xc2, 0x8e, 0xa9, 0xd0, 0xbf, 0x80, 0xb7, 0x5b, 0x87, 0xb4, 0xd6, 0x11,
	0x81, 0x23, 0x97, 0x69, 0x39, 0xdf, 0xf3, 0x75, 0x0e, 0x87, 0x26, 0x64, 0x12, 0x51, 0x7d, 0xc1,
	0x5d, 0x6c, 0x44, 0xff, 0x05, 0x78, 0xd7, 0x9d, 0xd5, 0x2d, 0x44, 0xff, 0xdb, 0x82, 0xb7, 0x4c,
	0xf8, 0x9b, 0xdf, 0xdf, 0x75, 0x13, 0xa9, 0xb8, 0x3c, 0x76, 0x75, 0x79, 0x4c, 0x76, 0xa7, 0x96,
	0x7d, 0x08, 0xfd, 0x09, 0x4b, 0xc2, 0x93, 0x8c, 0xcf, 0xd3, 0xf2, 0x29, 0xaa, 0xab, 0x56, 0xdf,
	0xd4, 0x6e, 0xe3, 0x4d, 0xf5, 0x17, 0x70, 0xcf, 0x40, 0x54, 0x0e, 0xdb, 0xe3, 0x6c, 0x20, 0xb0,
	0xdb, 0x08, 0xd6, 0xe0, 0x3e, 0xfc, 0xd5, 0x05, 0xd7, 0x24, 0x46, 0xdf, 0x80, 0x7d, 0x1c, 0x86,
	0x28, 0xd8, 0xf0, 0x5a, 0x15, 0x18, 0x07, 0x83, 0xeb, 0x46, 0xde, 0x5c, 0xa0, 0x73, 0xe8, 0x62,
	0xaa, 0xf0, 0xdd, 0x66, 0x54, 0x0c, 0xce, 0x33, 0xbe, 0xb8, 0xdd, 0x98, 0xdf, 0x81, 0x7b, 0x1c,
	0x6a, 0xae, 0xd0, 0xa3, 0x0d, 0xe3, 0xd6, 0x8f, 0xea, 0xc6, 0xe0, 0x2f, 0xa0, 0x97, 0x03, 0x7e,
	0x43, 0xd1, 0xbf, 0x87, 0xbe, 0x26, 0xf9, 0x0d, 0xc5, 0xff, 0xd9, 0x82, 0xfd, 0xe6, 0x07, 0x07,
	0x3a, 0x7a, 0x4d, 0x96, 0x6b, 0xbe, 0x71, 0x06, 0x4f, 0xb6, 0xf6, 0x2b, 0x1e, 0xda, 0x5f, 0x2c,
	0x38, 0x68, 0x6c, 0x16, 0x6f, 0xde, 0xe3, 0xed, 0x42, 0x1a, 0x24, 0x47, 0xdb, 0xba, 0x15, 0x40,
	0xe6, 0xd0, 0xd5, 0x9f, 0x92, 0xe8, 0x93, 0x0d, 0x99, 0x5e, 0xf9, 0x1e, 0x1e, 0x3c, 0xde, 0xd2,
	0xab, 0x48, 0x3b, 0x81, 0xbd, 0xd5, 0x7f, 0x89, 0xd7, 0xa6, 0x5f, 0xfb, 0xeb, 0x71, 0xd3, 0x49,
	0x4f, 0xba, 0xea, 0xbf, 0xe5, 0xd1, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xea, 0x55, 0x59, 0x9c,
	0x23, 0x0d, 0x00, 0x00,
}
