// Code generated by protoc-gen-go. DO NOT EDIT.
// source: permission/pb/structure.proto

package gs_service_permission

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	dto "konekko.me/gosion/commons/dto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetInfoRequest struct {
	StructureId          string   `protobuf:"bytes,1,opt,name=structureId,proto3" json:"structureId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoRequest) Reset()         { *m = GetInfoRequest{} }
func (m *GetInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetInfoRequest) ProtoMessage()    {}
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f325e6597bcc547a, []int{0}
}

func (m *GetInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoRequest.Unmarshal(m, b)
}
func (m *GetInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoRequest.Merge(m, src)
}
func (m *GetInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetInfoRequest.Size(m)
}
func (m *GetInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoRequest proto.InternalMessageInfo

func (m *GetInfoRequest) GetStructureId() string {
	if m != nil {
		return m.StructureId
	}
	return ""
}

type GetInfoResponse struct {
	State                *dto.State       `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Data                 *SimpleStructure `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetInfoResponse) Reset()         { *m = GetInfoResponse{} }
func (m *GetInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetInfoResponse) ProtoMessage()    {}
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f325e6597bcc547a, []int{1}
}

func (m *GetInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoResponse.Unmarshal(m, b)
}
func (m *GetInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoResponse.Merge(m, src)
}
func (m *GetInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetInfoResponse.Size(m)
}
func (m *GetInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoResponse proto.InternalMessageInfo

func (m *GetInfoResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *GetInfoResponse) GetData() *SimpleStructure {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AppId                string   `protobuf:"bytes,2,opt,name=appId,proto3" json:"appId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f325e6597bcc547a, []int{2}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

type EnabledRequest struct {
	StructureId          string   `protobuf:"bytes,1,opt,name=structureId,proto3" json:"structureId,omitempty"`
	Opening              bool     `protobuf:"varint,2,opt,name=opening,proto3" json:"opening,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnabledRequest) Reset()         { *m = EnabledRequest{} }
func (m *EnabledRequest) String() string { return proto.CompactTextString(m) }
func (*EnabledRequest) ProtoMessage()    {}
func (*EnabledRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f325e6597bcc547a, []int{3}
}

func (m *EnabledRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnabledRequest.Unmarshal(m, b)
}
func (m *EnabledRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnabledRequest.Marshal(b, m, deterministic)
}
func (m *EnabledRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnabledRequest.Merge(m, src)
}
func (m *EnabledRequest) XXX_Size() int {
	return xxx_messageInfo_EnabledRequest.Size(m)
}
func (m *EnabledRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnabledRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnabledRequest proto.InternalMessageInfo

func (m *EnabledRequest) GetStructureId() string {
	if m != nil {
		return m.StructureId
	}
	return ""
}

func (m *EnabledRequest) GetOpening() bool {
	if m != nil {
		return m.Opening
	}
	return false
}

type GetListRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	User                 bool     `protobuf:"varint,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListRequest) Reset()         { *m = GetListRequest{} }
func (m *GetListRequest) String() string { return proto.CompactTextString(m) }
func (*GetListRequest) ProtoMessage()    {}
func (*GetListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f325e6597bcc547a, []int{4}
}

func (m *GetListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListRequest.Unmarshal(m, b)
}
func (m *GetListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListRequest.Marshal(b, m, deterministic)
}
func (m *GetListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListRequest.Merge(m, src)
}
func (m *GetListRequest) XXX_Size() int {
	return xxx_messageInfo_GetListRequest.Size(m)
}
func (m *GetListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetListRequest proto.InternalMessageInfo

func (m *GetListRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *GetListRequest) GetUser() bool {
	if m != nil {
		return m.User
	}
	return false
}

type GetListResponse struct {
	State                *dto.State         `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Data                 []*SimpleStructure `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetListResponse) Reset()         { *m = GetListResponse{} }
func (m *GetListResponse) String() string { return proto.CompactTextString(m) }
func (*GetListResponse) ProtoMessage()    {}
func (*GetListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f325e6597bcc547a, []int{5}
}

func (m *GetListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListResponse.Unmarshal(m, b)
}
func (m *GetListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListResponse.Marshal(b, m, deterministic)
}
func (m *GetListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListResponse.Merge(m, src)
}
func (m *GetListResponse) XXX_Size() int {
	return xxx_messageInfo_GetListResponse.Size(m)
}
func (m *GetListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetListResponse proto.InternalMessageInfo

func (m *GetListResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *GetListResponse) GetData() []*SimpleStructure {
	if m != nil {
		return m.Data
	}
	return nil
}

type SimpleStructure struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreateAt             int64    `protobuf:"varint,2,opt,name=createAt,proto3" json:"createAt,omitempty"`
	Opening              bool     `protobuf:"varint,3,opt,name=opening,proto3" json:"opening,omitempty"`
	Id                   string   `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	FuncS                bool     `protobuf:"varint,5,opt,name=funcS,proto3" json:"funcS,omitempty"`
	LastUpdateAt         int64    `protobuf:"varint,6,opt,name=lastUpdateAt,proto3" json:"lastUpdateAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleStructure) Reset()         { *m = SimpleStructure{} }
func (m *SimpleStructure) String() string { return proto.CompactTextString(m) }
func (*SimpleStructure) ProtoMessage()    {}
func (*SimpleStructure) Descriptor() ([]byte, []int) {
	return fileDescriptor_f325e6597bcc547a, []int{6}
}

func (m *SimpleStructure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleStructure.Unmarshal(m, b)
}
func (m *SimpleStructure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleStructure.Marshal(b, m, deterministic)
}
func (m *SimpleStructure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleStructure.Merge(m, src)
}
func (m *SimpleStructure) XXX_Size() int {
	return xxx_messageInfo_SimpleStructure.Size(m)
}
func (m *SimpleStructure) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleStructure.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleStructure proto.InternalMessageInfo

func (m *SimpleStructure) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SimpleStructure) GetCreateAt() int64 {
	if m != nil {
		return m.CreateAt
	}
	return 0
}

func (m *SimpleStructure) GetOpening() bool {
	if m != nil {
		return m.Opening
	}
	return false
}

func (m *SimpleStructure) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SimpleStructure) GetFuncS() bool {
	if m != nil {
		return m.FuncS
	}
	return false
}

func (m *SimpleStructure) GetLastUpdateAt() int64 {
	if m != nil {
		return m.LastUpdateAt
	}
	return 0
}

func init() {
	proto.RegisterType((*GetInfoRequest)(nil), "gs.service.permission.GetInfoRequest")
	proto.RegisterType((*GetInfoResponse)(nil), "gs.service.permission.GetInfoResponse")
	proto.RegisterType((*CreateRequest)(nil), "gs.service.permission.CreateRequest")
	proto.RegisterType((*EnabledRequest)(nil), "gs.service.permission.EnabledRequest")
	proto.RegisterType((*GetListRequest)(nil), "gs.service.permission.GetListRequest")
	proto.RegisterType((*GetListResponse)(nil), "gs.service.permission.GetListResponse")
	proto.RegisterType((*SimpleStructure)(nil), "gs.service.permission.SimpleStructure")
}

func init() { proto.RegisterFile("permission/pb/structure.proto", fileDescriptor_f325e6597bcc547a) }

var fileDescriptor_f325e6597bcc547a = []byte{
	// 446 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xdf, 0x6f, 0xd3, 0x30,
	0x10, 0xc7, 0xd5, 0x5f, 0xdb, 0x7a, 0x83, 0x4e, 0x32, 0x0c, 0xa2, 0x4a, 0x48, 0x53, 0x04, 0x13,
	0xd2, 0x24, 0x57, 0x2a, 0x4f, 0xec, 0x0d, 0x21, 0x40, 0x95, 0xf6, 0x94, 0x68, 0x82, 0xd7, 0x34,
	0xbe, 0x55, 0x56, 0x1b, 0xdb, 0xf8, 0x1c, 0x1e, 0xf8, 0x7f, 0xf8, 0xf3, 0xf8, 0x1f, 0x50, 0xec,
	0xa4, 0x4d, 0x50, 0x57, 0x40, 0xec, 0xcd, 0xe7, 0x7c, 0xef, 0x73, 0xe7, 0xaf, 0x7d, 0x81, 0x17,
	0x06, 0x6d, 0x21, 0x89, 0xa4, 0x56, 0x33, 0xb3, 0x9c, 0x91, 0xb3, 0x65, 0xee, 0x4a, 0x8b, 0xdc,
	0x58, 0xed, 0x34, 0x3b, 0x5f, 0x11, 0x27, 0xb4, 0xdf, 0x64, 0x8e, 0x7c, 0xa7, 0x9c, 0x5e, 0xad,
	0xb5, 0xc2, 0xf5, 0x5a, 0xf3, 0x02, 0x67, 0x2b, 0xed, 0x93, 0x73, 0x5d, 0x14, 0x5a, 0xd1, 0x4c,
	0x38, 0xdd, 0xac, 0x03, 0x23, 0x9e, 0xc3, 0xe4, 0x13, 0xba, 0x85, 0xba, 0xd3, 0x09, 0x7e, 0x2d,
	0x91, 0x1c, 0xbb, 0x80, 0xd3, 0x6d, 0xa1, 0x85, 0x88, 0x7a, 0x17, 0xbd, 0xd7, 0xe3, 0xa4, 0xbd,
	0x15, 0x7f, 0x87, 0xb3, 0x6d, 0x0e, 0x19, 0xad, 0x08, 0xd9, 0x15, 0x8c, 0xc8, 0x65, 0x0e, 0xbd,
	0xfc, 0x74, 0x7e, 0xce, 0x57, 0xc4, 0x9b, 0x42, 0xc2, 0x69, 0x9e, 0x56, 0x1f, 0x93, 0xa0, 0x61,
	0xd7, 0x30, 0x14, 0x99, 0xcb, 0xa2, 0xbe, 0xd7, 0x5e, 0xf2, 0xbd, 0xc7, 0xe0, 0xa9, 0x2c, 0xcc,
	0x06, 0xd3, 0xa6, 0x6e, 0xe2, 0x73, 0xe2, 0xb7, 0xf0, 0xf8, 0xbd, 0xc5, 0x0a, 0x56, 0xb7, 0xcb,
	0x60, 0xa8, 0xb2, 0x02, 0xeb, 0x3e, 0xfd, 0x9a, 0x3d, 0x85, 0x51, 0x66, 0xcc, 0x42, 0xf8, 0x0a,
	0xe3, 0x24, 0x04, 0xf1, 0x0d, 0x4c, 0x3e, 0xa8, 0x6c, 0xb9, 0x41, 0xf1, 0xd7, 0x47, 0x65, 0x11,
	0x1c, 0x6b, 0x83, 0x4a, 0xaa, 0x95, 0x67, 0x9d, 0x24, 0x4d, 0x18, 0x5f, 0x7b, 0xe3, 0x6e, 0x24,
	0xb9, 0x86, 0xb6, 0xad, 0xda, 0x6b, 0x55, 0xad, 0xfa, 0x2b, 0x09, 0x6d, 0x9d, 0xee, 0xd7, 0xb5,
	0x81, 0x21, 0xf7, 0xff, 0x0c, 0x1c, 0xfc, 0xb3, 0x81, 0x3f, 0x7a, 0x70, 0xf6, 0xdb, 0x97, 0xbd,
	0x1e, 0x4e, 0xe1, 0x24, 0xf7, 0x46, 0xbf, 0x73, 0xbe, 0xf7, 0x41, 0xb2, 0x8d, 0xdb, 0xae, 0x0c,
	0x3a, 0xae, 0xb0, 0x09, 0xf4, 0xa5, 0x88, 0x86, 0x9e, 0xd3, 0x97, 0xa2, 0xf2, 0xe4, 0xae, 0x54,
	0x79, 0x1a, 0x8d, 0xbc, 0x2e, 0x04, 0x2c, 0x86, 0x47, 0x9b, 0x8c, 0xdc, 0xad, 0x11, 0x81, 0x7f,
	0xe4, 0xf9, 0x9d, 0xbd, 0xf9, 0xcf, 0x3e, 0x8c, 0x77, 0x1d, 0xa6, 0xf0, 0x24, 0x5c, 0xfb, 0x2d,
	0xa1, 0xdd, 0x6d, 0xbf, 0xbc, 0xe7, 0xe8, 0x9d, 0x27, 0x32, 0x7d, 0xb6, 0xcf, 0xcc, 0x92, 0xd8,
	0x67, 0x78, 0x1e, 0x84, 0x1f, 0x4b, 0x95, 0x3b, 0xa9, 0xd5, 0x43, 0x81, 0xbf, 0xc0, 0x71, 0x7d,
	0xbf, 0xec, 0xd5, 0x3d, 0xa0, 0xee, 0xdb, 0x99, 0x5e, 0xfe, 0x49, 0x56, 0x3f, 0x93, 0x40, 0xae,
	0x46, 0xef, 0x10, 0xb9, 0x35, 0xce, 0x87, 0xc8, 0xed, 0x09, 0x5e, 0x1e, 0xf9, 0xff, 0xc1, 0x9b,
	0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x78, 0x77, 0x16, 0x8b, 0x74, 0x04, 0x00, 0x00,
}
