// Code generated by protoc-gen-go. DO NOT EDIT.
// source: application/pb/ext/status.proto

package gs_ext_service_application

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	dto "konekko.me/gosion/commons/dto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetAppClientStatusRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAppClientStatusRequest) Reset()         { *m = GetAppClientStatusRequest{} }
func (m *GetAppClientStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetAppClientStatusRequest) ProtoMessage()    {}
func (*GetAppClientStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3145c9655bcccd15, []int{0}
}

func (m *GetAppClientStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppClientStatusRequest.Unmarshal(m, b)
}
func (m *GetAppClientStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppClientStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetAppClientStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppClientStatusRequest.Merge(m, src)
}
func (m *GetAppClientStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetAppClientStatusRequest.Size(m)
}
func (m *GetAppClientStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppClientStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppClientStatusRequest proto.InternalMessageInfo

func (m *GetAppClientStatusRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

type GetAppClientStatusResponse struct {
	State                *dto.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	AppId                string     `protobuf:"bytes,2,opt,name=appId,proto3" json:"appId,omitempty"`
	AppOpenMode          int64      `protobuf:"varint,3,opt,name=appOpenMode,proto3" json:"appOpenMode,omitempty"`
	AppQuarantine        int64      `protobuf:"varint,4,opt,name=appQuarantine,proto3" json:"appQuarantine,omitempty"`
	ClientPlatform       int64      `protobuf:"varint,5,opt,name=clientPlatform,proto3" json:"clientPlatform,omitempty"`
	ClientEnabled        int64      `protobuf:"varint,6,opt,name=clientEnabled,proto3" json:"clientEnabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAppClientStatusResponse) Reset()         { *m = GetAppClientStatusResponse{} }
func (m *GetAppClientStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetAppClientStatusResponse) ProtoMessage()    {}
func (*GetAppClientStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3145c9655bcccd15, []int{1}
}

func (m *GetAppClientStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppClientStatusResponse.Unmarshal(m, b)
}
func (m *GetAppClientStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppClientStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetAppClientStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppClientStatusResponse.Merge(m, src)
}
func (m *GetAppClientStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetAppClientStatusResponse.Size(m)
}
func (m *GetAppClientStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppClientStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppClientStatusResponse proto.InternalMessageInfo

func (m *GetAppClientStatusResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *GetAppClientStatusResponse) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *GetAppClientStatusResponse) GetAppOpenMode() int64 {
	if m != nil {
		return m.AppOpenMode
	}
	return 0
}

func (m *GetAppClientStatusResponse) GetAppQuarantine() int64 {
	if m != nil {
		return m.AppQuarantine
	}
	return 0
}

func (m *GetAppClientStatusResponse) GetClientPlatform() int64 {
	if m != nil {
		return m.ClientPlatform
	}
	return 0
}

func (m *GetAppClientStatusResponse) GetClientEnabled() int64 {
	if m != nil {
		return m.ClientEnabled
	}
	return 0
}

func init() {
	proto.RegisterType((*GetAppClientStatusRequest)(nil), "gs.ext.service.application.GetAppClientStatusRequest")
	proto.RegisterType((*GetAppClientStatusResponse)(nil), "gs.ext.service.application.GetAppClientStatusResponse")
}

func init() { proto.RegisterFile("application/pb/ext/status.proto", fileDescriptor_3145c9655bcccd15) }

var fileDescriptor_3145c9655bcccd15 = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x89, 0xb5, 0x45, 0xb7, 0x28, 0xb8, 0x28, 0xc4, 0x5c, 0x2c, 0x45, 0xa4, 0x50, 0xd8,
	0x40, 0x45, 0x3d, 0x17, 0x11, 0xe9, 0x41, 0xd4, 0xf8, 0x04, 0xdb, 0x64, 0x0c, 0xa1, 0xc9, 0xce,
	0x98, 0x9d, 0x4a, 0xef, 0x3e, 0x85, 0x0f, 0xea, 0x5d, 0xb2, 0x4b, 0xb5, 0x55, 0x7b, 0xf0, 0xb6,
	0xf3, 0xf1, 0xcf, 0x3f, 0xb3, 0xff, 0x88, 0x13, 0x4d, 0x54, 0x16, 0xa9, 0xe6, 0x02, 0x4d, 0x4c,
	0xd3, 0x18, 0x16, 0x1c, 0x5b, 0xd6, 0x3c, 0xb7, 0x8a, 0x6a, 0x64, 0x94, 0x51, 0x6e, 0x15, 0x2c,
	0x58, 0x59, 0xa8, 0x5f, 0x8b, 0x14, 0xd4, 0x8a, 0x3e, 0x1a, 0xce, 0xd0, 0xc0, 0x6c, 0x86, 0xaa,
	0x82, 0x38, 0x47, 0xdb, 0x58, 0xa4, 0x58, 0x55, 0x68, 0x6c, 0x9c, 0x31, 0x2e, 0xdf, 0xde, 0xa8,
	0x7f, 0x25, 0x8e, 0x6f, 0x81, 0xc7, 0x44, 0xd7, 0x65, 0x01, 0x86, 0x9f, 0xdc, 0x90, 0x04, 0x5e,
	0xe6, 0x60, 0x59, 0x46, 0x62, 0x27, 0x75, 0x78, 0x92, 0x85, 0x41, 0x2f, 0x18, 0xec, 0x26, 0x5f,
	0x75, 0xff, 0x23, 0x10, 0xd1, 0x5f, 0x9d, 0x96, 0xd0, 0x58, 0x90, 0x43, 0xd1, 0x6e, 0x16, 0x06,
	0xd7, 0xd7, 0x1d, 0x1d, 0xa9, 0xdc, 0xaa, 0xe5, 0xe4, 0x8c, 0x51, 0x35, 0x72, 0x48, 0xbc, 0x46,
	0x1e, 0x8a, 0xb6, 0x26, 0x9a, 0x64, 0xe1, 0x96, 0x1b, 0xe2, 0x0b, 0xd9, 0x13, 0x5d, 0x4d, 0x74,
	0x4f, 0x60, 0xee, 0x30, 0x83, 0xb0, 0xd5, 0x0b, 0x06, 0xad, 0x64, 0x15, 0xc9, 0x53, 0xb1, 0xa7,
	0x89, 0x1e, 0xe7, 0xba, 0xd6, 0x86, 0x0b, 0x03, 0xe1, 0xb6, 0xd3, 0xac, 0x43, 0x79, 0x26, 0xf6,
	0xfd, 0xd6, 0x0f, 0xa5, 0xe6, 0x67, 0xac, 0xab, 0xb0, 0xed, 0x64, 0x3f, 0x68, 0xe3, 0xe6, 0xc9,
	0x8d, 0xd1, 0xd3, 0x12, 0xb2, 0xb0, 0xe3, 0xdd, 0xd6, 0xe0, 0xe8, 0x3d, 0x10, 0x07, 0xe3, 0xef,
	0xb4, 0xfd, 0xb7, 0xe5, 0x5b, 0x20, 0x64, 0xfe, 0x2b, 0x0d, 0x79, 0xa1, 0x36, 0xdf, 0x49, 0x6d,
	0xcc, 0x3d, 0xba, 0xfc, 0x6f, 0x9b, 0x0f, 0x7d, 0xda, 0x71, 0x37, 0x3d, 0xff, 0x0c, 0x00, 0x00,
	0xff, 0xff, 0xbb, 0x94, 0xab, 0x0f, 0x3f, 0x02, 0x00, 0x00,
}
