// Code generated by protoc-gen-go. DO NOT EDIT.
// source: analysis/pb/analysis.proto

package xbasissvc_external_analysis

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	dto "konekko.me/xbasis/commons/dto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SearchFunctionRequest struct {
	Rank                 bool     `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	Page                 int64    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int64    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Keyword              string   `protobuf:"bytes,4,opt,name=keyword,proto3" json:"keyword,omitempty"`
	AppId                string   `protobuf:"bytes,5,opt,name=appId,proto3" json:"appId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchFunctionRequest) Reset()         { *m = SearchFunctionRequest{} }
func (m *SearchFunctionRequest) String() string { return proto.CompactTextString(m) }
func (*SearchFunctionRequest) ProtoMessage()    {}
func (*SearchFunctionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b748b773419a4153, []int{0}
}

func (m *SearchFunctionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchFunctionRequest.Unmarshal(m, b)
}
func (m *SearchFunctionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchFunctionRequest.Marshal(b, m, deterministic)
}
func (m *SearchFunctionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchFunctionRequest.Merge(m, src)
}
func (m *SearchFunctionRequest) XXX_Size() int {
	return xxx_messageInfo_SearchFunctionRequest.Size(m)
}
func (m *SearchFunctionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchFunctionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchFunctionRequest proto.InternalMessageInfo

func (m *SearchFunctionRequest) GetRank() bool {
	if m != nil {
		return m.Rank
	}
	return false
}

func (m *SearchFunctionRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchFunctionRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *SearchFunctionRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *SearchFunctionRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

type SearchFunctionResponse struct {
	State                *dto.State       `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Data                 []*StateFunction `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SearchFunctionResponse) Reset()         { *m = SearchFunctionResponse{} }
func (m *SearchFunctionResponse) String() string { return proto.CompactTextString(m) }
func (*SearchFunctionResponse) ProtoMessage()    {}
func (*SearchFunctionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b748b773419a4153, []int{1}
}

func (m *SearchFunctionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchFunctionResponse.Unmarshal(m, b)
}
func (m *SearchFunctionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchFunctionResponse.Marshal(b, m, deterministic)
}
func (m *SearchFunctionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchFunctionResponse.Merge(m, src)
}
func (m *SearchFunctionResponse) XXX_Size() int {
	return xxx_messageInfo_SearchFunctionResponse.Size(m)
}
func (m *SearchFunctionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchFunctionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchFunctionResponse proto.InternalMessageInfo

func (m *SearchFunctionResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *SearchFunctionResponse) GetData() []*StateFunction {
	if m != nil {
		return m.Data
	}
	return nil
}

type StateFunction struct {
	FunctionId           string   `protobuf:"bytes,1,opt,name=functionId,proto3" json:"functionId,omitempty"`
	Total                int64    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	TodayTotal           int64    `protobuf:"varint,3,opt,name=todayTotal,proto3" json:"todayTotal,omitempty"`
	LastDayTotal         int64    `protobuf:"varint,4,opt,name=lastDayTotal,proto3" json:"lastDayTotal,omitempty"`
	Error                int64    `protobuf:"varint,5,opt,name=error,proto3" json:"error,omitempty"`
	TodayError           int64    `protobuf:"varint,6,opt,name=todayError,proto3" json:"todayError,omitempty"`
	LastDayError         int64    `protobuf:"varint,7,opt,name=lastDayError,proto3" json:"lastDayError,omitempty"`
	AvgTiming            int64    `protobuf:"varint,8,opt,name=avgTiming,proto3" json:"avgTiming,omitempty"`
	MinTiming            int64    `protobuf:"varint,9,opt,name=minTiming,proto3" json:"minTiming,omitempty"`
	MaxTiming            int64    `protobuf:"varint,10,opt,name=maxTiming,proto3" json:"maxTiming,omitempty"`
	Timing               int64    `protobuf:"varint,11,opt,name=timing,proto3" json:"timing,omitempty"`
	LastDayUserVisit     int64    `protobuf:"varint,12,opt,name=lastDayUserVisit,proto3" json:"lastDayUserVisit,omitempty"`
	TodayUserVisit       int64    `protobuf:"varint,13,opt,name=todayUserVisit,proto3" json:"todayUserVisit,omitempty"`
	FunctionName         string   `protobuf:"bytes,14,opt,name=functionName,proto3" json:"functionName,omitempty"`
	Path                 string   `protobuf:"bytes,15,opt,name=path,proto3" json:"path,omitempty"`
	AppId                string   `protobuf:"bytes,16,opt,name=appId,proto3" json:"appId,omitempty"`
	Mnovps               int64    `protobuf:"varint,17,opt,name=mnovps,proto3" json:"mnovps,omitempty"`
	Mnovpm               int64    `protobuf:"varint,18,opt,name=mnovpm,proto3" json:"mnovpm,omitempty"`
	Mnovph               int64    `protobuf:"varint,19,opt,name=mnovph,proto3" json:"mnovph,omitempty"`
	AvgDayTotal          int64    `protobuf:"varint,20,opt,name=avgDayTotal,proto3" json:"avgDayTotal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateFunction) Reset()         { *m = StateFunction{} }
func (m *StateFunction) String() string { return proto.CompactTextString(m) }
func (*StateFunction) ProtoMessage()    {}
func (*StateFunction) Descriptor() ([]byte, []int) {
	return fileDescriptor_b748b773419a4153, []int{2}
}

func (m *StateFunction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateFunction.Unmarshal(m, b)
}
func (m *StateFunction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateFunction.Marshal(b, m, deterministic)
}
func (m *StateFunction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateFunction.Merge(m, src)
}
func (m *StateFunction) XXX_Size() int {
	return xxx_messageInfo_StateFunction.Size(m)
}
func (m *StateFunction) XXX_DiscardUnknown() {
	xxx_messageInfo_StateFunction.DiscardUnknown(m)
}

var xxx_messageInfo_StateFunction proto.InternalMessageInfo

func (m *StateFunction) GetFunctionId() string {
	if m != nil {
		return m.FunctionId
	}
	return ""
}

func (m *StateFunction) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *StateFunction) GetTodayTotal() int64 {
	if m != nil {
		return m.TodayTotal
	}
	return 0
}

func (m *StateFunction) GetLastDayTotal() int64 {
	if m != nil {
		return m.LastDayTotal
	}
	return 0
}

func (m *StateFunction) GetError() int64 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *StateFunction) GetTodayError() int64 {
	if m != nil {
		return m.TodayError
	}
	return 0
}

func (m *StateFunction) GetLastDayError() int64 {
	if m != nil {
		return m.LastDayError
	}
	return 0
}

func (m *StateFunction) GetAvgTiming() int64 {
	if m != nil {
		return m.AvgTiming
	}
	return 0
}

func (m *StateFunction) GetMinTiming() int64 {
	if m != nil {
		return m.MinTiming
	}
	return 0
}

func (m *StateFunction) GetMaxTiming() int64 {
	if m != nil {
		return m.MaxTiming
	}
	return 0
}

func (m *StateFunction) GetTiming() int64 {
	if m != nil {
		return m.Timing
	}
	return 0
}

func (m *StateFunction) GetLastDayUserVisit() int64 {
	if m != nil {
		return m.LastDayUserVisit
	}
	return 0
}

func (m *StateFunction) GetTodayUserVisit() int64 {
	if m != nil {
		return m.TodayUserVisit
	}
	return 0
}

func (m *StateFunction) GetFunctionName() string {
	if m != nil {
		return m.FunctionName
	}
	return ""
}

func (m *StateFunction) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *StateFunction) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *StateFunction) GetMnovps() int64 {
	if m != nil {
		return m.Mnovps
	}
	return 0
}

func (m *StateFunction) GetMnovpm() int64 {
	if m != nil {
		return m.Mnovpm
	}
	return 0
}

func (m *StateFunction) GetMnovph() int64 {
	if m != nil {
		return m.Mnovph
	}
	return 0
}

func (m *StateFunction) GetAvgDayTotal() int64 {
	if m != nil {
		return m.AvgDayTotal
	}
	return 0
}

type GetFunctionDetailRequest struct {
	FunctionId           string   `protobuf:"bytes,1,opt,name=functionId,proto3" json:"functionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFunctionDetailRequest) Reset()         { *m = GetFunctionDetailRequest{} }
func (m *GetFunctionDetailRequest) String() string { return proto.CompactTextString(m) }
func (*GetFunctionDetailRequest) ProtoMessage()    {}
func (*GetFunctionDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b748b773419a4153, []int{3}
}

func (m *GetFunctionDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFunctionDetailRequest.Unmarshal(m, b)
}
func (m *GetFunctionDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFunctionDetailRequest.Marshal(b, m, deterministic)
}
func (m *GetFunctionDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFunctionDetailRequest.Merge(m, src)
}
func (m *GetFunctionDetailRequest) XXX_Size() int {
	return xxx_messageInfo_GetFunctionDetailRequest.Size(m)
}
func (m *GetFunctionDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFunctionDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFunctionDetailRequest proto.InternalMessageInfo

func (m *GetFunctionDetailRequest) GetFunctionId() string {
	if m != nil {
		return m.FunctionId
	}
	return ""
}

type GetFunctionDetailResponse struct {
	State                *dto.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetFunctionDetailResponse) Reset()         { *m = GetFunctionDetailResponse{} }
func (m *GetFunctionDetailResponse) String() string { return proto.CompactTextString(m) }
func (*GetFunctionDetailResponse) ProtoMessage()    {}
func (*GetFunctionDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b748b773419a4153, []int{4}
}

func (m *GetFunctionDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFunctionDetailResponse.Unmarshal(m, b)
}
func (m *GetFunctionDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFunctionDetailResponse.Marshal(b, m, deterministic)
}
func (m *GetFunctionDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFunctionDetailResponse.Merge(m, src)
}
func (m *GetFunctionDetailResponse) XXX_Size() int {
	return xxx_messageInfo_GetFunctionDetailResponse.Size(m)
}
func (m *GetFunctionDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFunctionDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFunctionDetailResponse proto.InternalMessageInfo

func (m *GetFunctionDetailResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

type SearchTrackingRequest struct {
	// def is PermissionVerification
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	AppId                string   `protobuf:"bytes,3,opt,name=appId,proto3" json:"appId,omitempty"`
	Page                 int64    `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int64    `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchTrackingRequest) Reset()         { *m = SearchTrackingRequest{} }
func (m *SearchTrackingRequest) String() string { return proto.CompactTextString(m) }
func (*SearchTrackingRequest) ProtoMessage()    {}
func (*SearchTrackingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b748b773419a4153, []int{5}
}

func (m *SearchTrackingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchTrackingRequest.Unmarshal(m, b)
}
func (m *SearchTrackingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchTrackingRequest.Marshal(b, m, deterministic)
}
func (m *SearchTrackingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchTrackingRequest.Merge(m, src)
}
func (m *SearchTrackingRequest) XXX_Size() int {
	return xxx_messageInfo_SearchTrackingRequest.Size(m)
}
func (m *SearchTrackingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchTrackingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchTrackingRequest proto.InternalMessageInfo

func (m *SearchTrackingRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SearchTrackingRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *SearchTrackingRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *SearchTrackingRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchTrackingRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type SearchTrackingResponse struct {
	State                *dto.State         `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Data                 []*RequestTracking `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SearchTrackingResponse) Reset()         { *m = SearchTrackingResponse{} }
func (m *SearchTrackingResponse) String() string { return proto.CompactTextString(m) }
func (*SearchTrackingResponse) ProtoMessage()    {}
func (*SearchTrackingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b748b773419a4153, []int{6}
}

func (m *SearchTrackingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchTrackingResponse.Unmarshal(m, b)
}
func (m *SearchTrackingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchTrackingResponse.Marshal(b, m, deterministic)
}
func (m *SearchTrackingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchTrackingResponse.Merge(m, src)
}
func (m *SearchTrackingResponse) XXX_Size() int {
	return xxx_messageInfo_SearchTrackingResponse.Size(m)
}
func (m *SearchTrackingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchTrackingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchTrackingResponse proto.InternalMessageInfo

func (m *SearchTrackingResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *SearchTrackingResponse) GetData() []*RequestTracking {
	if m != nil {
		return m.Data
	}
	return nil
}

type RequestTracking struct {
	TrackId              string       `protobuf:"bytes,1,opt,name=trackId,proto3" json:"trackId,omitempty"`
	UserAgent            string       `protobuf:"bytes,2,opt,name=userAgent,proto3" json:"userAgent,omitempty"`
	Path                 string       `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Ip                   string       `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	RouteTo              string       `protobuf:"bytes,5,opt,name=routeTo,proto3" json:"routeTo,omitempty"`
	Function             string       `protobuf:"bytes,6,opt,name=function,proto3" json:"function,omitempty"`
	Timestamp            int64        `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UserId               string       `protobuf:"bytes,8,opt,name=userId,proto3" json:"userId,omitempty"`
	HasAccessToken       bool         `protobuf:"varint,9,opt,name=hasAccessToken,proto3" json:"hasAccessToken,omitempty"`
	HasDurationToken     bool         `protobuf:"varint,10,opt,name=hasDurationToken,proto3" json:"hasDurationToken,omitempty"`
	Passed               bool         `protobuf:"varint,11,opt,name=passed,proto3" json:"passed,omitempty"`
	Taking               *StageTaking `protobuf:"bytes,12,opt,name=taking,proto3" json:"taking,omitempty"`
	BasicValidation      bool         `protobuf:"varint,13,opt,name=basicValidation,proto3" json:"basicValidation,omitempty"`
	InvalidApi           bool         `protobuf:"varint,14,opt,name=invalidApi,proto3" json:"invalidApi,omitempty"`
	DeniedApiClient      bool         `protobuf:"varint,15,opt,name=deniedApiClient,proto3" json:"deniedApiClient,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RequestTracking) Reset()         { *m = RequestTracking{} }
func (m *RequestTracking) String() string { return proto.CompactTextString(m) }
func (*RequestTracking) ProtoMessage()    {}
func (*RequestTracking) Descriptor() ([]byte, []int) {
	return fileDescriptor_b748b773419a4153, []int{7}
}

func (m *RequestTracking) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestTracking.Unmarshal(m, b)
}
func (m *RequestTracking) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestTracking.Marshal(b, m, deterministic)
}
func (m *RequestTracking) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestTracking.Merge(m, src)
}
func (m *RequestTracking) XXX_Size() int {
	return xxx_messageInfo_RequestTracking.Size(m)
}
func (m *RequestTracking) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestTracking.DiscardUnknown(m)
}

var xxx_messageInfo_RequestTracking proto.InternalMessageInfo

func (m *RequestTracking) GetTrackId() string {
	if m != nil {
		return m.TrackId
	}
	return ""
}

func (m *RequestTracking) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

func (m *RequestTracking) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *RequestTracking) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *RequestTracking) GetRouteTo() string {
	if m != nil {
		return m.RouteTo
	}
	return ""
}

func (m *RequestTracking) GetFunction() string {
	if m != nil {
		return m.Function
	}
	return ""
}

func (m *RequestTracking) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *RequestTracking) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RequestTracking) GetHasAccessToken() bool {
	if m != nil {
		return m.HasAccessToken
	}
	return false
}

func (m *RequestTracking) GetHasDurationToken() bool {
	if m != nil {
		return m.HasDurationToken
	}
	return false
}

func (m *RequestTracking) GetPassed() bool {
	if m != nil {
		return m.Passed
	}
	return false
}

func (m *RequestTracking) GetTaking() *StageTaking {
	if m != nil {
		return m.Taking
	}
	return nil
}

func (m *RequestTracking) GetBasicValidation() bool {
	if m != nil {
		return m.BasicValidation
	}
	return false
}

func (m *RequestTracking) GetInvalidApi() bool {
	if m != nil {
		return m.InvalidApi
	}
	return false
}

func (m *RequestTracking) GetDeniedApiClient() bool {
	if m != nil {
		return m.DeniedApiClient
	}
	return false
}

type GetTrackingDetailRequest struct {
	TraceId              string   `protobuf:"bytes,1,opt,name=traceId,proto3" json:"traceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTrackingDetailRequest) Reset()         { *m = GetTrackingDetailRequest{} }
func (m *GetTrackingDetailRequest) String() string { return proto.CompactTextString(m) }
func (*GetTrackingDetailRequest) ProtoMessage()    {}
func (*GetTrackingDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b748b773419a4153, []int{8}
}

func (m *GetTrackingDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTrackingDetailRequest.Unmarshal(m, b)
}
func (m *GetTrackingDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTrackingDetailRequest.Marshal(b, m, deterministic)
}
func (m *GetTrackingDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTrackingDetailRequest.Merge(m, src)
}
func (m *GetTrackingDetailRequest) XXX_Size() int {
	return xxx_messageInfo_GetTrackingDetailRequest.Size(m)
}
func (m *GetTrackingDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTrackingDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTrackingDetailRequest proto.InternalMessageInfo

func (m *GetTrackingDetailRequest) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

type TrackingStageResponse struct {
	State                *dto.State           `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Data                 []*TrackingStageItem `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	FunctionId           string               `protobuf:"bytes,3,opt,name=functionId,proto3" json:"functionId,omitempty"`
	AppId                string               `protobuf:"bytes,4,opt,name=appId,proto3" json:"appId,omitempty"`
	Taking               *StageTaking         `protobuf:"bytes,5,opt,name=taking,proto3" json:"taking,omitempty"`
	FunctionName         string               `protobuf:"bytes,6,opt,name=functionName,proto3" json:"functionName,omitempty"`
	Timestamp            int64                `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UserId               string               `protobuf:"bytes,8,opt,name=userId,proto3" json:"userId,omitempty"`
	ClientId             string               `protobuf:"bytes,9,opt,name=clientId,proto3" json:"clientId,omitempty"`
	RefClientId          string               `protobuf:"bytes,10,opt,name=refClientId,proto3" json:"refClientId,omitempty"`
	AuthTypes            []string             `protobuf:"bytes,11,rep,name=authTypes,proto3" json:"authTypes,omitempty"`
	UserAgent            string               `protobuf:"bytes,12,opt,name=userAgent,proto3" json:"userAgent,omitempty"`
	UserDevice           string               `protobuf:"bytes,13,opt,name=userDevice,proto3" json:"userDevice,omitempty"`
	Ip                   string               `protobuf:"bytes,14,opt,name=ip,proto3" json:"ip,omitempty"`
	Message              string               `protobuf:"bytes,15,opt,name=message,proto3" json:"message,omitempty"`
	HasAccessToken       bool                 `protobuf:"varint,16,opt,name=hasAccessToken,proto3" json:"hasAccessToken,omitempty"`
	HasDurationToken     bool                 `protobuf:"varint,17,opt,name=hasDurationToken,proto3" json:"hasDurationToken,omitempty"`
	Passed               bool                 `protobuf:"varint,18,opt,name=passed,proto3" json:"passed,omitempty"`
	BasicValidation      bool                 `protobuf:"varint,19,opt,name=basicValidation,proto3" json:"basicValidation,omitempty"`
	InvalidApi           bool                 `protobuf:"varint,20,opt,name=invalidApi,proto3" json:"invalidApi,omitempty"`
	DeniedApiClient      bool                 `protobuf:"varint,21,opt,name=deniedApiClient,proto3" json:"deniedApiClient,omitempty"`
	Path                 string               `protobuf:"bytes,22,opt,name=path,proto3" json:"path,omitempty"`
	Platform             string               `protobuf:"bytes,23,opt,name=platform,proto3" json:"platform,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TrackingStageResponse) Reset()         { *m = TrackingStageResponse{} }
func (m *TrackingStageResponse) String() string { return proto.CompactTextString(m) }
func (*TrackingStageResponse) ProtoMessage()    {}
func (*TrackingStageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b748b773419a4153, []int{9}
}

func (m *TrackingStageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackingStageResponse.Unmarshal(m, b)
}
func (m *TrackingStageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackingStageResponse.Marshal(b, m, deterministic)
}
func (m *TrackingStageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackingStageResponse.Merge(m, src)
}
func (m *TrackingStageResponse) XXX_Size() int {
	return xxx_messageInfo_TrackingStageResponse.Size(m)
}
func (m *TrackingStageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackingStageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TrackingStageResponse proto.InternalMessageInfo

func (m *TrackingStageResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *TrackingStageResponse) GetData() []*TrackingStageItem {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *TrackingStageResponse) GetFunctionId() string {
	if m != nil {
		return m.FunctionId
	}
	return ""
}

func (m *TrackingStageResponse) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *TrackingStageResponse) GetTaking() *StageTaking {
	if m != nil {
		return m.Taking
	}
	return nil
}

func (m *TrackingStageResponse) GetFunctionName() string {
	if m != nil {
		return m.FunctionName
	}
	return ""
}

func (m *TrackingStageResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *TrackingStageResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TrackingStageResponse) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *TrackingStageResponse) GetRefClientId() string {
	if m != nil {
		return m.RefClientId
	}
	return ""
}

func (m *TrackingStageResponse) GetAuthTypes() []string {
	if m != nil {
		return m.AuthTypes
	}
	return nil
}

func (m *TrackingStageResponse) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

func (m *TrackingStageResponse) GetUserDevice() string {
	if m != nil {
		return m.UserDevice
	}
	return ""
}

func (m *TrackingStageResponse) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *TrackingStageResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *TrackingStageResponse) GetHasAccessToken() bool {
	if m != nil {
		return m.HasAccessToken
	}
	return false
}

func (m *TrackingStageResponse) GetHasDurationToken() bool {
	if m != nil {
		return m.HasDurationToken
	}
	return false
}

func (m *TrackingStageResponse) GetPassed() bool {
	if m != nil {
		return m.Passed
	}
	return false
}

func (m *TrackingStageResponse) GetBasicValidation() bool {
	if m != nil {
		return m.BasicValidation
	}
	return false
}

func (m *TrackingStageResponse) GetInvalidApi() bool {
	if m != nil {
		return m.InvalidApi
	}
	return false
}

func (m *TrackingStageResponse) GetDeniedApiClient() bool {
	if m != nil {
		return m.DeniedApiClient
	}
	return false
}

func (m *TrackingStageResponse) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *TrackingStageResponse) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

type TrackingStageItem struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	Timing               int64    `protobuf:"varint,2,opt,name=timing,proto3" json:"timing,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	StateCode            int64    `protobuf:"varint,4,opt,name=stateCode,proto3" json:"stateCode,omitempty"`
	ModuleName           string   `protobuf:"bytes,5,opt,name=moduleName,proto3" json:"moduleName,omitempty"`
	Level                string   `protobuf:"bytes,6,opt,name=level,proto3" json:"level,omitempty"`
	Action               string   `protobuf:"bytes,7,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackingStageItem) Reset()         { *m = TrackingStageItem{} }
func (m *TrackingStageItem) String() string { return proto.CompactTextString(m) }
func (*TrackingStageItem) ProtoMessage()    {}
func (*TrackingStageItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_b748b773419a4153, []int{10}
}

func (m *TrackingStageItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackingStageItem.Unmarshal(m, b)
}
func (m *TrackingStageItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackingStageItem.Marshal(b, m, deterministic)
}
func (m *TrackingStageItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackingStageItem.Merge(m, src)
}
func (m *TrackingStageItem) XXX_Size() int {
	return xxx_messageInfo_TrackingStageItem.Size(m)
}
func (m *TrackingStageItem) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackingStageItem.DiscardUnknown(m)
}

var xxx_messageInfo_TrackingStageItem proto.InternalMessageInfo

func (m *TrackingStageItem) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *TrackingStageItem) GetTiming() int64 {
	if m != nil {
		return m.Timing
	}
	return 0
}

func (m *TrackingStageItem) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *TrackingStageItem) GetStateCode() int64 {
	if m != nil {
		return m.StateCode
	}
	return 0
}

func (m *TrackingStageItem) GetModuleName() string {
	if m != nil {
		return m.ModuleName
	}
	return ""
}

func (m *TrackingStageItem) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *TrackingStageItem) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

type StageTaking struct {
	Verification         float64  `protobuf:"fixed64,1,opt,name=verification,proto3" json:"verification,omitempty"`
	Process              float64  `protobuf:"fixed64,2,opt,name=process,proto3" json:"process,omitempty"`
	All                  float64  `protobuf:"fixed64,3,opt,name=all,proto3" json:"all,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StageTaking) Reset()         { *m = StageTaking{} }
func (m *StageTaking) String() string { return proto.CompactTextString(m) }
func (*StageTaking) ProtoMessage()    {}
func (*StageTaking) Descriptor() ([]byte, []int) {
	return fileDescriptor_b748b773419a4153, []int{11}
}

func (m *StageTaking) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StageTaking.Unmarshal(m, b)
}
func (m *StageTaking) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StageTaking.Marshal(b, m, deterministic)
}
func (m *StageTaking) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StageTaking.Merge(m, src)
}
func (m *StageTaking) XXX_Size() int {
	return xxx_messageInfo_StageTaking.Size(m)
}
func (m *StageTaking) XXX_DiscardUnknown() {
	xxx_messageInfo_StageTaking.DiscardUnknown(m)
}

var xxx_messageInfo_StageTaking proto.InternalMessageInfo

func (m *StageTaking) GetVerification() float64 {
	if m != nil {
		return m.Verification
	}
	return 0
}

func (m *StageTaking) GetProcess() float64 {
	if m != nil {
		return m.Process
	}
	return 0
}

func (m *StageTaking) GetAll() float64 {
	if m != nil {
		return m.All
	}
	return 0
}

func init() {
	proto.RegisterType((*SearchFunctionRequest)(nil), "xbasissvc.external.analysis.SearchFunctionRequest")
	proto.RegisterType((*SearchFunctionResponse)(nil), "xbasissvc.external.analysis.SearchFunctionResponse")
	proto.RegisterType((*StateFunction)(nil), "xbasissvc.external.analysis.StateFunction")
	proto.RegisterType((*GetFunctionDetailRequest)(nil), "xbasissvc.external.analysis.GetFunctionDetailRequest")
	proto.RegisterType((*GetFunctionDetailResponse)(nil), "xbasissvc.external.analysis.GetFunctionDetailResponse")
	proto.RegisterType((*SearchTrackingRequest)(nil), "xbasissvc.external.analysis.SearchTrackingRequest")
	proto.RegisterType((*SearchTrackingResponse)(nil), "xbasissvc.external.analysis.SearchTrackingResponse")
	proto.RegisterType((*RequestTracking)(nil), "xbasissvc.external.analysis.RequestTracking")
	proto.RegisterType((*GetTrackingDetailRequest)(nil), "xbasissvc.external.analysis.GetTrackingDetailRequest")
	proto.RegisterType((*TrackingStageResponse)(nil), "xbasissvc.external.analysis.TrackingStageResponse")
	proto.RegisterType((*TrackingStageItem)(nil), "xbasissvc.external.analysis.TrackingStageItem")
	proto.RegisterType((*StageTaking)(nil), "xbasissvc.external.analysis.StageTaking")
}

func init() { proto.RegisterFile("analysis/pb/analysis.proto", fileDescriptor_b748b773419a4153) }

var fileDescriptor_b748b773419a4153 = []byte{
	// 1182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0x4d, 0x6f, 0xdb, 0x46,
	0x13, 0x06, 0x4d, 0x59, 0x96, 0x56, 0x8e, 0x3f, 0x18, 0xdb, 0x2f, 0xa3, 0x37, 0x08, 0x04, 0x1e,
	0x0a, 0x21, 0x2d, 0x24, 0x40, 0x69, 0x7b, 0xe8, 0xa1, 0x88, 0x6b, 0xb7, 0x85, 0x80, 0xa2, 0x07,
	0x46, 0xcd, 0xad, 0x87, 0x35, 0xb9, 0x96, 0x16, 0x22, 0xb9, 0x2c, 0x77, 0xa5, 0x5a, 0x01, 0x7a,
	0x69, 0x4e, 0x45, 0xfb, 0x6b, 0xfa, 0x57, 0xfa, 0x0b, 0xfa, 0x3b, 0x7a, 0x29, 0x66, 0x3f, 0xa8,
	0x25, 0xad, 0xda, 0x8a, 0x6e, 0x3b, 0xcf, 0xcc, 0x7e, 0xcd, 0xcc, 0xf3, 0x2c, 0x89, 0xba, 0x38,
	0xc3, 0xc9, 0x8a, 0x53, 0x3e, 0xcc, 0x6f, 0x86, 0x66, 0x3c, 0xc8, 0x0b, 0x26, 0x98, 0xf7, 0xff,
	0xbb, 0x1b, 0xcc, 0x29, 0xe7, 0xcb, 0x68, 0x40, 0xee, 0x04, 0x29, 0x32, 0x9c, 0x0c, 0x4c, 0x48,
	0xf7, 0xe3, 0x39, 0xcb, 0xc8, 0x7c, 0xce, 0x06, 0x29, 0x19, 0xaa, 0xb8, 0x61, 0xc4, 0xd2, 0x94,
	0x65, 0x7c, 0x18, 0x0b, 0x66, 0xc6, 0x6a, 0xa5, 0xe0, 0xbd, 0x83, 0xce, 0xdf, 0x10, 0x5c, 0x44,
	0xb3, 0x6f, 0x16, 0x59, 0x24, 0x28, 0xcb, 0x42, 0xf2, 0xd3, 0x82, 0x70, 0xe1, 0x79, 0xa8, 0x51,
	0xe0, 0x6c, 0xee, 0x3b, 0x3d, 0xa7, 0xdf, 0x0a, 0xe5, 0x18, 0xb0, 0x1c, 0x4f, 0x89, 0xbf, 0xd7,
	0x73, 0xfa, 0x6e, 0x28, 0xc7, 0x80, 0x71, 0xfa, 0x8e, 0xf8, 0xae, 0xc2, 0x60, 0xec, 0xf9, 0xe8,
	0x60, 0x4e, 0x56, 0x3f, 0xb3, 0x22, 0xf6, 0x1b, 0x3d, 0xa7, 0xdf, 0x0e, 0x8d, 0xe9, 0x9d, 0xa1,
	0x7d, 0x9c, 0xe7, 0xe3, 0xd8, 0xdf, 0x97, 0xb8, 0x32, 0x82, 0xdf, 0x1c, 0x74, 0x51, 0x3f, 0x05,
	0xcf, 0x59, 0xc6, 0x89, 0x37, 0x44, 0xfb, 0x5c, 0x60, 0x41, 0xe4, 0x39, 0x3a, 0xa3, 0x67, 0x03,
	0x75, 0xa5, 0x81, 0xb9, 0x46, 0x2c, 0xd8, 0xe0, 0x0d, 0x04, 0x84, 0x2a, 0xce, 0xfb, 0x12, 0x35,
	0x62, 0x2c, 0xb0, 0xbf, 0xd7, 0x73, 0xfb, 0x9d, 0xd1, 0xcb, 0xc1, 0x03, 0xa9, 0x52, 0x13, 0xcb,
	0x2d, 0xe5, 0xbc, 0xe0, 0xef, 0x06, 0x7a, 0x52, 0xc1, 0xbd, 0x17, 0x08, 0xdd, 0xea, 0xf1, 0x38,
	0x96, 0xe7, 0x68, 0x87, 0x16, 0x02, 0x77, 0x12, 0x4c, 0xe0, 0x44, 0xa7, 0x45, 0x19, 0x30, 0x4b,
	0xb0, 0x18, 0xaf, 0x26, 0xd2, 0xa5, 0xb2, 0x63, 0x21, 0x5e, 0x80, 0x0e, 0x13, 0xcc, 0xc5, 0xb5,
	0x89, 0x68, 0xc8, 0x88, 0x0a, 0x06, 0x2b, 0x93, 0xa2, 0x60, 0x85, 0xcc, 0x96, 0x1b, 0x2a, 0xa3,
	0x5c, 0xf9, 0x6b, 0xe9, 0x6a, 0x5a, 0x2b, 0x4b, 0xc4, 0x5a, 0x59, 0x45, 0x1c, 0x54, 0x56, 0x56,
	0x31, 0xcf, 0x51, 0x1b, 0x2f, 0xa7, 0x13, 0x9a, 0xd2, 0x6c, 0xea, 0xb7, 0x64, 0xc0, 0x1a, 0x00,
	0x6f, 0x4a, 0x33, 0xed, 0x6d, 0x2b, 0x6f, 0x09, 0x48, 0x2f, 0xbe, 0xd3, 0x5e, 0xa4, 0xbd, 0x06,
	0xf0, 0x2e, 0x50, 0x53, 0x28, 0x57, 0x47, 0xba, 0xb4, 0xe5, 0xbd, 0x44, 0x27, 0xfa, 0x04, 0x3f,
	0x70, 0x52, 0xbc, 0xa5, 0x9c, 0x0a, 0xff, 0x50, 0x46, 0xdc, 0xc3, 0xbd, 0x8f, 0xd0, 0x91, 0xbc,
	0xcf, 0x3a, 0xf2, 0x89, 0x8c, 0xac, 0xa1, 0x70, 0x53, 0x53, 0x87, 0xef, 0x71, 0x4a, 0xfc, 0x23,
	0x59, 0x9b, 0x0a, 0xa6, 0x7a, 0x56, 0xcc, 0xfc, 0x63, 0xe9, 0x93, 0xe3, 0x75, 0x17, 0x9e, 0x58,
	0x5d, 0x08, 0x27, 0x4f, 0x33, 0xb6, 0xcc, 0xb9, 0x7f, 0xaa, 0x4e, 0xae, 0xac, 0x12, 0x4f, 0x7d,
	0xcf, 0xc2, 0xd3, 0x12, 0x9f, 0xf9, 0x4f, 0x2d, 0x7c, 0xe6, 0xf5, 0x50, 0x07, 0x2f, 0xa7, 0x65,
	0x61, 0xcf, 0xa4, 0xd3, 0x86, 0x82, 0x2f, 0x90, 0xff, 0x2d, 0x11, 0xa6, 0xc1, 0xae, 0x89, 0xc0,
	0x34, 0x31, 0xbc, 0x7b, 0xa4, 0xdb, 0x82, 0xef, 0xd0, 0xb3, 0x0d, 0x73, 0x77, 0x64, 0x4b, 0xf0,
	0x8b, 0xa1, 0xff, 0xa4, 0xc0, 0xd1, 0x9c, 0x66, 0x53, 0x73, 0x8c, 0x13, 0xe4, 0xce, 0xc9, 0x4a,
	0xef, 0x0f, 0x43, 0x48, 0xda, 0x12, 0x27, 0x0b, 0xc5, 0xfe, 0x76, 0xa8, 0x8c, 0x75, 0x2a, 0x5d,
	0x3b, 0x95, 0x46, 0x28, 0x1a, 0x1b, 0x84, 0x62, 0x7f, 0x2d, 0x14, 0xc1, 0xef, 0x25, 0xf1, 0xd7,
	0xfb, 0xef, 0x4a, 0xfc, 0xd7, 0x15, 0xe2, 0x7f, 0xf2, 0x20, 0xf1, 0xf5, 0x2d, 0xcb, 0x4d, 0x15,
	0xf5, 0xff, 0x71, 0xd1, 0x71, 0xcd, 0x03, 0x52, 0x26, 0x60, 0x5c, 0xd6, 0xc2, 0x98, 0x40, 0x83,
	0x05, 0x27, 0xc5, 0xe5, 0x94, 0x64, 0x42, 0xe7, 0x64, 0x0d, 0x94, 0x6d, 0xe7, 0x5a, 0x6d, 0x77,
	0x84, 0xf6, 0x68, 0xae, 0x15, 0x71, 0x8f, 0xe6, 0xb0, 0x76, 0xc1, 0x16, 0x82, 0x4c, 0x98, 0x96,
	0x43, 0x63, 0x7a, 0x5d, 0xd4, 0x32, 0x25, 0x97, 0x04, 0x6f, 0x87, 0xa5, 0x0d, 0xfb, 0x0a, 0x9a,
	0x12, 0x2e, 0x70, 0x9a, 0x6b, 0x6e, 0xaf, 0x01, 0x68, 0x4a, 0x38, 0xc4, 0x38, 0x96, 0xac, 0x6e,
	0x87, 0xda, 0x02, 0x4a, 0xcd, 0x30, 0xbf, 0x8c, 0x22, 0xc2, 0xf9, 0x84, 0xcd, 0x49, 0x26, 0x79,
	0xdd, 0x0a, 0x6b, 0x28, 0xd0, 0x74, 0x86, 0xf9, 0xf5, 0xa2, 0xc0, 0xb0, 0x99, 0x8a, 0x44, 0x32,
	0xf2, 0x1e, 0x0e, 0x7b, 0xe5, 0x98, 0x73, 0x12, 0x4b, 0xaa, 0xb7, 0x42, 0x6d, 0x79, 0xaf, 0x51,
	0x53, 0x60, 0xc8, 0x9e, 0x24, 0x78, 0x67, 0xd4, 0x7f, 0x4c, 0x84, 0xa7, 0x64, 0x22, 0xe3, 0x43,
	0x3d, 0xcf, 0xeb, 0xa3, 0x63, 0x98, 0x11, 0xbd, 0xc5, 0x09, 0x8d, 0xe5, 0x8e, 0x52, 0x01, 0x5a,
	0x61, 0x1d, 0x06, 0xba, 0xd0, 0x6c, 0x09, 0xf6, 0x65, 0x4e, 0xa5, 0x00, 0xb4, 0x42, 0x0b, 0x81,
	0x95, 0x62, 0x92, 0x51, 0x02, 0xc6, 0x55, 0x42, 0xa1, 0x56, 0xc7, 0x6a, 0xa5, 0x1a, 0x1c, 0x7c,
	0x2a, 0x49, 0x69, 0x0a, 0x5f, 0x25, 0xa5, 0xee, 0x02, 0x52, 0xed, 0x02, 0x32, 0x8e, 0x83, 0x3f,
	0x9b, 0xe8, 0xdc, 0xcc, 0x91, 0x37, 0xd9, 0xbd, 0x81, 0xbf, 0xaa, 0x34, 0xf0, 0xe0, 0xc1, 0xa4,
	0x55, 0xb6, 0x1c, 0x0b, 0x92, 0xaa, 0x16, 0xae, 0xa9, 0x87, 0xbb, 0xe9, 0xad, 0x52, 0x74, 0x6d,
	0xd8, 0x74, 0x5d, 0x17, 0x6c, 0x7f, 0xc7, 0x82, 0xd5, 0x95, 0xb8, 0xb9, 0x41, 0x89, 0x77, 0x6b,
	0xdc, 0x2e, 0x6a, 0x45, 0xb2, 0x40, 0xe3, 0x58, 0xb6, 0x6c, 0x3b, 0x2c, 0x6d, 0x50, 0xda, 0x82,
	0xdc, 0x5e, 0x19, 0x37, 0x92, 0x6e, 0x1b, 0x92, 0xef, 0xdc, 0x42, 0xcc, 0x26, 0xab, 0x9c, 0x70,
	0xbf, 0xd3, 0x73, 0x81, 0xa4, 0x25, 0x50, 0xa5, 0xf0, 0x61, 0x9d, 0xc2, 0x2f, 0x10, 0x02, 0xe3,
	0x9a, 0x2c, 0x69, 0x44, 0x64, 0xff, 0xb5, 0x43, 0x0b, 0xd1, 0x74, 0x3e, 0xb2, 0xe9, 0x9c, 0x12,
	0xce, 0x41, 0xf7, 0xd4, 0x63, 0x63, 0xcc, 0x0d, 0xe4, 0x3b, 0xd9, 0x9a, 0x7c, 0xa7, 0x8f, 0x92,
	0xcf, 0xab, 0x90, 0x6f, 0x03, 0x75, 0x9e, 0x6e, 0x43, 0x9d, 0xb3, 0x6d, 0xa8, 0x73, 0xbe, 0x91,
	0x3a, 0xa5, 0xd8, 0x5d, 0x58, 0x62, 0xd7, 0x45, 0xad, 0x3c, 0xc1, 0xe2, 0x96, 0x15, 0xa9, 0xff,
	0x3f, 0x55, 0x37, 0x63, 0x07, 0x7f, 0x39, 0xe8, 0xf4, 0x5e, 0x07, 0x43, 0x35, 0x39, 0x29, 0x20,
	0xb5, 0xb2, 0x85, 0x14, 0xd1, 0x6c, 0xc8, 0xfa, 0xb6, 0xd8, 0xab, 0x7c, 0x5b, 0x58, 0x99, 0x77,
	0xab, 0x99, 0x7f, 0x8e, 0xda, 0x92, 0x5c, 0x57, 0x2c, 0x36, 0xaf, 0xd1, 0x1a, 0x80, 0x0c, 0xa4,
	0x2c, 0x5e, 0x24, 0x6a, 0x43, 0xa5, 0xc1, 0x16, 0x02, 0x6c, 0x49, 0xc8, 0x92, 0x24, 0xba, 0x9d,
	0x95, 0x01, 0xa7, 0xc0, 0x4a, 0x9a, 0x0f, 0x54, 0xa7, 0x2a, 0x2b, 0xf8, 0x11, 0x75, 0x2c, 0x6a,
	0x00, 0x25, 0x96, 0xa4, 0xa0, 0xb7, 0x34, 0x52, 0x55, 0x80, 0xfb, 0x38, 0x61, 0x05, 0x83, 0x83,
	0xe7, 0x05, 0x83, 0x06, 0x90, 0x37, 0x72, 0x42, 0x63, 0xc2, 0xfb, 0x8b, 0x13, 0xf5, 0xdd, 0xe8,
	0x84, 0x30, 0x1c, 0xfd, 0xd1, 0x40, 0xad, 0x4b, 0xcd, 0x41, 0x6f, 0x85, 0x8e, 0xaa, 0xef, 0xa6,
	0x37, 0x7a, 0x98, 0xb3, 0x9b, 0x1e, 0xf9, 0xee, 0xab, 0x0f, 0x9a, 0xa3, 0x75, 0xed, 0xbd, 0x83,
	0x2e, 0x2c, 0xa1, 0x94, 0x57, 0x56, 0x6a, 0xe9, 0x7d, 0xf6, 0xe0, 0x7a, 0xff, 0xa5, 0xae, 0xdd,
	0xd1, 0xf6, 0x52, 0x57, 0x9e, 0xe2, 0x57, 0x07, 0x9d, 0xde, 0xfb, 0x0e, 0x7a, 0xfc, 0x00, 0x1b,
	0xbf, 0xb9, 0xba, 0x9f, 0x7f, 0xe8, 0x34, 0x7d, 0x88, 0x77, 0xe8, 0xb8, 0xfa, 0xdb, 0xc2, 0xb7,
	0x2a, 0x43, 0xed, 0x57, 0x6b, 0xab, 0x32, 0xd4, 0x7f, 0x8c, 0x6e, 0x9a, 0xf2, 0x07, 0xee, 0xd5,
	0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x42, 0xc7, 0xd9, 0xef, 0x28, 0x0e, 0x00, 0x00,
}
