// Code generated by protoc-gen-go. DO NOT EDIT.
// source: application/pb/application.proto

package gs_service_application

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	dto "konekko.me/gosion/commons/dto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SwitchRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	Enabled              bool     `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwitchRequest) Reset()         { *m = SwitchRequest{} }
func (m *SwitchRequest) String() string { return proto.CompactTextString(m) }
func (*SwitchRequest) ProtoMessage()    {}
func (*SwitchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b974f2f4f838fbc1, []int{0}
}

func (m *SwitchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchRequest.Unmarshal(m, b)
}
func (m *SwitchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchRequest.Marshal(b, m, deterministic)
}
func (m *SwitchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchRequest.Merge(m, src)
}
func (m *SwitchRequest) XXX_Size() int {
	return xxx_messageInfo_SwitchRequest.Size(m)
}
func (m *SwitchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchRequest proto.InternalMessageInfo

func (m *SwitchRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *SwitchRequest) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type FindRequest struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindRequest) Reset()         { *m = FindRequest{} }
func (m *FindRequest) String() string { return proto.CompactTextString(m) }
func (*FindRequest) ProtoMessage()    {}
func (*FindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b974f2f4f838fbc1, []int{1}
}

func (m *FindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindRequest.Unmarshal(m, b)
}
func (m *FindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindRequest.Marshal(b, m, deterministic)
}
func (m *FindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindRequest.Merge(m, src)
}
func (m *FindRequest) XXX_Size() int {
	return xxx_messageInfo_FindRequest.Size(m)
}
func (m *FindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindRequest proto.InternalMessageInfo

func (m *FindRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type ListResponse struct {
	State                *dto.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Info                 []*AppInfo `protobuf:"bytes,2,rep,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b974f2f4f838fbc1, []int{2}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *ListResponse) GetInfo() []*AppInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type SimpleApplicationResponse struct {
	State                *dto.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Info                 *AppInfo   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SimpleApplicationResponse) Reset()         { *m = SimpleApplicationResponse{} }
func (m *SimpleApplicationResponse) String() string { return proto.CompactTextString(m) }
func (*SimpleApplicationResponse) ProtoMessage()    {}
func (*SimpleApplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b974f2f4f838fbc1, []int{3}
}

func (m *SimpleApplicationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleApplicationResponse.Unmarshal(m, b)
}
func (m *SimpleApplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleApplicationResponse.Marshal(b, m, deterministic)
}
func (m *SimpleApplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleApplicationResponse.Merge(m, src)
}
func (m *SimpleApplicationResponse) XXX_Size() int {
	return xxx_messageInfo_SimpleApplicationResponse.Size(m)
}
func (m *SimpleApplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleApplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleApplicationResponse proto.InternalMessageInfo

func (m *SimpleApplicationResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *SimpleApplicationResponse) GetInfo() *AppInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type CreateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Open                 bool     `protobuf:"varint,3,opt,name=open,proto3" json:"open,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	MustSync             bool     `protobuf:"varint,5,opt,name=mustSync,proto3" json:"mustSync,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b974f2f4f838fbc1, []int{4}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRequest) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *CreateRequest) GetOpen() bool {
	if m != nil {
		return m.Open
	}
	return false
}

func (m *CreateRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CreateRequest) GetMustSync() bool {
	if m != nil {
		return m.MustSync
	}
	return false
}

type RemoveRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveRequest) Reset()         { *m = RemoveRequest{} }
func (m *RemoveRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveRequest) ProtoMessage()    {}
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b974f2f4f838fbc1, []int{5}
}

func (m *RemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRequest.Unmarshal(m, b)
}
func (m *RemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRequest.Marshal(b, m, deterministic)
}
func (m *RemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRequest.Merge(m, src)
}
func (m *RemoveRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveRequest.Size(m)
}
func (m *RemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRequest proto.InternalMessageInfo

func (m *RemoveRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

type ChangeNameRequest struct {
	AppId                string   `protobuf:"bytes,2,opt,name=appId,proto3" json:"appId,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeNameRequest) Reset()         { *m = ChangeNameRequest{} }
func (m *ChangeNameRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeNameRequest) ProtoMessage()    {}
func (*ChangeNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b974f2f4f838fbc1, []int{6}
}

func (m *ChangeNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeNameRequest.Unmarshal(m, b)
}
func (m *ChangeNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeNameRequest.Marshal(b, m, deterministic)
}
func (m *ChangeNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeNameRequest.Merge(m, src)
}
func (m *ChangeNameRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeNameRequest.Size(m)
}
func (m *ChangeNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeNameRequest proto.InternalMessageInfo

func (m *ChangeNameRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *ChangeNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AppInfo struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Desc                 string           `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	AppId                string           `protobuf:"bytes,3,opt,name=appId,proto3" json:"appId,omitempty"`
	Enabled              int64            `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreateAt             int64            `protobuf:"varint,5,opt,name=createAt,proto3" json:"createAt,omitempty"`
	Clients              []*AppClientInfo `protobuf:"bytes,6,rep,name=clients,proto3" json:"clients,omitempty"`
	Settings             *dto.AppSettings `protobuf:"bytes,7,opt,name=settings,proto3" json:"settings,omitempty"`
	CreateUserId         string           `protobuf:"bytes,8,opt,name=createUserId,proto3" json:"createUserId,omitempty"`
	Type                 string           `protobuf:"bytes,9,opt,name=type,proto3" json:"type,omitempty"`
	FuncS                string           `protobuf:"bytes,10,opt,name=funcS,proto3" json:"funcS,omitempty"`
	UserS                string           `protobuf:"bytes,11,opt,name=userS,proto3" json:"userS,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AppInfo) Reset()         { *m = AppInfo{} }
func (m *AppInfo) String() string { return proto.CompactTextString(m) }
func (*AppInfo) ProtoMessage()    {}
func (*AppInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b974f2f4f838fbc1, []int{7}
}

func (m *AppInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppInfo.Unmarshal(m, b)
}
func (m *AppInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppInfo.Marshal(b, m, deterministic)
}
func (m *AppInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppInfo.Merge(m, src)
}
func (m *AppInfo) XXX_Size() int {
	return xxx_messageInfo_AppInfo.Size(m)
}
func (m *AppInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AppInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AppInfo proto.InternalMessageInfo

func (m *AppInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AppInfo) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *AppInfo) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *AppInfo) GetEnabled() int64 {
	if m != nil {
		return m.Enabled
	}
	return 0
}

func (m *AppInfo) GetCreateAt() int64 {
	if m != nil {
		return m.CreateAt
	}
	return 0
}

func (m *AppInfo) GetClients() []*AppClientInfo {
	if m != nil {
		return m.Clients
	}
	return nil
}

func (m *AppInfo) GetSettings() *dto.AppSettings {
	if m != nil {
		return m.Settings
	}
	return nil
}

func (m *AppInfo) GetCreateUserId() string {
	if m != nil {
		return m.CreateUserId
	}
	return ""
}

func (m *AppInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AppInfo) GetFuncS() string {
	if m != nil {
		return m.FuncS
	}
	return ""
}

func (m *AppInfo) GetUserS() string {
	if m != nil {
		return m.UserS
	}
	return ""
}

type AppClientInfo struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	Enabled              int64    `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Platform             int64    `protobuf:"varint,3,opt,name=platform,proto3" json:"platform,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppClientInfo) Reset()         { *m = AppClientInfo{} }
func (m *AppClientInfo) String() string { return proto.CompactTextString(m) }
func (*AppClientInfo) ProtoMessage()    {}
func (*AppClientInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b974f2f4f838fbc1, []int{8}
}

func (m *AppClientInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppClientInfo.Unmarshal(m, b)
}
func (m *AppClientInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppClientInfo.Marshal(b, m, deterministic)
}
func (m *AppClientInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppClientInfo.Merge(m, src)
}
func (m *AppClientInfo) XXX_Size() int {
	return xxx_messageInfo_AppClientInfo.Size(m)
}
func (m *AppClientInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AppClientInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AppClientInfo proto.InternalMessageInfo

func (m *AppClientInfo) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *AppClientInfo) GetEnabled() int64 {
	if m != nil {
		return m.Enabled
	}
	return 0
}

func (m *AppClientInfo) GetPlatform() int64 {
	if m != nil {
		return m.Platform
	}
	return 0
}

func init() {
	proto.RegisterType((*SwitchRequest)(nil), "gs.service.application.SwitchRequest")
	proto.RegisterType((*FindRequest)(nil), "gs.service.application.FindRequest")
	proto.RegisterType((*ListResponse)(nil), "gs.service.application.ListResponse")
	proto.RegisterType((*SimpleApplicationResponse)(nil), "gs.service.application.SimpleApplicationResponse")
	proto.RegisterType((*CreateRequest)(nil), "gs.service.application.CreateRequest")
	proto.RegisterType((*RemoveRequest)(nil), "gs.service.application.RemoveRequest")
	proto.RegisterType((*ChangeNameRequest)(nil), "gs.service.application.ChangeNameRequest")
	proto.RegisterType((*AppInfo)(nil), "gs.service.application.AppInfo")
	proto.RegisterType((*AppClientInfo)(nil), "gs.service.application.AppClientInfo")
}

func init() { proto.RegisterFile("application/pb/application.proto", fileDescriptor_b974f2f4f838fbc1) }

var fileDescriptor_b974f2f4f838fbc1 = []byte{
	// 622 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x51, 0x6f, 0xd3, 0x3c,
	0x14, 0x55, 0x9b, 0xae, 0xed, 0x6e, 0xd7, 0x4f, 0x1f, 0x16, 0x4c, 0xa6, 0x3c, 0x50, 0x05, 0x26,
	0x86, 0x26, 0xa5, 0x62, 0x7b, 0xe0, 0x09, 0x4d, 0xa5, 0x12, 0xd3, 0x24, 0x04, 0x22, 0x11, 0x3f,
	0x20, 0x4b, 0x6e, 0xbb, 0x68, 0x89, 0x6d, 0x62, 0x67, 0xa8, 0x0f, 0xfc, 0x52, 0xc4, 0x7f, 0x41,
	0xb6, 0x9b, 0xac, 0x19, 0xf3, 0x34, 0x09, 0xf1, 0x76, 0xaf, 0x73, 0x72, 0x7c, 0xcf, 0xbd, 0xc7,
	0x36, 0x4c, 0x63, 0x21, 0xf2, 0x2c, 0x89, 0x55, 0xc6, 0xd9, 0x4c, 0x5c, 0xcc, 0xb6, 0xd2, 0x40,
	0x94, 0x5c, 0x71, 0xb2, 0xbf, 0x92, 0x81, 0xc4, 0xf2, 0x3a, 0x4b, 0x30, 0xd8, 0xfa, 0x3a, 0x39,
	0xba, 0xe2, 0x0c, 0xaf, 0xae, 0x78, 0x50, 0xe0, 0x6c, 0xc5, 0xa5, 0xfe, 0x3f, 0xe1, 0x45, 0xc1,
	0x99, 0x9c, 0xa5, 0x8a, 0xd7, 0xb1, 0x25, 0xf1, 0x4f, 0x61, 0x1c, 0x7d, 0xcf, 0x54, 0x72, 0x19,
	0xe2, 0xb7, 0x0a, 0xa5, 0x22, 0x8f, 0x61, 0x27, 0x16, 0xe2, 0x3c, 0xa5, 0x9d, 0x69, 0xe7, 0x70,
	0x37, 0xb4, 0x09, 0xa1, 0x30, 0x40, 0x16, 0x5f, 0xe4, 0x98, 0xd2, 0xee, 0xb4, 0x73, 0x38, 0x0c,
	0xeb, 0xd4, 0x7f, 0x05, 0xa3, 0x0f, 0x19, 0x4b, 0xeb, 0xdf, 0x29, 0x0c, 0x12, 0xce, 0x14, 0x32,
	0xb5, 0x21, 0xa8, 0x53, 0x5f, 0xc0, 0xde, 0xc7, 0x4c, 0xaa, 0x10, 0xa5, 0xe0, 0x4c, 0x22, 0x39,
	0x82, 0x1d, 0xa9, 0x62, 0x85, 0x06, 0x37, 0x3a, 0x7e, 0x12, 0xac, 0x64, 0x50, 0xd7, 0x96, 0x2a,
	0x1e, 0x44, 0xfa, 0x63, 0x68, 0x31, 0xe4, 0x04, 0x7a, 0x19, 0x5b, 0x72, 0xda, 0x9d, 0x7a, 0x87,
	0xa3, 0xe3, 0xe7, 0xc1, 0xdd, 0xd2, 0x83, 0xb9, 0x10, 0xe7, 0x6c, 0xc9, 0x43, 0x03, 0xf6, 0x7f,
	0xc0, 0xd3, 0x28, 0x2b, 0x44, 0x8e, 0xf3, 0x1b, 0xc8, 0xdf, 0x6e, 0xdf, 0x79, 0xf8, 0xf6, 0x6b,
	0x18, 0x2f, 0x4a, 0xd4, 0x2c, 0x9b, 0xde, 0x10, 0xe8, 0xb1, 0xb8, 0xc0, 0x4d, 0x63, 0x4c, 0xac,
	0xd7, 0x52, 0x94, 0x89, 0x61, 0xde, 0x0d, 0x4d, 0xac, 0xd7, 0xb8, 0x40, 0x46, 0x3d, 0xd3, 0x69,
	0x13, 0x93, 0xff, 0xc1, 0xab, 0xca, 0x9c, 0xf6, 0x0c, 0x4c, 0x87, 0x64, 0x02, 0xc3, 0xa2, 0x92,
	0x2a, 0x5a, 0xb3, 0x84, 0xee, 0x18, 0x64, 0x93, 0xfb, 0x07, 0x30, 0x0e, 0xb1, 0xe0, 0xd7, 0x78,
	0xef, 0x54, 0xfd, 0x77, 0xf0, 0x68, 0x71, 0x19, 0xb3, 0x15, 0x7e, 0x8a, 0x8b, 0x3f, 0xa1, 0xdd,
	0x6d, 0x03, 0xd4, 0xb5, 0x7b, 0x37, 0xb5, 0xfb, 0x3f, 0xbb, 0x30, 0xd8, 0x48, 0x7e, 0xb0, 0xb6,
	0x86, 0xdd, 0x73, 0xd8, 0x4b, 0x2b, 0xf4, 0x1a, 0x7b, 0x69, 0x95, 0x89, 0x69, 0xe2, 0x5c, 0x19,
	0x95, 0x5e, 0xd8, 0xe4, 0xe4, 0x14, 0x06, 0x49, 0x9e, 0x21, 0x53, 0x92, 0xf6, 0x8d, 0x2f, 0x0e,
	0xee, 0x19, 0xcc, 0xc2, 0x20, 0xcd, 0x78, 0xea, 0xbf, 0xc8, 0x5b, 0x18, 0x4a, 0x54, 0x2a, 0x63,
	0x2b, 0x49, 0x07, 0x66, 0xb4, 0xcf, 0x6e, 0xdb, 0x60, 0x2e, 0x44, 0xb4, 0x81, 0x84, 0x0d, 0x98,
	0xf8, 0xb0, 0x67, 0xab, 0xf8, 0x2a, 0xb1, 0x3c, 0x4f, 0xe9, 0xd0, 0x88, 0x69, 0xad, 0x69, 0xf5,
	0x6a, 0x2d, 0x90, 0xee, 0x5a, 0xf5, 0x3a, 0xd6, 0xea, 0x97, 0x15, 0x4b, 0x22, 0x0a, 0x56, 0xbd,
	0x49, 0xf4, 0x6a, 0x25, 0xb1, 0x8c, 0xe8, 0xc8, 0xae, 0x9a, 0xc4, 0x8f, 0x61, 0xdc, 0x2a, 0xdb,
	0xb4, 0xc2, 0x66, 0xf5, 0x18, 0x9b, 0xfc, 0xf6, 0xf9, 0x6c, 0x37, 0x50, 0xe4, 0xb1, 0x5a, 0xf2,
	0xb2, 0x30, 0x3d, 0xf7, 0xc2, 0x26, 0x3f, 0xfe, 0xd5, 0x83, 0xd1, 0xd6, 0xd9, 0x20, 0x67, 0xd0,
	0xb7, 0x8e, 0x25, 0xce, 0x4e, 0xb6, 0x1c, 0x3d, 0xd9, 0xbf, 0xeb, 0xd4, 0x54, 0x52, 0x13, 0x59,
	0xff, 0xb9, 0x89, 0x5a, 0xfe, 0x74, 0x12, 0x7d, 0x06, 0xb8, 0x71, 0x28, 0x79, 0xed, 0xac, 0xea,
	0xb6, 0x8b, 0x9d, 0x84, 0x68, 0xaf, 0xab, 0xf7, 0xeb, 0xb9, 0x31, 0xde, 0x0b, 0x17, 0xe3, 0xd6,
	0x9d, 0x36, 0x79, 0xe3, 0x02, 0xb9, 0x6f, 0x97, 0x4b, 0xf8, 0xcf, 0x6e, 0xb3, 0xa8, 0x27, 0xf4,
	0xaf, 0x76, 0xfa, 0x02, 0x3d, 0x7d, 0xad, 0x3e, 0x8c, 0xff, 0xa5, 0x0b, 0xd4, 0xba, 0x99, 0xcf,
	0xa0, 0x6f, 0xdf, 0x04, 0xf7, 0xf4, 0x5a, 0x6f, 0x86, 0xab, 0xd9, 0x17, 0x7d, 0xf3, 0xc6, 0x9c,
	0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x37, 0xdd, 0x00, 0xcc, 0x06, 0x00, 0x00,
}
