// Code generated by protoc-gen-go. DO NOT EDIT.
// source: application/pb/settings.proto

package xbasissvc_external_application

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	dto "konekko.me/xbasis/commons/dto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UpdateRequest struct {
	AppId                string           `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	Setting              *dto.AppSettings `protobuf:"bytes,2,opt,name=setting,proto3" json:"setting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64137262ba2d32b7, []int{0}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *UpdateRequest) GetSetting() *dto.AppSettings {
	if m != nil {
		return m.Setting
	}
	return nil
}

type EnabledRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Enabled              int64    `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnabledRequest) Reset()         { *m = EnabledRequest{} }
func (m *EnabledRequest) String() string { return proto.CompactTextString(m) }
func (*EnabledRequest) ProtoMessage()    {}
func (*EnabledRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64137262ba2d32b7, []int{1}
}

func (m *EnabledRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnabledRequest.Unmarshal(m, b)
}
func (m *EnabledRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnabledRequest.Marshal(b, m, deterministic)
}
func (m *EnabledRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnabledRequest.Merge(m, src)
}
func (m *EnabledRequest) XXX_Size() int {
	return xxx_messageInfo_EnabledRequest.Size(m)
}
func (m *EnabledRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnabledRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnabledRequest proto.InternalMessageInfo

func (m *EnabledRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *EnabledRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EnabledRequest) GetEnabled() int64 {
	if m != nil {
		return m.Enabled
	}
	return 0
}

type GetRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64137262ba2d32b7, []int{2}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func init() {
	proto.RegisterType((*UpdateRequest)(nil), "xbasissvc.external.application.UpdateRequest")
	proto.RegisterType((*EnabledRequest)(nil), "xbasissvc.external.application.EnabledRequest")
	proto.RegisterType((*GetRequest)(nil), "xbasissvc.external.application.GetRequest")
}

func init() { proto.RegisterFile("application/pb/settings.proto", fileDescriptor_64137262ba2d32b7) }

var fileDescriptor_64137262ba2d32b7 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x69, 0x17, 0x77, 0xdd, 0x91, 0xdd, 0x43, 0xf0, 0x50, 0x0a, 0x6a, 0xe9, 0xa9, 0x20,
	0xa6, 0xb0, 0x9e, 0x3c, 0x8a, 0x88, 0x78, 0x93, 0x16, 0x4f, 0x5e, 0x4c, 0x9b, 0x41, 0x42, 0xdb,
	0x24, 0x6e, 0x66, 0x65, 0x7f, 0x9c, 0x3f, 0x4e, 0xd8, 0x34, 0xe0, 0x82, 0xd4, 0x5b, 0x06, 0xe6,
	0x7d, 0x79, 0xef, 0x0d, 0x5c, 0x08, 0x6b, 0x7b, 0xd5, 0x0a, 0x52, 0x46, 0x97, 0xb6, 0x29, 0x1d,
	0x12, 0x29, 0xfd, 0xe1, 0xb8, 0xdd, 0x1a, 0x32, 0xec, 0x72, 0xdf, 0x08, 0xa7, 0x9c, 0xfb, 0x6a,
	0x39, 0xee, 0x09, 0xb7, 0x5a, 0xf4, 0xfc, 0x97, 0x22, 0xbd, 0xee, 0x8c, 0xc6, 0xae, 0x33, 0x7c,
	0xc0, 0xd2, 0xaf, 0x96, 0xad, 0x19, 0x06, 0xa3, 0x5d, 0x29, 0xc9, 0x84, 0xb7, 0x87, 0xe5, 0xef,
	0xb0, 0x7a, 0xb5, 0x52, 0x10, 0x56, 0xf8, 0xb9, 0x43, 0x47, 0xec, 0x1c, 0x4e, 0x84, 0xb5, 0xcf,
	0x32, 0x89, 0xb2, 0xa8, 0x58, 0x56, 0x7e, 0x60, 0x77, 0xb0, 0x18, 0x5d, 0x24, 0x71, 0x16, 0x15,
	0x67, 0x9b, 0x2b, 0xee, 0xd1, 0x3c, 0xe0, 0x24, 0x19, 0x7e, 0x6f, 0x6d, 0x3d, 0x7a, 0xad, 0xc2,
	0x7e, 0xfe, 0x02, 0xeb, 0x47, 0x2d, 0x9a, 0x1e, 0xe5, 0xf4, 0x17, 0x6b, 0x88, 0x95, 0x3c, 0xd0,
	0x97, 0x55, 0xac, 0x24, 0x4b, 0x60, 0x81, 0x5e, 0x97, 0xcc, 0xb2, 0xa8, 0x98, 0x55, 0x61, 0xcc,
	0x73, 0x80, 0x27, 0xa4, 0x49, 0xda, 0xe6, 0x3b, 0x82, 0xd3, 0xe0, 0x85, 0xd5, 0x30, 0xf7, 0x21,
	0xd9, 0x0d, 0x9f, 0x2e, 0x8f, 0x1f, 0x95, 0x91, 0xa6, 0x7f, 0xa5, 0xac, 0x49, 0xd0, 0xce, 0xb1,
	0x37, 0x58, 0x8d, 0xb9, 0x1e, 0x7a, 0x85, 0x9a, 0x18, 0xff, 0x8f, 0x7d, 0x5c, 0xc3, 0x14, 0xbc,
	0x99, 0x1f, 0xae, 0x73, 0xfb, 0x13, 0x00, 0x00, 0xff, 0xff, 0x90, 0x80, 0xe5, 0xe3, 0x0b, 0x02,
	0x00, 0x00,
}
