// Code generated by protoc-gen-go. DO NOT EDIT.
// source: safety/pb/locking.proto

package gosionsvc_external_safety

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	dto "konekko.me/gosion/commons/dto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SearchRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Page                 int64    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int64    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e289366ac52c5b50, []int{0}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SearchRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *SearchRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type SearchResponse struct {
	State                *dto.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e289366ac52c5b50, []int{1}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

type LockingItem struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreateAt             int64    `protobuf:"varint,2,opt,name=createAt,proto3" json:"createAt,omitempty"`
	CreateUser           string   `protobuf:"bytes,3,opt,name=createUser,proto3" json:"createUser,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	UserId               string   `protobuf:"bytes,5,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockingItem) Reset()         { *m = LockingItem{} }
func (m *LockingItem) String() string { return proto.CompactTextString(m) }
func (*LockingItem) ProtoMessage()    {}
func (*LockingItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_e289366ac52c5b50, []int{2}
}

func (m *LockingItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockingItem.Unmarshal(m, b)
}
func (m *LockingItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockingItem.Marshal(b, m, deterministic)
}
func (m *LockingItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockingItem.Merge(m, src)
}
func (m *LockingItem) XXX_Size() int {
	return xxx_messageInfo_LockingItem.Size(m)
}
func (m *LockingItem) XXX_DiscardUnknown() {
	xxx_messageInfo_LockingItem.DiscardUnknown(m)
}

var xxx_messageInfo_LockingItem proto.InternalMessageInfo

func (m *LockingItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LockingItem) GetCreateAt() int64 {
	if m != nil {
		return m.CreateAt
	}
	return 0
}

func (m *LockingItem) GetCreateUser() string {
	if m != nil {
		return m.CreateUser
	}
	return ""
}

func (m *LockingItem) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LockingItem) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type LockRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Time                 int64    `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockRequest) Reset()         { *m = LockRequest{} }
func (m *LockRequest) String() string { return proto.CompactTextString(m) }
func (*LockRequest) ProtoMessage()    {}
func (*LockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e289366ac52c5b50, []int{3}
}

func (m *LockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockRequest.Unmarshal(m, b)
}
func (m *LockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockRequest.Marshal(b, m, deterministic)
}
func (m *LockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockRequest.Merge(m, src)
}
func (m *LockRequest) XXX_Size() int {
	return xxx_messageInfo_LockRequest.Size(m)
}
func (m *LockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LockRequest proto.InternalMessageInfo

func (m *LockRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *LockRequest) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type UnlockRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnlockRequest) Reset()         { *m = UnlockRequest{} }
func (m *UnlockRequest) String() string { return proto.CompactTextString(m) }
func (*UnlockRequest) ProtoMessage()    {}
func (*UnlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e289366ac52c5b50, []int{4}
}

func (m *UnlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlockRequest.Unmarshal(m, b)
}
func (m *UnlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlockRequest.Marshal(b, m, deterministic)
}
func (m *UnlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlockRequest.Merge(m, src)
}
func (m *UnlockRequest) XXX_Size() int {
	return xxx_messageInfo_UnlockRequest.Size(m)
}
func (m *UnlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnlockRequest proto.InternalMessageInfo

func (m *UnlockRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func init() {
	proto.RegisterType((*SearchRequest)(nil), "gosionsvc.external.safety.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "gosionsvc.external.safety.SearchResponse")
	proto.RegisterType((*LockingItem)(nil), "gosionsvc.external.safety.LockingItem")
	proto.RegisterType((*LockRequest)(nil), "gosionsvc.external.safety.LockRequest")
	proto.RegisterType((*UnlockRequest)(nil), "gosionsvc.external.safety.UnlockRequest")
}

func init() { proto.RegisterFile("safety/pb/locking.proto", fileDescriptor_e289366ac52c5b50) }

var fileDescriptor_e289366ac52c5b50 = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x41, 0x6b, 0xdb, 0x30,
	0x14, 0xc7, 0xf1, 0x9c, 0x78, 0xcb, 0x0b, 0x19, 0x43, 0x6c, 0x99, 0xe7, 0xc3, 0x08, 0x3e, 0x6c,
	0x19, 0x01, 0x19, 0xb2, 0xd3, 0x0e, 0x3b, 0xec, 0x32, 0xc8, 0xd8, 0xc9, 0x21, 0xc7, 0x52, 0x14,
	0xe7, 0xd5, 0x35, 0xb6, 0x25, 0xd7, 0x92, 0x43, 0xd3, 0x6f, 0xd1, 0xef, 0xdb, 0x43, 0x91, 0x64,
	0xa7, 0x09, 0x34, 0x69, 0x6f, 0xff, 0xf7, 0xf4, 0xd7, 0x7b, 0x3f, 0x3d, 0x3d, 0xf8, 0x2c, 0xd9,
	0x15, 0xaa, 0x5d, 0x54, 0xad, 0xa3, 0x42, 0x24, 0x79, 0xc6, 0x53, 0x5a, 0xd5, 0x42, 0x09, 0xf2,
	0x25, 0x15, 0x32, 0x13, 0x5c, 0x6e, 0x13, 0x8a, 0xb7, 0x0a, 0x6b, 0xce, 0x0a, 0x6a, 0xbd, 0xc1,
	0x2c, 0x17, 0x1c, 0xf3, 0x5c, 0xd0, 0x12, 0x23, 0xeb, 0x8a, 0x12, 0x51, 0x96, 0x82, 0xcb, 0x68,
	0xa3, 0x44, 0xa7, 0x6d, 0x9d, 0xf0, 0x12, 0x46, 0x4b, 0x64, 0x75, 0x72, 0x1d, 0xe3, 0x4d, 0x83,
	0x52, 0x91, 0x0f, 0xe0, 0xe6, 0xb8, 0xf3, 0x9d, 0x89, 0x33, 0x1d, 0xc4, 0x5a, 0x92, 0x8f, 0xd0,
	0xdf, 0xb2, 0xa2, 0x41, 0xff, 0x8d, 0xc9, 0xd9, 0x80, 0x10, 0xe8, 0x55, 0x2c, 0x45, 0xdf, 0x9d,
	0x38, 0x53, 0x37, 0x36, 0x5a, 0xe7, 0x64, 0x76, 0x87, 0x7e, 0xcf, 0xe6, 0xb4, 0x0e, 0x7f, 0xc3,
	0xfb, 0xae, 0x81, 0xac, 0x04, 0x97, 0x48, 0x66, 0xd0, 0x97, 0x8a, 0x29, 0x34, 0x3d, 0x86, 0xf3,
	0x4f, 0x34, 0x95, 0xb4, 0x83, 0xda, 0x28, 0x41, 0x97, 0xfa, 0x30, 0xb6, 0x9e, 0xf0, 0xde, 0x81,
	0xe1, 0x7f, 0xfb, 0xf2, 0x85, 0xc2, 0x52, 0xb7, 0xe0, 0xac, 0xc4, 0x96, 0xcf, 0x68, 0x12, 0xc0,
	0xbb, 0xa4, 0x46, 0xa6, 0xf0, 0x8f, 0x32, 0x8c, 0x6e, 0xbc, 0x8f, 0xc9, 0x57, 0x00, 0xab, 0x57,
	0x12, 0x6b, 0x03, 0x3b, 0x88, 0x0f, 0x32, 0xfa, 0x6e, 0x23, 0xf5, 0xf8, 0x4a, 0x8b, 0x3d, 0x88,
	0xf7, 0x31, 0x19, 0x83, 0xa7, 0xf5, 0x62, 0xe3, 0xf7, 0xcd, 0x49, 0x1b, 0x85, 0xbf, 0x2c, 0x52,
	0x37, 0xb1, 0x27, 0x9b, 0x73, 0x68, 0xd3, 0xa8, 0x2a, 0x2b, 0xb1, 0x45, 0x32, 0x3a, 0xfc, 0x0e,
	0xa3, 0x15, 0x2f, 0x5e, 0xbe, 0x3c, 0x7f, 0x70, 0xe0, 0x6d, 0xfb, 0x6e, 0xf2, 0x17, 0x7a, 0x5a,
	0x92, 0x6f, 0xf4, 0xe4, 0xa7, 0xd3, 0x03, 0xa0, 0x60, 0xfc, 0xdc, 0x44, 0x1b, 0x49, 0xfe, 0x81,
	0x67, 0x9b, 0x93, 0xe9, 0x99, 0x4a, 0x47, 0x7c, 0x27, 0x6b, 0x5d, 0x80, 0x67, 0xbf, 0xf5, 0x6c,
	0xad, 0xa3, 0xd5, 0x0a, 0x7e, 0xbc, 0xc2, 0x69, 0x77, 0x64, 0xed, 0x99, 0xed, 0xfc, 0xf9, 0x18,
	0x00, 0x00, 0xff, 0xff, 0xea, 0x64, 0x5c, 0x7b, 0x00, 0x03, 0x00, 0x00,
}
