// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commons/dto/commons.proto

package gs_commons_dto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Status struct {
	State                *State   `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_34dae615404885fd, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetState() *State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *Status) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type State struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Ok                   bool     `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_34dae615404885fd, []int{1}
}

func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (m *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(m, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *State) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *State) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type Authorize struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Device               string   `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
	UserAgent            string   `protobuf:"bytes,5,opt,name=userAgent,proto3" json:"userAgent,omitempty"`
	Platform             int64    `protobuf:"varint,6,opt,name=platform,proto3" json:"platform,omitempty"`
	AppId                string   `protobuf:"bytes,7,opt,name=appId,proto3" json:"appId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Authorize) Reset()         { *m = Authorize{} }
func (m *Authorize) String() string { return proto.CompactTextString(m) }
func (*Authorize) ProtoMessage()    {}
func (*Authorize) Descriptor() ([]byte, []int) {
	return fileDescriptor_34dae615404885fd, []int{2}
}

func (m *Authorize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Authorize.Unmarshal(m, b)
}
func (m *Authorize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Authorize.Marshal(b, m, deterministic)
}
func (m *Authorize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Authorize.Merge(m, src)
}
func (m *Authorize) XXX_Size() int {
	return xxx_messageInfo_Authorize.Size(m)
}
func (m *Authorize) XXX_DiscardUnknown() {
	xxx_messageInfo_Authorize.DiscardUnknown(m)
}

var xxx_messageInfo_Authorize proto.InternalMessageInfo

func (m *Authorize) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *Authorize) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Authorize) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Authorize) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *Authorize) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

func (m *Authorize) GetPlatform() int64 {
	if m != nil {
		return m.Platform
	}
	return 0
}

func (m *Authorize) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

type AppSettings struct {
	Enabled              int64    `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppSettings) Reset()         { *m = AppSettings{} }
func (m *AppSettings) String() string { return proto.CompactTextString(m) }
func (*AppSettings) ProtoMessage()    {}
func (*AppSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_34dae615404885fd, []int{3}
}

func (m *AppSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppSettings.Unmarshal(m, b)
}
func (m *AppSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppSettings.Marshal(b, m, deterministic)
}
func (m *AppSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppSettings.Merge(m, src)
}
func (m *AppSettings) XXX_Size() int {
	return xxx_messageInfo_AppSettings.Size(m)
}
func (m *AppSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_AppSettings.DiscardUnknown(m)
}

var xxx_messageInfo_AppSettings proto.InternalMessageInfo

func (m *AppSettings) GetEnabled() int64 {
	if m != nil {
		return m.Enabled
	}
	return 0
}

func init() {
	proto.RegisterType((*Status)(nil), "gs.commons.dto.Status")
	proto.RegisterType((*State)(nil), "gs.commons.dto.State")
	proto.RegisterType((*Authorize)(nil), "gs.commons.dto.Authorize")
	proto.RegisterType((*AppSettings)(nil), "gs.commons.dto.AppSettings")
}

func init() { proto.RegisterFile("commons/dto/commons.proto", fileDescriptor_34dae615404885fd) }

var fileDescriptor_34dae615404885fd = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x41, 0x4e, 0xc3, 0x30,
	0x10, 0x45, 0x95, 0xb4, 0x49, 0x9b, 0xa9, 0xd4, 0x85, 0x05, 0xc8, 0x20, 0x16, 0x55, 0x36, 0x54,
	0x42, 0x4a, 0x25, 0x38, 0x41, 0x17, 0x2c, 0xba, 0x42, 0x4a, 0x4f, 0x90, 0xc6, 0x43, 0xb0, 0xda,
	0x78, 0xac, 0x78, 0xc2, 0x82, 0x8b, 0x71, 0x3d, 0x64, 0x27, 0x29, 0x62, 0x37, 0x6f, 0xfc, 0xff,
	0xb7, 0xbe, 0x0d, 0xf7, 0x35, 0xb5, 0x2d, 0x19, 0xb7, 0x53, 0x4c, 0xbb, 0x71, 0x2e, 0x6c, 0x47,
	0x4c, 0x62, 0xdd, 0xb8, 0x62, 0xda, 0x28, 0xa6, 0xfc, 0x1d, 0xd2, 0x23, 0x57, 0xdc, 0x3b, 0xf1,
	0x0c, 0x89, 0xe3, 0x8a, 0x51, 0x46, 0x9b, 0x68, 0xbb, 0x7a, 0xb9, 0x2d, 0xfe, 0x2b, 0x0b, 0x2f,
	0xc3, 0x72, 0xd0, 0x08, 0x09, 0x8b, 0x9a, 0x0c, 0xa3, 0x61, 0x19, 0x6f, 0xa2, 0x6d, 0x56, 0x4e,
	0x98, 0xbf, 0x41, 0x12, 0x94, 0x42, 0xc0, 0xbc, 0x26, 0x35, 0xc4, 0xcd, 0xca, 0x30, 0x7b, 0x5b,
	0x8b, 0xce, 0x55, 0x0d, 0x4e, 0xb6, 0x11, 0xc5, 0x1a, 0x62, 0x3a, 0xcb, 0xd9, 0x26, 0xda, 0x2e,
	0xcb, 0x98, 0xce, 0xf9, 0x4f, 0x04, 0xd9, 0xbe, 0xe7, 0x4f, 0xea, 0xf4, 0x37, 0x8a, 0x07, 0x58,
	0xd6, 0x17, 0x8d, 0x86, 0x0f, 0x2a, 0xe4, 0x65, 0xe5, 0x95, 0xc5, 0x1d, 0xa4, 0xbd, 0xc3, 0xee,
	0xa0, 0xc6, 0xc8, 0x91, 0x7c, 0xa2, 0xb6, 0x21, 0x31, 0x2b, 0x63, 0x6d, 0xbd, 0x4e, 0xe1, 0x97,
	0xae, 0x51, 0xce, 0x07, 0xdd, 0x40, 0xe2, 0x11, 0x32, 0xef, 0xd8, 0x37, 0xbe, 0x4c, 0x12, 0x8e,
	0xfe, 0x16, 0xfe, 0x66, 0x7b, 0xa9, 0xf8, 0x83, 0xba, 0x56, 0xa6, 0xa1, 0xc9, 0x95, 0xc5, 0x0d,
	0x24, 0x95, 0xb5, 0x07, 0x25, 0x17, 0xc1, 0x35, 0x40, 0xfe, 0x04, 0xab, 0xbd, 0xb5, 0x47, 0x64,
	0xd6, 0xa6, 0x71, 0xbe, 0x32, 0x9a, 0xea, 0x74, 0x41, 0x35, 0xbe, 0xc4, 0x84, 0xa7, 0x34, 0xfc,
	0xc8, 0xeb, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x30, 0x67, 0x68, 0xd8, 0xae, 0x01, 0x00, 0x00,
}
