// Code generated by protoc-gen-go. DO NOT EDIT.
// source: application/pb/inner/status.proto

package gosionsvc_internal_application

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	dto "konekko.me/gosion/commons/dto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetAppClientStatusRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	Redirect             string   `protobuf:"bytes,2,opt,name=redirect,proto3" json:"redirect,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAppClientStatusRequest) Reset()         { *m = GetAppClientStatusRequest{} }
func (m *GetAppClientStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetAppClientStatusRequest) ProtoMessage()    {}
func (*GetAppClientStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68c6123b188f9c9c, []int{0}
}

func (m *GetAppClientStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppClientStatusRequest.Unmarshal(m, b)
}
func (m *GetAppClientStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppClientStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetAppClientStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppClientStatusRequest.Merge(m, src)
}
func (m *GetAppClientStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetAppClientStatusRequest.Size(m)
}
func (m *GetAppClientStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppClientStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppClientStatusRequest proto.InternalMessageInfo

func (m *GetAppClientStatusRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *GetAppClientStatusRequest) GetRedirect() string {
	if m != nil {
		return m.Redirect
	}
	return ""
}

type GetAppClientStatusResponse struct {
	State                *dto.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	AppId                string     `protobuf:"bytes,2,opt,name=appId,proto3" json:"appId,omitempty"`
	AppQuarantine        int64      `protobuf:"varint,3,opt,name=appQuarantine,proto3" json:"appQuarantine,omitempty"`
	ClientPlatform       int64      `protobuf:"varint,4,opt,name=clientPlatform,proto3" json:"clientPlatform,omitempty"`
	ClientEnabled        int64      `protobuf:"varint,5,opt,name=clientEnabled,proto3" json:"clientEnabled,omitempty"`
	Mustsync             bool       `protobuf:"varint,6,opt,name=mustsync,proto3" json:"mustsync,omitempty"`
	Type                 int64      `protobuf:"varint,7,opt,name=type,proto3" json:"type,omitempty"`
	CanRedirect          bool       `protobuf:"varint,8,opt,name=canRedirect,proto3" json:"canRedirect,omitempty"`
	SecretKey            string     `protobuf:"bytes,9,opt,name=secretKey,proto3" json:"secretKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAppClientStatusResponse) Reset()         { *m = GetAppClientStatusResponse{} }
func (m *GetAppClientStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetAppClientStatusResponse) ProtoMessage()    {}
func (*GetAppClientStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68c6123b188f9c9c, []int{1}
}

func (m *GetAppClientStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppClientStatusResponse.Unmarshal(m, b)
}
func (m *GetAppClientStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppClientStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetAppClientStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppClientStatusResponse.Merge(m, src)
}
func (m *GetAppClientStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetAppClientStatusResponse.Size(m)
}
func (m *GetAppClientStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppClientStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppClientStatusResponse proto.InternalMessageInfo

func (m *GetAppClientStatusResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *GetAppClientStatusResponse) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *GetAppClientStatusResponse) GetAppQuarantine() int64 {
	if m != nil {
		return m.AppQuarantine
	}
	return 0
}

func (m *GetAppClientStatusResponse) GetClientPlatform() int64 {
	if m != nil {
		return m.ClientPlatform
	}
	return 0
}

func (m *GetAppClientStatusResponse) GetClientEnabled() int64 {
	if m != nil {
		return m.ClientEnabled
	}
	return 0
}

func (m *GetAppClientStatusResponse) GetMustsync() bool {
	if m != nil {
		return m.Mustsync
	}
	return false
}

func (m *GetAppClientStatusResponse) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *GetAppClientStatusResponse) GetCanRedirect() bool {
	if m != nil {
		return m.CanRedirect
	}
	return false
}

func (m *GetAppClientStatusResponse) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

func init() {
	proto.RegisterType((*GetAppClientStatusRequest)(nil), "gosionsvc.internal.application.GetAppClientStatusRequest")
	proto.RegisterType((*GetAppClientStatusResponse)(nil), "gosionsvc.internal.application.GetAppClientStatusResponse")
}

func init() { proto.RegisterFile("application/pb/inner/status.proto", fileDescriptor_68c6123b188f9c9c) }

var fileDescriptor_68c6123b188f9c9c = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xdb, 0xaa, 0x13, 0x31,
	0x14, 0x65, 0x7a, 0xb3, 0x4d, 0x51, 0x30, 0x28, 0xc4, 0x41, 0x64, 0x2c, 0x22, 0x85, 0x42, 0x06,
	0xea, 0x93, 0xbe, 0x15, 0x11, 0x29, 0xbe, 0xe8, 0xf4, 0x0b, 0xd2, 0xcc, 0xb6, 0x84, 0xce, 0x24,
	0x31, 0xd9, 0x23, 0xf4, 0x1b, 0xfc, 0x0a, 0xbf, 0xe5, 0xfc, 0xd8, 0x61, 0x92, 0x33, 0xbd, 0x9c,
	0xdb, 0xc3, 0x79, 0xcb, 0x5a, 0x59, 0x6b, 0x25, 0xfb, 0x42, 0xde, 0x0b, 0x6b, 0x2b, 0x25, 0x05,
	0x2a, 0xa3, 0x73, 0xbb, 0xcd, 0x95, 0xd6, 0xe0, 0x72, 0x8f, 0x02, 0x1b, 0xcf, 0xad, 0x33, 0x68,
	0xe8, 0xbb, 0x9d, 0xf1, 0xca, 0x68, 0xff, 0x57, 0x72, 0xa5, 0x11, 0x9c, 0x16, 0x15, 0x3f, 0x73,
	0xa5, 0x8b, 0xbd, 0xd1, 0xb0, 0xdf, 0x1b, 0x5e, 0x43, 0x1e, 0xa5, 0xb9, 0x34, 0x75, 0x6d, 0xb4,
	0xcf, 0x4b, 0x34, 0xdd, 0x39, 0x86, 0xcd, 0x36, 0xe4, 0xcd, 0x77, 0xc0, 0x95, 0xb5, 0x5f, 0x2b,
	0x05, 0x1a, 0x37, 0xe1, 0xa1, 0x02, 0xfe, 0x34, 0xe0, 0x91, 0xa6, 0x64, 0x2c, 0x03, 0xbd, 0x2e,
	0x59, 0x92, 0x25, 0xf3, 0x49, 0x71, 0xc4, 0xed, 0x9d, 0x83, 0x52, 0x39, 0x90, 0xc8, 0x7a, 0xf1,
	0xae, 0xc3, 0xb3, 0xab, 0x1e, 0x49, 0xef, 0x4b, 0xf5, 0xd6, 0x68, 0x0f, 0x74, 0x41, 0x86, 0x6d,
	0x41, 0x10, 0x32, 0xa7, 0xcb, 0xd7, 0x7c, 0xe7, 0x79, 0xf7, 0xab, 0x12, 0x0d, 0x6f, 0xe5, 0x50,
	0x44, 0x0d, 0x7d, 0x45, 0x86, 0xc2, 0xda, 0x75, 0x79, 0xf3, 0x48, 0x04, 0xf4, 0x03, 0x79, 0x2e,
	0xac, 0xfd, 0xd5, 0x08, 0x27, 0x34, 0x2a, 0x0d, 0xac, 0x9f, 0x25, 0xf3, 0x7e, 0x71, 0x49, 0xd2,
	0x8f, 0xe4, 0x45, 0xfc, 0xef, 0xcf, 0x4a, 0xe0, 0x6f, 0xe3, 0x6a, 0x36, 0x08, 0xb2, 0x5b, 0x6c,
	0x9b, 0x16, 0x99, 0x6f, 0x5a, 0x6c, 0x2b, 0x28, 0xd9, 0x30, 0xa6, 0x5d, 0x90, 0x6d, 0xc5, 0x75,
	0xe3, 0xd1, 0x1f, 0xb4, 0x64, 0xa3, 0x2c, 0x99, 0x8f, 0x8b, 0x23, 0xa6, 0x94, 0x0c, 0xf0, 0x60,
	0x81, 0x3d, 0x0b, 0xc6, 0x70, 0xa6, 0x19, 0x99, 0x4a, 0xa1, 0x8b, 0xae, 0x49, 0xe3, 0x60, 0x39,
	0xa7, 0xe8, 0x5b, 0x32, 0xf1, 0x20, 0x1d, 0xe0, 0x0f, 0x38, 0xb0, 0x49, 0xa8, 0xef, 0x44, 0x2c,
	0xff, 0x27, 0xe4, 0xe5, 0xea, 0x34, 0xd7, 0xd8, 0x44, 0xfa, 0x2f, 0x21, 0xf4, 0x6e, 0x6f, 0xe9,
	0x67, 0xfe, 0xf8, 0x56, 0xf0, 0x07, 0xa7, 0x9c, 0x7e, 0x79, 0x8a, 0x35, 0x8e, 0x72, 0x3b, 0x0a,
	0x5b, 0xf4, 0xe9, 0x3a, 0x00, 0x00, 0xff, 0xff, 0x1a, 0x2c, 0xc8, 0x49, 0xb7, 0x02, 0x00, 0x00,
}
