// Code generated by protoc-gen-go. DO NOT EDIT.
// source: safety/pb/inner/security.proto

package gosionsvc_internal_safety

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	dto "konekko.me/gosion/commons/dto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_53a408c061af1207, []int{0}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetResponse struct {
	State                *dto.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Current              int64      `protobuf:"varint,2,opt,name=current,proto3" json:"current,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_53a408c061af1207, []int{1}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *GetResponse) GetCurrent() int64 {
	if m != nil {
		return m.Current
	}
	return 0
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "gosionsvc.internal.safety.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "gosionsvc.internal.safety.GetResponse")
}

func init() { proto.RegisterFile("safety/pb/inner/security.proto", fileDescriptor_53a408c061af1207) }

var fileDescriptor_53a408c061af1207 = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8f, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x89, 0xc5, 0xaa, 0xd3, 0xdb, 0x82, 0x12, 0x7b, 0x90, 0x52, 0x54, 0x0a, 0x85, 0x59,
	0xa8, 0x0f, 0x51, 0xbc, 0xa6, 0x7d, 0x00, 0xd3, 0x64, 0x2c, 0x21, 0x66, 0x26, 0xee, 0xcc, 0x0a,
	0x7d, 0x7b, 0x31, 0xdb, 0xe0, 0x49, 0xbc, 0xed, 0xcf, 0x7e, 0xf3, 0xf3, 0x7f, 0xf0, 0xa0, 0xe5,
	0x3b, 0xd9, 0xc9, 0xf7, 0x07, 0xdf, 0x30, 0x53, 0xf0, 0x4a, 0x55, 0x0c, 0x8d, 0x9d, 0xb0, 0x0f,
	0x62, 0xe2, 0xee, 0x8f, 0xa2, 0x8d, 0xb0, 0x7e, 0x55, 0xd8, 0xb0, 0x51, 0xe0, 0xf2, 0x03, 0xd3,
	0xc9, 0x7c, 0xdd, 0x0a, 0x53, 0xdb, 0x0a, 0x76, 0xe4, 0x13, 0xe5, 0x2b, 0xe9, 0x3a, 0x61, 0xf5,
	0xb5, 0xc9, 0xf8, 0x4e, 0x3d, 0xcb, 0x47, 0x80, 0x2d, 0x59, 0x41, 0x9f, 0x91, 0xd4, 0xdc, 0x1d,
	0x4c, 0xa3, 0x52, 0x78, 0xad, 0xf3, 0x6c, 0x91, 0xad, 0x6e, 0x8a, 0x73, 0x5a, 0xee, 0x61, 0x36,
	0x50, 0xda, 0x0b, 0x2b, 0xb9, 0x35, 0x5c, 0xaa, 0x95, 0x46, 0x03, 0x35, 0xdb, 0xdc, 0xe2, 0x51,
	0x71, 0xac, 0xad, 0x4d, 0x70, 0xf7, 0xf3, 0x59, 0x24, 0xc6, 0xe5, 0x70, 0x55, 0xc5, 0x10, 0x88,
	0x2d, 0xbf, 0x58, 0x64, 0xab, 0x49, 0x31, 0xc6, 0xcd, 0x1b, 0x5c, 0xef, 0xce, 0x56, 0x6e, 0x0f,
	0x93, 0x2d, 0x99, 0x7b, 0xc2, 0x3f, 0xbd, 0xf0, 0x77, 0xe7, 0xfc, 0xf9, 0x3f, 0x2c, 0x0d, 0x3d,
	0x4c, 0x07, 0xc9, 0x97, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x60, 0x10, 0xf0, 0xa3, 0x4e, 0x01,
	0x00, 0x00,
}
