// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/pb/grant.proto

package gosionsvc_external_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "konekko.me/gosion/commons/dto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_875be15474041634, []int{0}
}

func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (m *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(m, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

type GrantRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrantRequest) Reset()         { *m = GrantRequest{} }
func (m *GrantRequest) String() string { return proto.CompactTextString(m) }
func (*GrantRequest) ProtoMessage()    {}
func (*GrantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_875be15474041634, []int{1}
}

func (m *GrantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrantRequest.Unmarshal(m, b)
}
func (m *GrantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrantRequest.Marshal(b, m, deterministic)
}
func (m *GrantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrantRequest.Merge(m, src)
}
func (m *GrantRequest) XXX_Size() int {
	return xxx_messageInfo_GrantRequest.Size(m)
}
func (m *GrantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GrantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GrantRequest proto.InternalMessageInfo

func (m *GrantRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func init() {
	proto.RegisterType((*StatusRequest)(nil), "gosionsvc.external.user.StatusRequest")
	proto.RegisterType((*GrantRequest)(nil), "gosionsvc.external.user.GrantRequest")
}

func init() { proto.RegisterFile("user/pb/grant.proto", fileDescriptor_875be15474041634) }

var fileDescriptor_875be15474041634 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2f, 0x48, 0xd2, 0x4f, 0x2f, 0x4a, 0xcc, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x12, 0x4f, 0xcf, 0x2f, 0xce, 0xcc, 0xcf, 0x2b, 0x2e, 0x4b, 0xd6, 0x4b, 0xad, 0x28, 0x49, 0x2d,
	0xca, 0x4b, 0xcc, 0xd1, 0x03, 0xa9, 0x93, 0xd2, 0xce, 0xce, 0xcf, 0x4b, 0xcd, 0xce, 0xce, 0xd7,
	0xcb, 0x4d, 0xd5, 0x87, 0xa8, 0xd1, 0x4f, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0x2b, 0xd6, 0x4f, 0x29,
	0xc9, 0x87, 0xb1, 0x21, 0xa6, 0x28, 0xf1, 0x73, 0xf1, 0x06, 0x97, 0x24, 0x96, 0x94, 0x16, 0x07,
	0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x28, 0x69, 0x71, 0xf1, 0xb8, 0x83, 0x6c, 0x81, 0xf2, 0x85,
	0xa4, 0xb8, 0x38, 0x92, 0x73, 0x32, 0x53, 0xf3, 0x4a, 0x3c, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35,
	0x38, 0x83, 0xe0, 0x7c, 0x23, 0x5f, 0x2e, 0x56, 0xb0, 0x5a, 0x21, 0x17, 0x2e, 0xe6, 0xc8, 0xd4,
	0x62, 0x21, 0x55, 0x3d, 0x1c, 0x6e, 0xd2, 0x43, 0x36, 0x52, 0x4a, 0x4c, 0x2f, 0xbd, 0x58, 0x0f,
	0xe6, 0x8c, 0x94, 0x92, 0x7c, 0x3d, 0x88, 0x0b, 0x92, 0xd8, 0xc0, 0x4e, 0x32, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x55, 0x44, 0x20, 0xc1, 0xef, 0x00, 0x00, 0x00,
}
