// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/pb/invite.proto

package gosionsvc_external_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	dto "konekko.me/gosion/commons/dto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HasInvitedRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HasInvitedRequest) Reset()         { *m = HasInvitedRequest{} }
func (m *HasInvitedRequest) String() string { return proto.CompactTextString(m) }
func (*HasInvitedRequest) ProtoMessage()    {}
func (*HasInvitedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3caf1176bf5393cc, []int{0}
}

func (m *HasInvitedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasInvitedRequest.Unmarshal(m, b)
}
func (m *HasInvitedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasInvitedRequest.Marshal(b, m, deterministic)
}
func (m *HasInvitedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasInvitedRequest.Merge(m, src)
}
func (m *HasInvitedRequest) XXX_Size() int {
	return xxx_messageInfo_HasInvitedRequest.Size(m)
}
func (m *HasInvitedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HasInvitedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HasInvitedRequest proto.InternalMessageInfo

func (m *HasInvitedRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *HasInvitedRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type FindInviteRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindInviteRequest) Reset()         { *m = FindInviteRequest{} }
func (m *FindInviteRequest) String() string { return proto.CompactTextString(m) }
func (*FindInviteRequest) ProtoMessage()    {}
func (*FindInviteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3caf1176bf5393cc, []int{1}
}

func (m *FindInviteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindInviteRequest.Unmarshal(m, b)
}
func (m *FindInviteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindInviteRequest.Marshal(b, m, deterministic)
}
func (m *FindInviteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindInviteRequest.Merge(m, src)
}
func (m *FindInviteRequest) XXX_Size() int {
	return xxx_messageInfo_FindInviteRequest.Size(m)
}
func (m *FindInviteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindInviteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindInviteRequest proto.InternalMessageInfo

func (m *FindInviteRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type FindInviteResponse struct {
	State                *dto.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FindInviteResponse) Reset()         { *m = FindInviteResponse{} }
func (m *FindInviteResponse) String() string { return proto.CompactTextString(m) }
func (*FindInviteResponse) ProtoMessage()    {}
func (*FindInviteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3caf1176bf5393cc, []int{2}
}

func (m *FindInviteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindInviteResponse.Unmarshal(m, b)
}
func (m *FindInviteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindInviteResponse.Marshal(b, m, deterministic)
}
func (m *FindInviteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindInviteResponse.Merge(m, src)
}
func (m *FindInviteResponse) XXX_Size() int {
	return xxx_messageInfo_FindInviteResponse.Size(m)
}
func (m *FindInviteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindInviteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindInviteResponse proto.InternalMessageInfo

func (m *FindInviteResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

type ListRequest struct {
	PageIndex            int64    `protobuf:"varint,1,opt,name=pageIndex,proto3" json:"pageIndex,omitempty"`
	PageSize             int64    `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3caf1176bf5393cc, []int{3}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetPageIndex() int64 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *ListRequest) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type ListResponse struct {
	State                *dto.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3caf1176bf5393cc, []int{4}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

type InviteRequest struct {
	Phone                string        `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string        `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username             string        `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	RealName             string        `protobuf:"bytes,4,opt,name=realName,proto3" json:"realName,omitempty"`
	Items                []*InviteItem `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	ExpiredAt            int64         `protobuf:"varint,6,opt,name=expiredAt,proto3" json:"expiredAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *InviteRequest) Reset()         { *m = InviteRequest{} }
func (m *InviteRequest) String() string { return proto.CompactTextString(m) }
func (*InviteRequest) ProtoMessage()    {}
func (*InviteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3caf1176bf5393cc, []int{5}
}

func (m *InviteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteRequest.Unmarshal(m, b)
}
func (m *InviteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteRequest.Marshal(b, m, deterministic)
}
func (m *InviteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteRequest.Merge(m, src)
}
func (m *InviteRequest) XXX_Size() int {
	return xxx_messageInfo_InviteRequest.Size(m)
}
func (m *InviteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InviteRequest proto.InternalMessageInfo

func (m *InviteRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *InviteRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *InviteRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *InviteRequest) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

func (m *InviteRequest) GetItems() []*InviteItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *InviteRequest) GetExpiredAt() int64 {
	if m != nil {
		return m.ExpiredAt
	}
	return 0
}

type InviteItem struct {
	AppId                string   `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	Roles                []int64  `protobuf:"varint,2,rep,packed,name=roles,proto3" json:"roles,omitempty"`
	BindGroupId          string   `protobuf:"bytes,3,opt,name=bindGroupId,proto3" json:"bindGroupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteItem) Reset()         { *m = InviteItem{} }
func (m *InviteItem) String() string { return proto.CompactTextString(m) }
func (*InviteItem) ProtoMessage()    {}
func (*InviteItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_3caf1176bf5393cc, []int{6}
}

func (m *InviteItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteItem.Unmarshal(m, b)
}
func (m *InviteItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteItem.Marshal(b, m, deterministic)
}
func (m *InviteItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteItem.Merge(m, src)
}
func (m *InviteItem) XXX_Size() int {
	return xxx_messageInfo_InviteItem.Size(m)
}
func (m *InviteItem) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteItem.DiscardUnknown(m)
}

var xxx_messageInfo_InviteItem proto.InternalMessageInfo

func (m *InviteItem) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *InviteItem) GetRoles() []int64 {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *InviteItem) GetBindGroupId() string {
	if m != nil {
		return m.BindGroupId
	}
	return ""
}

func init() {
	proto.RegisterType((*HasInvitedRequest)(nil), "gosionsvc.external.user.HasInvitedRequest")
	proto.RegisterType((*FindInviteRequest)(nil), "gosionsvc.external.user.FindInviteRequest")
	proto.RegisterType((*FindInviteResponse)(nil), "gosionsvc.external.user.FindInviteResponse")
	proto.RegisterType((*ListRequest)(nil), "gosionsvc.external.user.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "gosionsvc.external.user.ListResponse")
	proto.RegisterType((*InviteRequest)(nil), "gosionsvc.external.user.InviteRequest")
	proto.RegisterType((*InviteItem)(nil), "gosionsvc.external.user.InviteItem")
}

func init() { proto.RegisterFile("user/pb/invite.proto", fileDescriptor_3caf1176bf5393cc) }

var fileDescriptor_3caf1176bf5393cc = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x51, 0x8b, 0x13, 0x31,
	0x10, 0xa6, 0xdd, 0xb6, 0x78, 0x53, 0x05, 0x2f, 0x9c, 0xba, 0x2c, 0x3e, 0x94, 0xd5, 0x93, 0x62,
	0x21, 0x0b, 0xf5, 0x49, 0x7c, 0x90, 0x7b, 0xb9, 0xb3, 0x20, 0x22, 0x5b, 0x7c, 0xf1, 0x45, 0xd2,
	0xcb, 0x50, 0x43, 0x77, 0x93, 0x98, 0x64, 0x8f, 0xea, 0x6f, 0xf4, 0x07, 0xf8, 0x73, 0x24, 0x9b,
	0xdd, 0xb6, 0x72, 0xae, 0x55, 0xdf, 0xf2, 0xcd, 0x7c, 0xf3, 0xcd, 0x97, 0x99, 0x04, 0xce, 0x2a,
	0x8b, 0x26, 0xd3, 0xab, 0x4c, 0xc8, 0x1b, 0xe1, 0x90, 0x6a, 0xa3, 0x9c, 0x22, 0x8f, 0xd6, 0xca,
	0x0a, 0x25, 0xed, 0xcd, 0x35, 0xc5, 0xad, 0x43, 0x23, 0x59, 0x41, 0x3d, 0x31, 0x99, 0x6d, 0x94,
	0xc4, 0xcd, 0x46, 0xd1, 0x12, 0xb3, 0xc0, 0xc9, 0xae, 0x55, 0x59, 0x2a, 0x69, 0x33, 0xee, 0x54,
	0x7b, 0x0e, 0x2a, 0xe9, 0x6b, 0x38, 0x7d, 0xc3, 0xec, 0xa2, 0x16, 0xe6, 0x39, 0x7e, 0xa9, 0xd0,
	0x3a, 0x72, 0x06, 0x43, 0xfd, 0x59, 0x49, 0x8c, 0x7b, 0x93, 0xde, 0xf4, 0x24, 0x0f, 0xc0, 0x47,
	0xb1, 0x64, 0xa2, 0x88, 0xfb, 0x21, 0x5a, 0x83, 0xf4, 0x1c, 0x4e, 0x2f, 0x85, 0xe4, 0x41, 0xa1,
	0x15, 0xb8, 0x0f, 0xd1, 0x06, 0xbf, 0x36, 0xe5, 0xfe, 0x98, 0x5e, 0x00, 0x39, 0xa4, 0x59, 0xad,
	0xa4, 0x45, 0x32, 0x83, 0xa1, 0x75, 0xcc, 0x85, 0x46, 0xe3, 0xf9, 0x03, 0xba, 0xb6, 0xb4, 0xf5,
	0xc7, 0x9d, 0xa2, 0x4b, 0x9f, 0xcc, 0x03, 0x27, 0xbd, 0x82, 0xf1, 0x5b, 0x61, 0x5d, 0xdb, 0xe3,
	0x31, 0x9c, 0x68, 0xb6, 0xc6, 0x85, 0xe4, 0xb8, 0xad, 0xeb, 0xa3, 0x7c, 0x1f, 0x20, 0x09, 0xdc,
	0xf1, 0x60, 0x29, 0xbe, 0x61, 0xed, 0x37, 0xca, 0x77, 0x38, 0x7d, 0x05, 0x77, 0x83, 0xd0, 0xff,
	0xb8, 0xf8, 0xde, 0x83, 0x7b, 0xbf, 0x5e, 0xf6, 0x1f, 0xa6, 0xe5, 0x6d, 0xf9, 0x1d, 0x49, 0x56,
	0x62, 0x1c, 0xd5, 0x89, 0x1d, 0xf6, 0x39, 0x83, 0xac, 0x78, 0xe7, 0x73, 0x83, 0x90, 0x6b, 0x31,
	0x79, 0x09, 0x43, 0xe1, 0xb0, 0xb4, 0xf1, 0x70, 0x12, 0x4d, 0xc7, 0xf3, 0x27, 0xb4, 0x63, 0xf9,
	0x34, 0x58, 0x5b, 0x38, 0x2c, 0xf3, 0x50, 0xe1, 0xe7, 0x84, 0x5b, 0x2d, 0x0c, 0xf2, 0x0b, 0x17,
	0x8f, 0xc2, 0x9c, 0x76, 0x81, 0xf4, 0x23, 0xc0, 0xbe, 0xc4, 0x9b, 0x66, 0x5a, 0x2f, 0x78, 0x7b,
	0x95, 0x1a, 0xf8, 0xa8, 0x51, 0x05, 0xda, 0xb8, 0x3f, 0x89, 0xa6, 0x51, 0x1e, 0x00, 0x99, 0xc0,
	0x78, 0x25, 0x24, 0xbf, 0x32, 0xaa, 0xf2, 0x15, 0xe1, 0x36, 0x87, 0xa1, 0xf9, 0x8f, 0x3e, 0x8c,
	0x82, 0x38, 0xb9, 0x84, 0xc1, 0x07, 0x8b, 0x86, 0x3c, 0x3b, 0x62, 0xbc, 0x99, 0x69, 0xf2, 0xf0,
	0x77, 0x3b, 0xa8, 0x2c, 0x59, 0xc2, 0xc0, 0xaf, 0x8e, 0x3c, 0xed, 0xd4, 0x39, 0x78, 0x22, 0xc9,
	0xf9, 0x11, 0x56, 0xb3, 0xff, 0x4f, 0x30, 0xf0, 0x6f, 0x93, 0x3c, 0xef, 0xa4, 0xdf, 0x7a, 0xe1,
	0xc9, 0xec, 0xaf, 0xb8, 0x4d, 0x83, 0xf7, 0x00, 0xfb, 0x4f, 0xf6, 0x87, 0x36, 0xb7, 0x7e, 0x62,
	0xd7, 0x1c, 0x56, 0xa3, 0xfa, 0xf7, 0xbe, 0xf8, 0x19, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x10, 0xb0,
	0x64, 0x1b, 0x04, 0x00, 0x00,
}
