// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/pb/login.proto

package gs_service_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	dto "konekko.me/gosion/commons/dto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EntryRequest struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	ClientId             string   `protobuf:"bytes,3,opt,name=clientId,proto3" json:"clientId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntryRequest) Reset()         { *m = EntryRequest{} }
func (m *EntryRequest) String() string { return proto.CompactTextString(m) }
func (*EntryRequest) ProtoMessage()    {}
func (*EntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f339c1dfa0e14c2b, []int{0}
}

func (m *EntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntryRequest.Unmarshal(m, b)
}
func (m *EntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntryRequest.Marshal(b, m, deterministic)
}
func (m *EntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryRequest.Merge(m, src)
}
func (m *EntryRequest) XXX_Size() int {
	return xxx_messageInfo_EntryRequest.Size(m)
}
func (m *EntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EntryRequest proto.InternalMessageInfo

func (m *EntryRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *EntryRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *EntryRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

type EntryWithAccountResponse struct {
	State                *dto.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	AccessToken          string     `protobuf:"bytes,2,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken         string     `protobuf:"bytes,3,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EntryWithAccountResponse) Reset()         { *m = EntryWithAccountResponse{} }
func (m *EntryWithAccountResponse) String() string { return proto.CompactTextString(m) }
func (*EntryWithAccountResponse) ProtoMessage()    {}
func (*EntryWithAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f339c1dfa0e14c2b, []int{1}
}

func (m *EntryWithAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntryWithAccountResponse.Unmarshal(m, b)
}
func (m *EntryWithAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntryWithAccountResponse.Marshal(b, m, deterministic)
}
func (m *EntryWithAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryWithAccountResponse.Merge(m, src)
}
func (m *EntryWithAccountResponse) XXX_Size() int {
	return xxx_messageInfo_EntryWithAccountResponse.Size(m)
}
func (m *EntryWithAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryWithAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EntryWithAccountResponse proto.InternalMessageInfo

func (m *EntryWithAccountResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *EntryWithAccountResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *EntryWithAccountResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type EntryWithQRCodeRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntryWithQRCodeRequest) Reset()         { *m = EntryWithQRCodeRequest{} }
func (m *EntryWithQRCodeRequest) String() string { return proto.CompactTextString(m) }
func (*EntryWithQRCodeRequest) ProtoMessage()    {}
func (*EntryWithQRCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f339c1dfa0e14c2b, []int{2}
}

func (m *EntryWithQRCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntryWithQRCodeRequest.Unmarshal(m, b)
}
func (m *EntryWithQRCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntryWithQRCodeRequest.Marshal(b, m, deterministic)
}
func (m *EntryWithQRCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryWithQRCodeRequest.Merge(m, src)
}
func (m *EntryWithQRCodeRequest) XXX_Size() int {
	return xxx_messageInfo_EntryWithQRCodeRequest.Size(m)
}
func (m *EntryWithQRCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryWithQRCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EntryWithQRCodeRequest proto.InternalMessageInfo

func (m *EntryWithQRCodeRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

type EntryWithQRCodeResponse struct {
	State                *dto.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Code                 string     `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EntryWithQRCodeResponse) Reset()         { *m = EntryWithQRCodeResponse{} }
func (m *EntryWithQRCodeResponse) String() string { return proto.CompactTextString(m) }
func (*EntryWithQRCodeResponse) ProtoMessage()    {}
func (*EntryWithQRCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f339c1dfa0e14c2b, []int{3}
}

func (m *EntryWithQRCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntryWithQRCodeResponse.Unmarshal(m, b)
}
func (m *EntryWithQRCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntryWithQRCodeResponse.Marshal(b, m, deterministic)
}
func (m *EntryWithQRCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryWithQRCodeResponse.Merge(m, src)
}
func (m *EntryWithQRCodeResponse) XXX_Size() int {
	return xxx_messageInfo_EntryWithQRCodeResponse.Size(m)
}
func (m *EntryWithQRCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryWithQRCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EntryWithQRCodeResponse proto.InternalMessageInfo

func (m *EntryWithQRCodeResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *EntryWithQRCodeResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func init() {
	proto.RegisterType((*EntryRequest)(nil), "gs.service.user.EntryRequest")
	proto.RegisterType((*EntryWithAccountResponse)(nil), "gs.service.user.EntryWithAccountResponse")
	proto.RegisterType((*EntryWithQRCodeRequest)(nil), "gs.service.user.EntryWithQRCodeRequest")
	proto.RegisterType((*EntryWithQRCodeResponse)(nil), "gs.service.user.EntryWithQRCodeResponse")
}

func init() { proto.RegisterFile("user/pb/login.proto", fileDescriptor_f339c1dfa0e14c2b) }

var fileDescriptor_f339c1dfa0e14c2b = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0xdd, 0x4a, 0xf3, 0x40,
	0x10, 0x25, 0xfd, 0xbe, 0x7e, 0x3f, 0xd3, 0x82, 0xb2, 0xa2, 0x86, 0x82, 0x50, 0x72, 0x55, 0x29,
	0x6c, 0xa0, 0xfa, 0x02, 0x22, 0x5e, 0x08, 0xde, 0x18, 0x7f, 0x0a, 0x0a, 0x42, 0xba, 0x19, 0xd3,
	0x90, 0x76, 0xa7, 0x66, 0xa6, 0x82, 0x0f, 0xe1, 0x9d, 0x0f, 0x2c, 0x49, 0x9a, 0x1a, 0x6b, 0x45,
	0x10, 0xef, 0x76, 0xe6, 0xcc, 0xcf, 0x39, 0x73, 0x16, 0xb6, 0xe6, 0x8c, 0x99, 0x3f, 0x1b, 0xf9,
	0x13, 0x8a, 0x13, 0xab, 0x67, 0x19, 0x09, 0xa9, 0x8d, 0x98, 0x35, 0x63, 0xf6, 0x98, 0x18, 0xd4,
	0x39, 0xde, 0xe9, 0xa7, 0x64, 0x31, 0x4d, 0x49, 0x4f, 0xd1, 0x8f, 0x89, 0x13, 0xb2, 0xbe, 0xa1,
	0xe9, 0x94, 0x2c, 0xfb, 0x91, 0x50, 0xf5, 0x2e, 0xbb, 0xbd, 0x3b, 0x68, 0x9f, 0x58, 0xc9, 0x9e,
	0x02, 0x7c, 0x98, 0x23, 0x8b, 0x72, 0xe1, 0xaf, 0x21, 0x2b, 0x68, 0xc5, 0x75, 0xba, 0x4e, 0xef,
	0x7f, 0x50, 0x85, 0x39, 0x12, 0x1a, 0x43, 0x73, 0x2b, 0x6e, 0xa3, 0x44, 0x16, 0xa1, 0xea, 0xc0,
	0x3f, 0x33, 0x49, 0xd0, 0xca, 0x69, 0xe4, 0xfe, 0x2a, 0xa0, 0x65, 0xec, 0x3d, 0x3b, 0xe0, 0x16,
	0x0b, 0x86, 0x89, 0x8c, 0x8f, 0xca, 0x86, 0x00, 0x79, 0x46, 0x96, 0x51, 0xf5, 0xa1, 0xc9, 0x12,
	0x0a, 0x16, 0xab, 0x5a, 0x83, 0x6d, 0x1d, 0xb3, 0xae, 0xe8, 0x45, 0x42, 0xfa, 0x22, 0x07, 0x83,
	0xb2, 0x46, 0x75, 0xa1, 0x15, 0x1a, 0x83, 0xcc, 0x97, 0x94, 0xa2, 0x5d, 0x70, 0xa8, 0xa7, 0x94,
	0x07, 0xed, 0x0c, 0xef, 0x33, 0xe4, 0x71, 0x59, 0x52, 0x72, 0x79, 0x97, 0xf3, 0x0e, 0x61, 0x67,
	0x49, 0xe7, 0x3c, 0x38, 0xa6, 0x08, 0x2b, 0xe5, 0x75, 0x15, 0xce, 0x8a, 0x8a, 0x1b, 0xd8, 0xfd,
	0xd0, 0xf5, 0x1d, 0x0d, 0x0a, 0x7e, 0x1b, 0x8a, 0x70, 0x41, 0xbe, 0x78, 0x0f, 0x5e, 0x1a, 0xd0,
	0x3c, 0xcb, 0xfd, 0x54, 0x43, 0x68, 0xd5, 0xae, 0xa4, 0xf6, 0xf4, 0x8a, 0xb3, 0xba, 0xee, 0x54,
	0x67, 0x7f, 0x3d, 0xbc, 0xee, 0xce, 0x57, 0x00, 0x6f, 0xcc, 0xbf, 0x9a, 0xdb, 0xfb, 0x7c, 0xee,
	0x8a, 0xf4, 0x5b, 0xd8, 0xcc, 0xb3, 0xd7, 0xe1, 0x24, 0x89, 0x42, 0xc1, 0x1f, 0x1d, 0x3e, 0xfa,
	0x53, 0xfc, 0xcf, 0x83, 0xd7, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd7, 0xb6, 0x24, 0x6b, 0xf4, 0x02,
	0x00, 0x00,
}
