// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: user/pb/register.proto

/*
Package xbasissvc_external_user is a generated protocol buffer package.

It is generated from these files:
	user/pb/register.proto

It has these top-level messages:
	NewRequest
*/
package xbasissvc_external_user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import xbasis_commons_dto "konekko.me/xbasis/commons/dto"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = xbasis_commons_dto.Status{}

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Register service

type RegisterService interface {
	New(ctx context.Context, in *NewRequest, opts ...client.CallOption) (*xbasis_commons_dto.Status, error)
}

type registerService struct {
	c    client.Client
	name string
}

func NewRegisterService(name string, c client.Client) RegisterService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "xbasissvc.external.user"
	}
	return &registerService{
		c:    c,
		name: name,
	}
}

func (c *registerService) New(ctx context.Context, in *NewRequest, opts ...client.CallOption) (*xbasis_commons_dto.Status, error) {
	req := c.c.NewRequest(c.name, "Register.New", in)
	out := new(xbasis_commons_dto.Status)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Register service

type RegisterHandler interface {
	New(context.Context, *NewRequest, *xbasis_commons_dto.Status) error
}

func RegisterRegisterHandler(s server.Server, hdlr RegisterHandler, opts ...server.HandlerOption) error {
	type register interface {
		New(ctx context.Context, in *NewRequest, out *xbasis_commons_dto.Status) error
	}
	type Register struct {
		register
	}
	h := &registerHandler{hdlr}
	return s.Handle(s.NewHandler(&Register{h}, opts...))
}

type registerHandler struct {
	RegisterHandler
}

func (h *registerHandler) New(ctx context.Context, in *NewRequest, out *xbasis_commons_dto.Status) error {
	return h.RegisterHandler.New(ctx, in, out)
}
