// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/pb/user.proto

package xbasissvc_external_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	dto "konekko.me/xbasis/commons/dto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SearchRequest struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Page                 int64    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int64    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca9694bbbb4de3af, []int{0}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *SearchRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SearchRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type SearchResponse struct {
	State                *dto.State        `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Data                 []*SimpleUserData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca9694bbbb4de3af, []int{1}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *SearchResponse) GetData() []*SimpleUserData {
	if m != nil {
		return m.Data
	}
	return nil
}

type SimpleUserData struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	RealName             string   `protobuf:"bytes,4,opt,name=realName,proto3" json:"realName,omitempty"`
	UserId               string   `protobuf:"bytes,5,opt,name=userId,proto3" json:"userId,omitempty"`
	Icon                 string   `protobuf:"bytes,6,opt,name=icon,proto3" json:"icon,omitempty"`
	State                int64    `protobuf:"varint,7,opt,name=state,proto3" json:"state,omitempty"`
	Account              string   `protobuf:"bytes,8,opt,name=account,proto3" json:"account,omitempty"`
	Invite               bool     `protobuf:"varint,9,opt,name=invite,proto3" json:"invite,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleUserData) Reset()         { *m = SimpleUserData{} }
func (m *SimpleUserData) String() string { return proto.CompactTextString(m) }
func (*SimpleUserData) ProtoMessage()    {}
func (*SimpleUserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca9694bbbb4de3af, []int{2}
}

func (m *SimpleUserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleUserData.Unmarshal(m, b)
}
func (m *SimpleUserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleUserData.Marshal(b, m, deterministic)
}
func (m *SimpleUserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleUserData.Merge(m, src)
}
func (m *SimpleUserData) XXX_Size() int {
	return xxx_messageInfo_SimpleUserData.Size(m)
}
func (m *SimpleUserData) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleUserData.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleUserData proto.InternalMessageInfo

func (m *SimpleUserData) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SimpleUserData) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *SimpleUserData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SimpleUserData) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

func (m *SimpleUserData) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SimpleUserData) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *SimpleUserData) GetState() int64 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *SimpleUserData) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *SimpleUserData) GetInvite() bool {
	if m != nil {
		return m.Invite
	}
	return false
}

func init() {
	proto.RegisterType((*SearchRequest)(nil), "xbasissvc.external.user.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "xbasissvc.external.user.SearchResponse")
	proto.RegisterType((*SimpleUserData)(nil), "xbasissvc.external.user.SimpleUserData")
}

func init() { proto.RegisterFile("user/pb/user.proto", fileDescriptor_ca9694bbbb4de3af) }

var fileDescriptor_ca9694bbbb4de3af = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x31, 0x4f, 0xf3, 0x30,
	0x14, 0x54, 0x9a, 0x34, 0x6d, 0x5d, 0x7d, 0xd5, 0x27, 0x0b, 0x81, 0xe9, 0x14, 0x75, 0xa0, 0x91,
	0x90, 0x1c, 0xa9, 0x8c, 0xac, 0x2c, 0x2c, 0x0c, 0xa9, 0x18, 0x98, 0x90, 0x9b, 0x3c, 0xd1, 0x28,
	0x89, 0x1d, 0x62, 0xa7, 0x2a, 0x0c, 0xfc, 0x5e, 0x7e, 0x06, 0x7a, 0x76, 0x82, 0x60, 0xa8, 0x98,
	0xfa, 0xee, 0xde, 0xf5, 0xec, 0x3b, 0x87, 0xd0, 0x4e, 0x43, 0x9b, 0x34, 0xbb, 0x04, 0x7f, 0x79,
	0xd3, 0x2a, 0xa3, 0xe8, 0xc5, 0x71, 0x27, 0x74, 0xa1, 0xf5, 0x21, 0xe3, 0x70, 0x34, 0xd0, 0x4a,
	0x51, 0x71, 0x5c, 0x2f, 0xaf, 0x4b, 0x25, 0xa1, 0x2c, 0x15, 0xaf, 0x21, 0x71, 0x9a, 0x24, 0x53,
	0x75, 0xad, 0xa4, 0x4e, 0x72, 0xa3, 0x86, 0xd9, 0xb9, 0xac, 0x9e, 0xc9, 0xbf, 0x2d, 0x88, 0x36,
	0xdb, 0xa7, 0xf0, 0xda, 0x81, 0x36, 0xf4, 0x8c, 0x8c, 0x0f, 0xa2, 0xea, 0x80, 0x79, 0x91, 0x17,
	0xcf, 0x52, 0x07, 0xe8, 0x7f, 0xe2, 0x97, 0xf0, 0xc6, 0x46, 0x96, 0xc3, 0x91, 0x52, 0x12, 0x34,
	0xe2, 0x05, 0x98, 0x1f, 0x79, 0xb1, 0x9f, 0xda, 0x19, 0x39, 0x5d, 0xbc, 0x03, 0x0b, 0x1c, 0x87,
	0xf3, 0xea, 0x83, 0x2c, 0x86, 0x03, 0x74, 0xa3, 0xa4, 0x06, 0x9a, 0x90, 0xb1, 0x36, 0xc2, 0xb8,
	0x13, 0xe6, 0x9b, 0x4b, 0xee, 0x2e, 0xc9, 0x87, 0x8b, 0xe5, 0x46, 0xf1, 0x2d, 0x0a, 0x52, 0xa7,
	0xa3, 0xb7, 0x24, 0xc8, 0x85, 0x11, 0x6c, 0x14, 0xf9, 0xf1, 0x7c, 0xb3, 0xe6, 0x27, 0x82, 0xf3,
	0x6d, 0x51, 0x37, 0x15, 0x3c, 0x6a, 0x68, 0xef, 0x84, 0x11, 0xa9, 0xfd, 0xd3, 0xea, 0xd3, 0x23,
	0x8b, 0xdf, 0x0b, 0xba, 0x24, 0x53, 0xd4, 0x4b, 0x51, 0x0f, 0x29, 0xbf, 0x31, 0xc6, 0x6f, 0xf6,
	0x4a, 0x42, 0x1f, 0xd5, 0x01, 0x64, 0xa1, 0x16, 0x45, 0x65, 0xd3, 0xce, 0x52, 0x07, 0xd0, 0xa7,
	0x05, 0x51, 0x3d, 0xa0, 0x4f, 0xe0, 0x7c, 0x06, 0x4c, 0xcf, 0x49, 0x88, 0x9e, 0xf7, 0x39, 0x1b,
	0xdb, 0x4d, 0x8f, 0xb0, 0xa2, 0x22, 0x53, 0x92, 0x85, 0x96, 0xb5, 0x33, 0xba, 0xbb, 0x42, 0x26,
	0xb6, 0xb7, 0x3e, 0x35, 0x23, 0x13, 0x91, 0x65, 0xaa, 0x93, 0x86, 0x4d, 0xad, 0x78, 0x80, 0xe8,
	0x5d, 0xc8, 0x43, 0x61, 0x80, 0xcd, 0x22, 0x2f, 0x9e, 0xa6, 0x3d, 0xda, 0x08, 0x12, 0x60, 0x46,
	0xfa, 0x44, 0x42, 0x57, 0x39, 0xbd, 0x3a, 0xdd, 0xd5, 0xcf, 0x47, 0x5f, 0xae, 0xff, 0xd4, 0xb9,
	0xb7, 0xdb, 0x85, 0xf6, 0xab, 0xb9, 0xf9, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x0b, 0xa2, 0x39,
	0x91, 0x02, 0x00, 0x00,
}
