// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: pb/extensions.proto

/*
Package xbasissvc_external_workflow is a generated protocol buffer package.

It is generated from these files:
	pb/extensions.proto

It has these top-level messages:
*/
package xbasissvc_external_workflow

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Extensions service

type ExtensionsService interface {
}

type extensionsService struct {
	c    client.Client
	name string
}

func NewExtensionsService(name string, c client.Client) ExtensionsService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "xbasissvc.external.workflow"
	}
	return &extensionsService{
		c:    c,
		name: name,
	}
}

// Server API for Extensions service

type ExtensionsHandler interface {
}

func RegisterExtensionsHandler(s server.Server, hdlr ExtensionsHandler, opts ...server.HandlerOption) error {
	type extensions interface {
	}
	type Extensions struct {
		extensions
	}
	h := &extensionsHandler{hdlr}
	return s.Handle(s.NewHandler(&Extensions{h}, opts...))
}

type extensionsHandler struct {
	ExtensionsHandler
}
