// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/form.proto

package gosionsvc_external_workflow

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	dto "konekko.me/gosion/commons/dto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SearchRequest struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Page                 int64    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int64    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98ec7bac17c170cc, []int{0}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *SearchRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SearchRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type SearchResponse struct {
	State                *dto.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98ec7bac17c170cc, []int{1}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

type CheckFiledValueRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckFiledValueRequest) Reset()         { *m = CheckFiledValueRequest{} }
func (m *CheckFiledValueRequest) String() string { return proto.CompactTextString(m) }
func (*CheckFiledValueRequest) ProtoMessage()    {}
func (*CheckFiledValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98ec7bac17c170cc, []int{2}
}

func (m *CheckFiledValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckFiledValueRequest.Unmarshal(m, b)
}
func (m *CheckFiledValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckFiledValueRequest.Marshal(b, m, deterministic)
}
func (m *CheckFiledValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckFiledValueRequest.Merge(m, src)
}
func (m *CheckFiledValueRequest) XXX_Size() int {
	return xxx_messageInfo_CheckFiledValueRequest.Size(m)
}
func (m *CheckFiledValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckFiledValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckFiledValueRequest proto.InternalMessageInfo

type CheckFieldValueResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckFieldValueResponse) Reset()         { *m = CheckFieldValueResponse{} }
func (m *CheckFieldValueResponse) String() string { return proto.CompactTextString(m) }
func (*CheckFieldValueResponse) ProtoMessage()    {}
func (*CheckFieldValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98ec7bac17c170cc, []int{3}
}

func (m *CheckFieldValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckFieldValueResponse.Unmarshal(m, b)
}
func (m *CheckFieldValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckFieldValueResponse.Marshal(b, m, deterministic)
}
func (m *CheckFieldValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckFieldValueResponse.Merge(m, src)
}
func (m *CheckFieldValueResponse) XXX_Size() int {
	return xxx_messageInfo_CheckFieldValueResponse.Size(m)
}
func (m *CheckFieldValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckFieldValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckFieldValueResponse proto.InternalMessageInfo

type GetAllTypeFieldsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllTypeFieldsRequest) Reset()         { *m = GetAllTypeFieldsRequest{} }
func (m *GetAllTypeFieldsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllTypeFieldsRequest) ProtoMessage()    {}
func (*GetAllTypeFieldsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98ec7bac17c170cc, []int{4}
}

func (m *GetAllTypeFieldsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllTypeFieldsRequest.Unmarshal(m, b)
}
func (m *GetAllTypeFieldsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllTypeFieldsRequest.Marshal(b, m, deterministic)
}
func (m *GetAllTypeFieldsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllTypeFieldsRequest.Merge(m, src)
}
func (m *GetAllTypeFieldsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllTypeFieldsRequest.Size(m)
}
func (m *GetAllTypeFieldsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllTypeFieldsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllTypeFieldsRequest proto.InternalMessageInfo

type GetAllTypeFieldsResponse struct {
	State                *dto.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAllTypeFieldsResponse) Reset()         { *m = GetAllTypeFieldsResponse{} }
func (m *GetAllTypeFieldsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllTypeFieldsResponse) ProtoMessage()    {}
func (*GetAllTypeFieldsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98ec7bac17c170cc, []int{5}
}

func (m *GetAllTypeFieldsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllTypeFieldsResponse.Unmarshal(m, b)
}
func (m *GetAllTypeFieldsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllTypeFieldsResponse.Marshal(b, m, deterministic)
}
func (m *GetAllTypeFieldsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllTypeFieldsResponse.Merge(m, src)
}
func (m *GetAllTypeFieldsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllTypeFieldsResponse.Size(m)
}
func (m *GetAllTypeFieldsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllTypeFieldsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllTypeFieldsResponse proto.InternalMessageInfo

func (m *GetAllTypeFieldsResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

type CreatePlaceholderRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc                 string   `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePlaceholderRequest) Reset()         { *m = CreatePlaceholderRequest{} }
func (m *CreatePlaceholderRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePlaceholderRequest) ProtoMessage()    {}
func (*CreatePlaceholderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98ec7bac17c170cc, []int{6}
}

func (m *CreatePlaceholderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePlaceholderRequest.Unmarshal(m, b)
}
func (m *CreatePlaceholderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePlaceholderRequest.Marshal(b, m, deterministic)
}
func (m *CreatePlaceholderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePlaceholderRequest.Merge(m, src)
}
func (m *CreatePlaceholderRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePlaceholderRequest.Size(m)
}
func (m *CreatePlaceholderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePlaceholderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePlaceholderRequest proto.InternalMessageInfo

func (m *CreatePlaceholderRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CreatePlaceholderRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreatePlaceholderRequest) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type CreatePlaceholderResponse struct {
	State                *dto.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Id                   string     `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreatePlaceholderResponse) Reset()         { *m = CreatePlaceholderResponse{} }
func (m *CreatePlaceholderResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePlaceholderResponse) ProtoMessage()    {}
func (*CreatePlaceholderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98ec7bac17c170cc, []int{7}
}

func (m *CreatePlaceholderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePlaceholderResponse.Unmarshal(m, b)
}
func (m *CreatePlaceholderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePlaceholderResponse.Marshal(b, m, deterministic)
}
func (m *CreatePlaceholderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePlaceholderResponse.Merge(m, src)
}
func (m *CreatePlaceholderResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePlaceholderResponse.Size(m)
}
func (m *CreatePlaceholderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePlaceholderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePlaceholderResponse proto.InternalMessageInfo

func (m *CreatePlaceholderResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *CreatePlaceholderResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeletePlaceholderRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePlaceholderRequest) Reset()         { *m = DeletePlaceholderRequest{} }
func (m *DeletePlaceholderRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePlaceholderRequest) ProtoMessage()    {}
func (*DeletePlaceholderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98ec7bac17c170cc, []int{8}
}

func (m *DeletePlaceholderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePlaceholderRequest.Unmarshal(m, b)
}
func (m *DeletePlaceholderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePlaceholderRequest.Marshal(b, m, deterministic)
}
func (m *DeletePlaceholderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePlaceholderRequest.Merge(m, src)
}
func (m *DeletePlaceholderRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePlaceholderRequest.Size(m)
}
func (m *DeletePlaceholderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePlaceholderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePlaceholderRequest proto.InternalMessageInfo

func (m *DeletePlaceholderRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeletePlaceholderResponse struct {
	State                *dto.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DeletePlaceholderResponse) Reset()         { *m = DeletePlaceholderResponse{} }
func (m *DeletePlaceholderResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePlaceholderResponse) ProtoMessage()    {}
func (*DeletePlaceholderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98ec7bac17c170cc, []int{9}
}

func (m *DeletePlaceholderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePlaceholderResponse.Unmarshal(m, b)
}
func (m *DeletePlaceholderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePlaceholderResponse.Marshal(b, m, deterministic)
}
func (m *DeletePlaceholderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePlaceholderResponse.Merge(m, src)
}
func (m *DeletePlaceholderResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePlaceholderResponse.Size(m)
}
func (m *DeletePlaceholderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePlaceholderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePlaceholderResponse proto.InternalMessageInfo

func (m *DeletePlaceholderResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

type UpdatePlaceholderRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc                 string   `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Key                  string   `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePlaceholderRequest) Reset()         { *m = UpdatePlaceholderRequest{} }
func (m *UpdatePlaceholderRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePlaceholderRequest) ProtoMessage()    {}
func (*UpdatePlaceholderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98ec7bac17c170cc, []int{10}
}

func (m *UpdatePlaceholderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePlaceholderRequest.Unmarshal(m, b)
}
func (m *UpdatePlaceholderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePlaceholderRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePlaceholderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePlaceholderRequest.Merge(m, src)
}
func (m *UpdatePlaceholderRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePlaceholderRequest.Size(m)
}
func (m *UpdatePlaceholderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePlaceholderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePlaceholderRequest proto.InternalMessageInfo

func (m *UpdatePlaceholderRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdatePlaceholderRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdatePlaceholderRequest) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *UpdatePlaceholderRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type UpdatePlaceholderResponse struct {
	State                *dto.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdatePlaceholderResponse) Reset()         { *m = UpdatePlaceholderResponse{} }
func (m *UpdatePlaceholderResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePlaceholderResponse) ProtoMessage()    {}
func (*UpdatePlaceholderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98ec7bac17c170cc, []int{11}
}

func (m *UpdatePlaceholderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePlaceholderResponse.Unmarshal(m, b)
}
func (m *UpdatePlaceholderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePlaceholderResponse.Marshal(b, m, deterministic)
}
func (m *UpdatePlaceholderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePlaceholderResponse.Merge(m, src)
}
func (m *UpdatePlaceholderResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePlaceholderResponse.Size(m)
}
func (m *UpdatePlaceholderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePlaceholderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePlaceholderResponse proto.InternalMessageInfo

func (m *UpdatePlaceholderResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

type AddFieldRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Label                string   `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Type                 int64    `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFieldRequest) Reset()         { *m = AddFieldRequest{} }
func (m *AddFieldRequest) String() string { return proto.CompactTextString(m) }
func (*AddFieldRequest) ProtoMessage()    {}
func (*AddFieldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98ec7bac17c170cc, []int{12}
}

func (m *AddFieldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFieldRequest.Unmarshal(m, b)
}
func (m *AddFieldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFieldRequest.Marshal(b, m, deterministic)
}
func (m *AddFieldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFieldRequest.Merge(m, src)
}
func (m *AddFieldRequest) XXX_Size() int {
	return xxx_messageInfo_AddFieldRequest.Size(m)
}
func (m *AddFieldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFieldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddFieldRequest proto.InternalMessageInfo

func (m *AddFieldRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddFieldRequest) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *AddFieldRequest) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *AddFieldRequest) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

type AddFieldResponse struct {
	State                *dto.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AddFieldResponse) Reset()         { *m = AddFieldResponse{} }
func (m *AddFieldResponse) String() string { return proto.CompactTextString(m) }
func (*AddFieldResponse) ProtoMessage()    {}
func (*AddFieldResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98ec7bac17c170cc, []int{13}
}

func (m *AddFieldResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFieldResponse.Unmarshal(m, b)
}
func (m *AddFieldResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFieldResponse.Marshal(b, m, deterministic)
}
func (m *AddFieldResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFieldResponse.Merge(m, src)
}
func (m *AddFieldResponse) XXX_Size() int {
	return xxx_messageInfo_AddFieldResponse.Size(m)
}
func (m *AddFieldResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFieldResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddFieldResponse proto.InternalMessageInfo

func (m *AddFieldResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

type RemoveFieldRequest struct {
	PhId                 string   `protobuf:"bytes,1,opt,name=phId,proto3" json:"phId,omitempty"`
	FieldId              string   `protobuf:"bytes,2,opt,name=fieldId,proto3" json:"fieldId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFieldRequest) Reset()         { *m = RemoveFieldRequest{} }
func (m *RemoveFieldRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveFieldRequest) ProtoMessage()    {}
func (*RemoveFieldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98ec7bac17c170cc, []int{14}
}

func (m *RemoveFieldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFieldRequest.Unmarshal(m, b)
}
func (m *RemoveFieldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFieldRequest.Marshal(b, m, deterministic)
}
func (m *RemoveFieldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFieldRequest.Merge(m, src)
}
func (m *RemoveFieldRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveFieldRequest.Size(m)
}
func (m *RemoveFieldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFieldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFieldRequest proto.InternalMessageInfo

func (m *RemoveFieldRequest) GetPhId() string {
	if m != nil {
		return m.PhId
	}
	return ""
}

func (m *RemoveFieldRequest) GetFieldId() string {
	if m != nil {
		return m.FieldId
	}
	return ""
}

type RemoveFieldResponse struct {
	State                *dto.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RemoveFieldResponse) Reset()         { *m = RemoveFieldResponse{} }
func (m *RemoveFieldResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveFieldResponse) ProtoMessage()    {}
func (*RemoveFieldResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98ec7bac17c170cc, []int{15}
}

func (m *RemoveFieldResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFieldResponse.Unmarshal(m, b)
}
func (m *RemoveFieldResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFieldResponse.Marshal(b, m, deterministic)
}
func (m *RemoveFieldResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFieldResponse.Merge(m, src)
}
func (m *RemoveFieldResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveFieldResponse.Size(m)
}
func (m *RemoveFieldResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFieldResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFieldResponse proto.InternalMessageInfo

func (m *RemoveFieldResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

type UpdateFieldPropsRequest struct {
	PhId                 string   `protobuf:"bytes,1,opt,name=phId,proto3" json:"phId,omitempty"`
	FieldId              string   `protobuf:"bytes,2,opt,name=fieldId,proto3" json:"fieldId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFieldPropsRequest) Reset()         { *m = UpdateFieldPropsRequest{} }
func (m *UpdateFieldPropsRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateFieldPropsRequest) ProtoMessage()    {}
func (*UpdateFieldPropsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98ec7bac17c170cc, []int{16}
}

func (m *UpdateFieldPropsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFieldPropsRequest.Unmarshal(m, b)
}
func (m *UpdateFieldPropsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFieldPropsRequest.Marshal(b, m, deterministic)
}
func (m *UpdateFieldPropsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFieldPropsRequest.Merge(m, src)
}
func (m *UpdateFieldPropsRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateFieldPropsRequest.Size(m)
}
func (m *UpdateFieldPropsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFieldPropsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFieldPropsRequest proto.InternalMessageInfo

func (m *UpdateFieldPropsRequest) GetPhId() string {
	if m != nil {
		return m.PhId
	}
	return ""
}

func (m *UpdateFieldPropsRequest) GetFieldId() string {
	if m != nil {
		return m.FieldId
	}
	return ""
}

type UpdateFieldPropsResponse struct {
	State                *dto.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateFieldPropsResponse) Reset()         { *m = UpdateFieldPropsResponse{} }
func (m *UpdateFieldPropsResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateFieldPropsResponse) ProtoMessage()    {}
func (*UpdateFieldPropsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98ec7bac17c170cc, []int{17}
}

func (m *UpdateFieldPropsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFieldPropsResponse.Unmarshal(m, b)
}
func (m *UpdateFieldPropsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFieldPropsResponse.Marshal(b, m, deterministic)
}
func (m *UpdateFieldPropsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFieldPropsResponse.Merge(m, src)
}
func (m *UpdateFieldPropsResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateFieldPropsResponse.Size(m)
}
func (m *UpdateFieldPropsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFieldPropsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFieldPropsResponse proto.InternalMessageInfo

func (m *UpdateFieldPropsResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

func init() {
	proto.RegisterType((*SearchRequest)(nil), "gosionsvc.external.workflow.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "gosionsvc.external.workflow.SearchResponse")
	proto.RegisterType((*CheckFiledValueRequest)(nil), "gosionsvc.external.workflow.CheckFiledValueRequest")
	proto.RegisterType((*CheckFieldValueResponse)(nil), "gosionsvc.external.workflow.CheckFieldValueResponse")
	proto.RegisterType((*GetAllTypeFieldsRequest)(nil), "gosionsvc.external.workflow.GetAllTypeFieldsRequest")
	proto.RegisterType((*GetAllTypeFieldsResponse)(nil), "gosionsvc.external.workflow.GetAllTypeFieldsResponse")
	proto.RegisterType((*CreatePlaceholderRequest)(nil), "gosionsvc.external.workflow.CreatePlaceholderRequest")
	proto.RegisterType((*CreatePlaceholderResponse)(nil), "gosionsvc.external.workflow.CreatePlaceholderResponse")
	proto.RegisterType((*DeletePlaceholderRequest)(nil), "gosionsvc.external.workflow.DeletePlaceholderRequest")
	proto.RegisterType((*DeletePlaceholderResponse)(nil), "gosionsvc.external.workflow.DeletePlaceholderResponse")
	proto.RegisterType((*UpdatePlaceholderRequest)(nil), "gosionsvc.external.workflow.UpdatePlaceholderRequest")
	proto.RegisterType((*UpdatePlaceholderResponse)(nil), "gosionsvc.external.workflow.UpdatePlaceholderResponse")
	proto.RegisterType((*AddFieldRequest)(nil), "gosionsvc.external.workflow.AddFieldRequest")
	proto.RegisterType((*AddFieldResponse)(nil), "gosionsvc.external.workflow.AddFieldResponse")
	proto.RegisterType((*RemoveFieldRequest)(nil), "gosionsvc.external.workflow.RemoveFieldRequest")
	proto.RegisterType((*RemoveFieldResponse)(nil), "gosionsvc.external.workflow.RemoveFieldResponse")
	proto.RegisterType((*UpdateFieldPropsRequest)(nil), "gosionsvc.external.workflow.UpdateFieldPropsRequest")
	proto.RegisterType((*UpdateFieldPropsResponse)(nil), "gosionsvc.external.workflow.UpdateFieldPropsResponse")
}

func init() { proto.RegisterFile("pb/form.proto", fileDescriptor_98ec7bac17c170cc) }

var fileDescriptor_98ec7bac17c170cc = []byte{
	// 631 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x96, 0x5b, 0x4f, 0xd4, 0x40,
	0x14, 0xc7, 0xd3, 0x65, 0x41, 0x38, 0x84, 0x8b, 0x23, 0x4a, 0xa9, 0x2f, 0xa4, 0x4f, 0x04, 0xb4,
	0x6b, 0xb8, 0xf8, 0x66, 0x0c, 0x60, 0x58, 0x79, 0x23, 0x05, 0x8d, 0x6f, 0xa6, 0xb4, 0x87, 0xdd,
	0x4d, 0xa7, 0x9d, 0xda, 0x29, 0x20, 0xc6, 0xc4, 0xc4, 0xaf, 0xe8, 0x17, 0x32, 0xd3, 0xe9, 0x2c,
	0xbb, 0xbd, 0x6c, 0x4b, 0xdf, 0x4e, 0x67, 0xce, 0x99, 0xf3, 0xcb, 0x3f, 0xf3, 0xef, 0x19, 0x58,
	0x89, 0xae, 0x7b, 0x37, 0x2c, 0x0e, 0xac, 0x28, 0x66, 0x09, 0x23, 0xaf, 0x07, 0x8c, 0x8f, 0x58,
	0xc8, 0xef, 0x5c, 0x0b, 0x7f, 0x26, 0x18, 0x87, 0x0e, 0xb5, 0xee, 0x59, 0xec, 0xdf, 0x50, 0x76,
	0x6f, 0xec, 0xf9, 0x2c, 0x44, 0xdf, 0x67, 0x56, 0x80, 0x3d, 0x99, 0xd7, 0x73, 0x59, 0x10, 0xb0,
	0x90, 0xf7, 0xbc, 0x84, 0xa9, 0x58, 0x9e, 0x64, 0x7e, 0x87, 0x95, 0x4b, 0x74, 0x62, 0x77, 0x68,
	0xe3, 0x8f, 0x5b, 0xe4, 0x09, 0xd9, 0x80, 0xf9, 0x3b, 0x87, 0xde, 0xa2, 0xae, 0x6d, 0x6b, 0x3b,
	0x4b, 0xb6, 0xfc, 0x20, 0xeb, 0x30, 0xe7, 0xe3, 0x83, 0xde, 0x49, 0xd7, 0x44, 0x48, 0x08, 0x74,
	0x23, 0x67, 0x80, 0xfa, 0xdc, 0xb6, 0xb6, 0x33, 0x67, 0xa7, 0xb1, 0x58, 0xe3, 0xa3, 0x5f, 0xa8,
	0x77, 0xe5, 0x9a, 0x88, 0xcd, 0x0f, 0xb0, 0xaa, 0x1a, 0xf0, 0x88, 0x85, 0x1c, 0xc9, 0x1e, 0xcc,
	0xf3, 0xc4, 0x49, 0x64, 0x87, 0xe5, 0xfd, 0x97, 0xd6, 0x80, 0x5b, 0x0a, 0xca, 0x4b, 0x98, 0x75,
	0x29, 0x36, 0x6d, 0x99, 0x63, 0xea, 0xf0, 0xea, 0x74, 0x88, 0xae, 0x7f, 0x36, 0xa2, 0xe8, 0x7d,
	0x15, 0x2c, 0x19, 0xa8, 0xb9, 0x05, 0x9b, 0xd9, 0x0e, 0x52, 0xb5, 0x23, 0x3b, 0x88, 0xad, 0x3e,
	0x26, 0xc7, 0x94, 0x5e, 0x3d, 0x44, 0x98, 0xee, 0x73, 0x55, 0xd5, 0x07, 0xbd, 0xb8, 0xd5, 0x06,
	0xec, 0x0a, 0xf4, 0xd3, 0x18, 0x9d, 0x04, 0x2f, 0xa8, 0xe3, 0xe2, 0x90, 0x51, 0x0f, 0x63, 0xa5,
	0x61, 0xa6, 0x96, 0x36, 0xa5, 0x56, 0xe8, 0x04, 0x98, 0x09, 0x98, 0xc6, 0x62, 0xcd, 0x43, 0xee,
	0xa6, 0x0a, 0x2e, 0xd9, 0x69, 0x6c, 0x7e, 0x83, 0xad, 0x92, 0x53, 0x5b, 0xf0, 0x91, 0x55, 0xe8,
	0x8c, 0xbc, 0xac, 0x5f, 0x67, 0xe4, 0x99, 0xbb, 0xa0, 0x7f, 0x42, 0x8a, 0xa5, 0xbc, 0x32, 0x57,
	0x1b, 0xe7, 0x7e, 0x86, 0xad, 0x92, 0xdc, 0x36, 0x2a, 0x79, 0xa0, 0x7f, 0x89, 0x3c, 0xa7, 0x49,
	0xd7, 0xa6, 0x1a, 0x29, 0x75, 0xbb, 0x63, 0x75, 0x05, 0x6f, 0x49, 0x97, 0x36, 0xbc, 0x2e, 0xac,
	0x1d, 0x7b, 0x5e, 0x7a, 0x2f, 0x14, 0xa6, 0xc2, 0xd2, 0x4a, 0xb0, 0x3a, 0x13, 0x58, 0x1b, 0x30,
	0x4f, 0x9d, 0x6b, 0xa4, 0x19, 0xab, 0xfc, 0x10, 0x99, 0xc9, 0x43, 0x34, 0xb6, 0x84, 0x88, 0xcd,
	0x8f, 0xb0, 0xfe, 0xd8, 0xa4, 0x0d, 0xe5, 0x09, 0x10, 0x1b, 0x03, 0x76, 0x87, 0x79, 0xd0, 0x68,
	0x78, 0xae, 0x14, 0x4d, 0x63, 0xa2, 0xc3, 0xb3, 0x1b, 0x91, 0x73, 0xae, 0xae, 0x82, 0xfa, 0x34,
	0x4f, 0xe0, 0xc5, 0xd4, 0x19, 0x6d, 0x38, 0xfa, 0xb0, 0x29, 0x75, 0x4f, 0xcf, 0xb8, 0x88, 0x59,
	0xc4, 0xdb, 0xc1, 0xf4, 0xd5, 0x35, 0x99, 0x3c, 0xa8, 0x05, 0xd1, 0xfe, 0xbf, 0x45, 0xe8, 0x9e,
	0xb1, 0x38, 0x20, 0x7f, 0x35, 0x78, 0x5e, 0x70, 0x12, 0x39, 0xb2, 0x66, 0xfc, 0x38, 0xad, 0x2a,
	0x3f, 0x1b, 0xef, 0x9f, 0x5a, 0x96, 0xa1, 0x0b, 0x88, 0x82, 0x91, 0x6a, 0x20, 0xaa, 0x4c, 0x5a,
	0x03, 0x51, 0xed, 0x57, 0x01, 0x51, 0x70, 0x47, 0x0d, 0x44, 0x95, 0x67, 0x6b, 0x20, 0xaa, 0x4d,
	0x38, 0x80, 0x45, 0x75, 0xe5, 0xc9, 0x9b, 0x99, 0x67, 0xe4, 0xec, 0x67, 0xbc, 0x6d, 0x98, 0x9d,
	0x35, 0x8a, 0x60, 0x79, 0xe2, 0x5a, 0x93, 0xde, 0xcc, 0xea, 0xa2, 0x89, 0x8c, 0x77, 0xcd, 0x0b,
	0xb2, 0x8e, 0x7f, 0x60, 0x3d, 0x7f, 0x77, 0xc9, 0x61, 0x03, 0x99, 0x0a, 0x9e, 0x31, 0x8e, 0x9e,
	0x58, 0xf5, 0x08, 0x90, 0x1f, 0x69, 0x35, 0x00, 0x15, 0xc3, 0xb1, 0x06, 0xa0, 0x72, 0x6e, 0xfe,
	0x86, 0xb5, 0xdc, 0x8c, 0x26, 0x07, 0xb3, 0x1d, 0x53, 0x3a, 0xd1, 0x8d, 0xc3, 0x26, 0x45, 0xf9,
	0x61, 0x4f, 0x1c, 0x58, 0x90, 0x0f, 0x0c, 0xb2, 0x3b, 0xb3, 0x7e, 0xea, 0x99, 0x63, 0xec, 0x35,
	0xca, 0x95, 0x2d, 0xae, 0x17, 0xd2, 0xb7, 0xd2, 0xc1, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6f,
	0x15, 0x78, 0x27, 0x86, 0x09, 0x00, 0x00,
}
