// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/process.proto

package gs_service_workflow

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	dto "konekko.me/gosion/commons/dto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DetailRequest struct {
	ProcessId            string   `protobuf:"bytes,1,opt,name=processId,proto3" json:"processId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailRequest) Reset()         { *m = DetailRequest{} }
func (m *DetailRequest) String() string { return proto.CompactTextString(m) }
func (*DetailRequest) ProtoMessage()    {}
func (*DetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7499dfaf74a17214, []int{0}
}

func (m *DetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailRequest.Unmarshal(m, b)
}
func (m *DetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailRequest.Marshal(b, m, deterministic)
}
func (m *DetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailRequest.Merge(m, src)
}
func (m *DetailRequest) XXX_Size() int {
	return xxx_messageInfo_DetailRequest.Size(m)
}
func (m *DetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DetailRequest proto.InternalMessageInfo

func (m *DetailRequest) GetProcessId() string {
	if m != nil {
		return m.ProcessId
	}
	return ""
}

type DetailResponse struct {
	State                *dto.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DetailResponse) Reset()         { *m = DetailResponse{} }
func (m *DetailResponse) String() string { return proto.CompactTextString(m) }
func (*DetailResponse) ProtoMessage()    {}
func (*DetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7499dfaf74a17214, []int{1}
}

func (m *DetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailResponse.Unmarshal(m, b)
}
func (m *DetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailResponse.Marshal(b, m, deterministic)
}
func (m *DetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailResponse.Merge(m, src)
}
func (m *DetailResponse) XXX_Size() int {
	return xxx_messageInfo_DetailResponse.Size(m)
}
func (m *DetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DetailResponse proto.InternalMessageInfo

func (m *DetailResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

type GetImageRequest struct {
	ProcessId            string   `protobuf:"bytes,1,opt,name=processId,proto3" json:"processId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetImageRequest) Reset()         { *m = GetImageRequest{} }
func (m *GetImageRequest) String() string { return proto.CompactTextString(m) }
func (*GetImageRequest) ProtoMessage()    {}
func (*GetImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7499dfaf74a17214, []int{2}
}

func (m *GetImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetImageRequest.Unmarshal(m, b)
}
func (m *GetImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetImageRequest.Marshal(b, m, deterministic)
}
func (m *GetImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetImageRequest.Merge(m, src)
}
func (m *GetImageRequest) XXX_Size() int {
	return xxx_messageInfo_GetImageRequest.Size(m)
}
func (m *GetImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetImageRequest proto.InternalMessageInfo

func (m *GetImageRequest) GetProcessId() string {
	if m != nil {
		return m.ProcessId
	}
	return ""
}

type GetImageResponse struct {
	State                *dto.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Url                  string     `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetImageResponse) Reset()         { *m = GetImageResponse{} }
func (m *GetImageResponse) String() string { return proto.CompactTextString(m) }
func (*GetImageResponse) ProtoMessage()    {}
func (*GetImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7499dfaf74a17214, []int{3}
}

func (m *GetImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetImageResponse.Unmarshal(m, b)
}
func (m *GetImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetImageResponse.Marshal(b, m, deterministic)
}
func (m *GetImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetImageResponse.Merge(m, src)
}
func (m *GetImageResponse) XXX_Size() int {
	return xxx_messageInfo_GetImageResponse.Size(m)
}
func (m *GetImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetImageResponse proto.InternalMessageInfo

func (m *GetImageResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *GetImageResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type CreateRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc                 string   `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	AppId                string   `protobuf:"bytes,4,opt,name=appId,proto3" json:"appId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7499dfaf74a17214, []int{4}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRequest) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *CreateRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

type CreateResponse struct {
	State                *dto.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	ProcessId            string     `protobuf:"bytes,2,opt,name=processId,proto3" json:"processId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7499dfaf74a17214, []int{5}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *CreateResponse) GetProcessId() string {
	if m != nil {
		return m.ProcessId
	}
	return ""
}

type BuildRequest struct {
	ProcessId            string   `protobuf:"bytes,1,opt,name=processId,proto3" json:"processId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildRequest) Reset()         { *m = BuildRequest{} }
func (m *BuildRequest) String() string { return proto.CompactTextString(m) }
func (*BuildRequest) ProtoMessage()    {}
func (*BuildRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7499dfaf74a17214, []int{6}
}

func (m *BuildRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildRequest.Unmarshal(m, b)
}
func (m *BuildRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildRequest.Marshal(b, m, deterministic)
}
func (m *BuildRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildRequest.Merge(m, src)
}
func (m *BuildRequest) XXX_Size() int {
	return xxx_messageInfo_BuildRequest.Size(m)
}
func (m *BuildRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BuildRequest proto.InternalMessageInfo

func (m *BuildRequest) GetProcessId() string {
	if m != nil {
		return m.ProcessId
	}
	return ""
}

type BuildResponse struct {
	State                *dto.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BuildResponse) Reset()         { *m = BuildResponse{} }
func (m *BuildResponse) String() string { return proto.CompactTextString(m) }
func (*BuildResponse) ProtoMessage()    {}
func (*BuildResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7499dfaf74a17214, []int{7}
}

func (m *BuildResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildResponse.Unmarshal(m, b)
}
func (m *BuildResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildResponse.Marshal(b, m, deterministic)
}
func (m *BuildResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildResponse.Merge(m, src)
}
func (m *BuildResponse) XXX_Size() int {
	return xxx_messageInfo_BuildResponse.Size(m)
}
func (m *BuildResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BuildResponse proto.InternalMessageInfo

func (m *BuildResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

type DeleteRequest struct {
	ProcessId            string   `protobuf:"bytes,1,opt,name=processId,proto3" json:"processId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7499dfaf74a17214, []int{8}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetProcessId() string {
	if m != nil {
		return m.ProcessId
	}
	return ""
}

type DeleteResponse struct {
	State                *dto.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7499dfaf74a17214, []int{9}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

type UpdateRequest struct {
	ProcessId            string   `protobuf:"bytes,1,opt,name=processId,proto3" json:"processId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc                 string   `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7499dfaf74a17214, []int{10}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetProcessId() string {
	if m != nil {
		return m.ProcessId
	}
	return ""
}

func (m *UpdateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateRequest) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type UpdateResponse struct {
	State                *dto.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7499dfaf74a17214, []int{11}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

type OpenRequest struct {
	ProcessId            string   `protobuf:"bytes,1,opt,name=processId,proto3" json:"processId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenRequest) Reset()         { *m = OpenRequest{} }
func (m *OpenRequest) String() string { return proto.CompactTextString(m) }
func (*OpenRequest) ProtoMessage()    {}
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7499dfaf74a17214, []int{12}
}

func (m *OpenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenRequest.Unmarshal(m, b)
}
func (m *OpenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenRequest.Marshal(b, m, deterministic)
}
func (m *OpenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenRequest.Merge(m, src)
}
func (m *OpenRequest) XXX_Size() int {
	return xxx_messageInfo_OpenRequest.Size(m)
}
func (m *OpenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpenRequest proto.InternalMessageInfo

func (m *OpenRequest) GetProcessId() string {
	if m != nil {
		return m.ProcessId
	}
	return ""
}

type OpenResponse struct {
	State                *dto.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *OpenResponse) Reset()         { *m = OpenResponse{} }
func (m *OpenResponse) String() string { return proto.CompactTextString(m) }
func (*OpenResponse) ProtoMessage()    {}
func (*OpenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7499dfaf74a17214, []int{13}
}

func (m *OpenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenResponse.Unmarshal(m, b)
}
func (m *OpenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenResponse.Marshal(b, m, deterministic)
}
func (m *OpenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenResponse.Merge(m, src)
}
func (m *OpenResponse) XXX_Size() int {
	return xxx_messageInfo_OpenResponse.Size(m)
}
func (m *OpenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OpenResponse proto.InternalMessageInfo

func (m *OpenResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

type LaunchRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LaunchRequest) Reset()         { *m = LaunchRequest{} }
func (m *LaunchRequest) String() string { return proto.CompactTextString(m) }
func (*LaunchRequest) ProtoMessage()    {}
func (*LaunchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7499dfaf74a17214, []int{14}
}

func (m *LaunchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LaunchRequest.Unmarshal(m, b)
}
func (m *LaunchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LaunchRequest.Marshal(b, m, deterministic)
}
func (m *LaunchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LaunchRequest.Merge(m, src)
}
func (m *LaunchRequest) XXX_Size() int {
	return xxx_messageInfo_LaunchRequest.Size(m)
}
func (m *LaunchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LaunchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LaunchRequest proto.InternalMessageInfo

func (m *LaunchRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type LaunchResponse struct {
	State                *dto.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LaunchResponse) Reset()         { *m = LaunchResponse{} }
func (m *LaunchResponse) String() string { return proto.CompactTextString(m) }
func (*LaunchResponse) ProtoMessage()    {}
func (*LaunchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7499dfaf74a17214, []int{15}
}

func (m *LaunchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LaunchResponse.Unmarshal(m, b)
}
func (m *LaunchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LaunchResponse.Marshal(b, m, deterministic)
}
func (m *LaunchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LaunchResponse.Merge(m, src)
}
func (m *LaunchResponse) XXX_Size() int {
	return xxx_messageInfo_LaunchResponse.Size(m)
}
func (m *LaunchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LaunchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LaunchResponse proto.InternalMessageInfo

func (m *LaunchResponse) GetState() *dto.State {
	if m != nil {
		return m.State
	}
	return nil
}

func init() {
	proto.RegisterType((*DetailRequest)(nil), "gs.service.workflow.DetailRequest")
	proto.RegisterType((*DetailResponse)(nil), "gs.service.workflow.DetailResponse")
	proto.RegisterType((*GetImageRequest)(nil), "gs.service.workflow.GetImageRequest")
	proto.RegisterType((*GetImageResponse)(nil), "gs.service.workflow.GetImageResponse")
	proto.RegisterType((*CreateRequest)(nil), "gs.service.workflow.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "gs.service.workflow.CreateResponse")
	proto.RegisterType((*BuildRequest)(nil), "gs.service.workflow.BuildRequest")
	proto.RegisterType((*BuildResponse)(nil), "gs.service.workflow.BuildResponse")
	proto.RegisterType((*DeleteRequest)(nil), "gs.service.workflow.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "gs.service.workflow.DeleteResponse")
	proto.RegisterType((*UpdateRequest)(nil), "gs.service.workflow.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "gs.service.workflow.UpdateResponse")
	proto.RegisterType((*OpenRequest)(nil), "gs.service.workflow.OpenRequest")
	proto.RegisterType((*OpenResponse)(nil), "gs.service.workflow.OpenResponse")
	proto.RegisterType((*LaunchRequest)(nil), "gs.service.workflow.LaunchRequest")
	proto.RegisterType((*LaunchResponse)(nil), "gs.service.workflow.LaunchResponse")
}

func init() { proto.RegisterFile("pb/process.proto", fileDescriptor_7499dfaf74a17214) }

var fileDescriptor_7499dfaf74a17214 = []byte{
	// 490 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x5d, 0x8b, 0xd3, 0x40,
	0x14, 0x65, 0xb7, 0x1f, 0xba, 0x77, 0x37, 0x6b, 0x19, 0x15, 0x4a, 0xf0, 0x61, 0x1b, 0x15, 0x84,
	0xea, 0x04, 0xd6, 0x47, 0xf5, 0x45, 0x05, 0x29, 0x8a, 0xda, 0xca, 0xe2, 0x83, 0x0f, 0x92, 0x4d,
	0xae, 0x35, 0xe4, 0x63, 0xc6, 0xcc, 0xc4, 0xe2, 0x9f, 0xf1, 0xb7, 0xca, 0x64, 0x12, 0x9a, 0x84,
	0x4c, 0xcd, 0xe6, 0xed, 0x76, 0x7a, 0xe6, 0x9c, 0x33, 0x77, 0xce, 0xdc, 0xc0, 0x8c, 0x5f, 0xbb,
	0x3c, 0x63, 0x3e, 0x0a, 0x41, 0x79, 0xc6, 0x24, 0x23, 0x77, 0xb7, 0x82, 0x0a, 0xcc, 0x7e, 0x87,
	0x3e, 0xd2, 0x1d, 0xcb, 0xa2, 0x1f, 0x31, 0xdb, 0xd9, 0xcb, 0x88, 0xa5, 0x18, 0x45, 0x8c, 0x26,
	0xe8, 0x6e, 0x99, 0x08, 0x59, 0xea, 0xfa, 0x2c, 0x49, 0x58, 0x2a, 0xdc, 0x40, 0xb2, 0xaa, 0xd6,
	0x0c, 0xce, 0x33, 0xb0, 0xde, 0xa2, 0xf4, 0xc2, 0x78, 0x83, 0xbf, 0x72, 0x14, 0x92, 0x3c, 0x80,
	0x93, 0x52, 0x63, 0x15, 0xcc, 0x8f, 0x2e, 0x8e, 0x9e, 0x9c, 0x6c, 0xf6, 0x0b, 0xce, 0x2b, 0x38,
	0xaf, 0xe0, 0x82, 0xb3, 0x54, 0x20, 0x59, 0xc2, 0x44, 0x48, 0x4f, 0x62, 0x81, 0x3d, 0xbd, 0xbc,
	0x4f, 0xb7, 0x82, 0x56, 0x12, 0x81, 0x64, 0xf4, 0x8b, 0xfa, 0x73, 0xa3, 0x31, 0x8e, 0x0b, 0x77,
	0xde, 0xa1, 0x5c, 0x25, 0xde, 0x16, 0xfb, 0xe9, 0xad, 0x61, 0xb6, 0xdf, 0x30, 0x40, 0x91, 0xcc,
	0x60, 0x94, 0x67, 0xf1, 0xfc, 0xb8, 0x20, 0x56, 0xa5, 0xf3, 0x1d, 0xac, 0x37, 0x19, 0x2a, 0x48,
	0xe9, 0x60, 0x06, 0xa3, 0x08, 0xff, 0x94, 0xda, 0xaa, 0x24, 0x04, 0xc6, 0xa9, 0x97, 0x60, 0xb9,
	0xab, 0xa8, 0xd5, 0x5a, 0x80, 0xc2, 0x9f, 0x8f, 0xf4, 0x9a, 0xaa, 0xc9, 0x3d, 0x98, 0x78, 0x9c,
	0xaf, 0x82, 0xf9, 0xb8, 0x58, 0xd4, 0x3f, 0x9c, 0x6f, 0x70, 0x5e, 0x09, 0x0c, 0x71, 0xdc, 0x68,
	0xc8, 0x71, 0xbb, 0x21, 0x4f, 0xe1, 0xec, 0x75, 0x1e, 0xc6, 0x41, 0xbf, 0xf6, 0xbd, 0x04, 0xab,
	0x44, 0x0f, 0xb9, 0xad, 0x22, 0x1b, 0x31, 0x4a, 0xbc, 0x41, 0x36, 0x34, 0x7c, 0x88, 0xda, 0x15,
	0x58, 0x57, 0x3c, 0xf0, 0x7a, 0xaa, 0xf5, 0xbd, 0x23, 0xe5, 0xaa, 0xa2, 0x1d, 0xe2, 0x6a, 0x09,
	0xa7, 0x9f, 0x38, 0xa6, 0xfd, 0x3a, 0xf0, 0x02, 0xce, 0x34, 0x78, 0x88, 0xd2, 0x02, 0xac, 0x0f,
	0x5e, 0x9e, 0xfa, 0x3f, 0x8d, 0xb9, 0x54, 0x67, 0xa9, 0x20, 0x03, 0x14, 0x2e, 0xff, 0x4e, 0xe0,
	0xd6, 0x67, 0x6d, 0x96, 0xac, 0x61, 0xaa, 0xa9, 0x88, 0x43, 0x3b, 0x86, 0x08, 0x6d, 0x58, 0xb1,
	0x1f, 0x1e, 0xc4, 0x94, 0x5e, 0xd6, 0x30, 0xd5, 0xb9, 0x37, 0x50, 0x36, 0x5e, 0x9d, 0x81, 0xb2,
	0xf5, 0x70, 0x3e, 0xc2, 0xa4, 0xc8, 0x2f, 0x59, 0x74, 0xa2, 0xeb, 0x2f, 0xc1, 0x76, 0x0e, 0x41,
	0xf6, 0x16, 0x75, 0x44, 0x0d, 0x16, 0x1b, 0x71, 0x37, 0x58, 0x6c, 0x65, 0x7c, 0x0d, 0x53, 0x9d,
	0x2f, 0x03, 0x65, 0x23, 0xd3, 0x06, 0xca, 0x56, 0x40, 0xdf, 0xc3, 0x58, 0xc5, 0x88, 0x5c, 0x74,
	0x82, 0x6b, 0x71, 0xb4, 0x17, 0x07, 0x10, 0xf5, 0x23, 0xab, 0x89, 0x6d, 0x3c, 0x72, 0x6d, 0xfa,
	0x1b, 0x8f, 0xdc, 0x18, 0xf9, 0x5f, 0xe1, 0x76, 0x35, 0x94, 0xc9, 0xa3, 0xce, 0x0d, 0xad, 0x21,
	0x6f, 0x3f, 0xfe, 0x0f, 0x4a, 0x13, 0x5f, 0x4f, 0x8b, 0x6f, 0xd2, 0xf3, 0x7f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x2c, 0x6a, 0x85, 0x09, 0xe9, 0x06, 0x00, 0x00,
}
